UML-1556-OOL-ask-for-actor-role-when-no-match
ministryofjustice/opg-use-an-lpa pull request #1002
Opened 2021-07-22 12:58 UTC by GemTay

# Purpose

As a user 
If my LPA has been found but my details do not match
Then I am asked if I am a donor or attorney 
So that we can verify the user is authorised by that donor (they will know donor details)

This ticket is about directing the user through additional data capture that would allow a caseworker to properly cleanse an LPA record for the requesting user (both LPA data and personal user data).

Fixes UML-1556

## Approach

Created a new handler, form, route, and template for the actor role page, and hooked it upto the no match case in the `CheckYourAnswersHandler`. Partially configured the ActorRoleHandler to redirect the user to the contact details page if the selected the 'Donor' option, and left a TODO comment for the attorney option which is to be completed as part of UML-1606. 

I created a new handler and route, and template for the contact details page however did not create the contact details form as this work has been split into a separate ticket UML-1555. 

Created 2 ui tests for the new journey which is under the `allow_older_lpas` feature flag

## Checklist

* [x] I have performed a self-review of my own code
* [x] I have added tests to prove my work
* [ ] The product team have tested these changes

2021-07-23 09:29 UTC, cooperaj commented on service-front/app/src/Actor/src/Form/ActorRole.php
> +                                NotEmpty::IS_EMPTY => 'Select whether you are the donor or an attorney on the LPA',
Has this been added to the translation file?

2021-07-23 09:42 UTC, GemTay commented on service-front/app/src/Actor/src/Form/ActorRole.php
> +                                NotEmpty::IS_EMPTY => 'Select whether you are the donor or an attorney on the LPA',
Uchenna is going to get the translations for this and everything else on the OOL journey to add them in at the end, so that all tickets aren't blocked by welsh. As its under the feature flag anyway we don't need it right away

2021-07-28 08:20 UTC, lukejolliffe commented
I'm wondering if we should add all the things that need to be translated to the pot file? It may make it easier to keep track of all the translations that are needed.

2021-07-28 08:47 UTC, lukejolliffe requested changes

2021-07-28 08:47 UTC, lukejolliffe commented on service-front/app/src/Actor/src/Form/ActorRole.php
> +                                NotEmpty::IS_EMPTY => 'Select whether you are the donor or an attorney on the LPA',
Just need this bit in the pot file as well.

2021-07-28 09:04 UTC, GemTay commented on service-front/app/src/Actor/src/Form/ActorRole.php
> +                                NotEmpty::IS_EMPTY => 'Select whether you are the donor or an attorney on the LPA',
Whoops, missed that - added in now

2021-07-28 09:06 UTC, lukejolliffe submitted a review, later dismissed

2021-07-29 12:28 UTC, lukejolliffe approved these changes

2021-07-29 12:36 UTC, cooperaj commented on service-front/app/src/Actor/src/Form/ActorRole.php
> +                                NotEmpty::IS_EMPTY => 'Select whether you are the donor or an attorney on the LPA',
^ yeah, thats what I meant :)

2021-07-29 12:37 UTC, cooperaj approved these changes

2021-07-29 12:41 UTC, merged