UML-1568-Confirm-older-lpa
ministryofjustice/opg-use-an-lpa pull request #1005
Opened 2021-07-27 15:06 UTC by GemTay

# Purpose

As a user
I want to be asked to confirm the LPA I am requesting a key when a match is found

Fixes UML-1568

## Approach

Refactored the validation steps in the LpaActionsHandler, and moved these steps into a new validation function in the OlderLpaService to be reused. Split API journey into OlderLpaValidationHandler and OlderLpaConfirmationHandler

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-07-29 12:34 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/CreateActivationKeyHandler.php
> +                filter_var($data['force_activation_key'], FILTER_VALIDATE_BOOLEAN) ?: false
Is it not better to do this casting as a part of the form definition/filtering?

2021-07-29 12:34 UTC, cooperaj commented on service-front/app/src/Common/src/Service/Lpa/Response/Parse/ParseOlderLpaMatchResponse.php
> +
```suggestion
```

2021-07-30 08:30 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/CreateActivationKeyHandler.php
> +                filter_var($data['force_activation_key'], FILTER_VALIDATE_BOOLEAN) ?: false
Applied...

2021-08-03 13:04 UTC, GemTay commented on service-api/app/features/context/Acceptance/LpaContext.php
> +            'lpaActorToken'  => $this->userLpaActorToken
the lpa actor token is only in the response if the user has already added the LPA

2021-08-03 13:07 UTC, GemTay commented on service-api/app/src/App/src/Handler/OlderLpaConfirmationHandler.php
> +    public function handle(ServerRequestInterface $request): ResponseInterface
create a doc block for this handle function

2021-08-03 13:08 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +        if (!isset($lpaMatchResponse['lpa-id'])) {
theres 2 codeCov issues reported here that need resolving

2021-08-03 13:10 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +        $this->resolveActor;
this isn't needed since you're calling it in the `lookupActorInLpa` function. Nor is the `'actor' => $actor,` included in the return statement below

2021-08-03 13:11 UTC, GemTay commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +                    'actor' => null
`actor` wont be needed as a result of my previous comment

2021-08-03 13:13 UTC, GemTay commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +        $this->expectExceptionMessage('LPA has an activation key already');
Best to add some assertions on the exception's additional data to check it contains everything we expect

2021-08-03 13:17 UTC, GemTay commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> -        $result = $service->checkLPAMatchAndGetActorDetails($this->userId, $dataToMatch);
You've switched which function you're testing here, so we'll have lost some test coverage on `checkLPAMatchAndGetActorDetails`. We need tests for both

2021-08-03 13:21 UTC, GemTay commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +                         ));
the indentation needs fixing in the above

2021-08-03 14:36 UTC, GemTay commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +       $response = $service->validateOlderLpaRequest($this->userId, $dataToMatch);
How come you're calling both functions here? $result isnt being used either

2021-08-03 14:39 UTC, GemTay commented on service-front/app/features/context/Integration/LpaContext.php
> -    public function iRequestForANewActivationKeyAgain()
why has this test been removed?

2021-08-03 14:41 UTC, GemTay commented on service-front/app/features/context/Integration/LpaContext.php
> +        // API call for getLpaById call happens inside of the check access codes handler
this comment refers to the check access codes handler which isn't relevant here

2021-08-03 14:43 UTC, GemTay commented on service-front/app/features/context/Integration/LpaContext.php
> +            $addOlderLpa->validate(
There needs to be some assertions in this step on what we expect to get back

2021-08-03 14:50 UTC, GemTay commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +#| "\" class=\"govuk-link\">Let us know if you have moved.</a>"
something's gone wrong with this translation :/

2021-08-03 14:55 UTC, GemTay commented on service-front/app/src/Actor/src/Form/CreateNewActivationKey.php
> +            ],
Rather than storing all this data hidden form fields, you could store them in the session instead? Both solutions are fine but I guess theres less files/work involved with storing data in the session

2021-08-03 15:00 UTC, GemTay commented on service-front/app/src/Common/src/Service/Log/EventCodes.php
> +    public const OLDER_LPA_FOUND = 'OLDER_LPA_FOUND';
this new event code will need to be added to the terraform cloudwatch metrics file so we can track it

2021-08-03 15:05 UTC, GemTay commented on service-front/app/src/Common/src/Service/Lpa/AddOlderLpa.php
> -        bool $forceActivationKey = false
thinking about it, the force flag will always have to be `false` for the validate path, so you could remove it as a parameter as we don't want anyone to ever be able to change that

2021-08-03 16:02 UTC, GemTay commented on service-front/app/test/CommonTest/Service/Lpa/Response/OlderLpaMatchResponseTest.php
> +    public function it_allows_donor_name_and_lpa_type_to_be_set_and_get()
I think there needs to be a few more tests for this, including the attorney. Also a case where the getAttorney function returns null as the actor is the donor

2021-08-03 16:02 UTC, GemTay commented on service-front/app/test/CommonTest/Service/Lpa/Response/Parse/ParseOlderLpaMatchResponseTest.php
> +    public function it_creates_an_already_added_dto_from_array_data()
this test name doesn't reflect the correct dto

2021-08-03 16:03 UTC, GemTay commented on service-front/app/test/CommonTest/Service/Lpa/Response/Parse/ParseOlderLpaMatchResponseTest.php
> +    public function it_creates_an_already_added_dto_from_array_data_with_null_name_fields()
same here

2021-08-03 16:04 UTC, GemTay commented on service-front/app/test/CommonTest/Service/Lpa/Response/Parse/ParseOlderLpaMatchResponseTest.php
> +    public function alreadyAddedDataProvider()
misnamed data provider and the data needs to include scenarios with both an attorney and donor

2021-08-04 09:08 UTC, SeemaMenon commented on service-front/app/test/CommonTest/Service/Lpa/Response/Parse/ParseOlderLpaMatchResponseTest.php
> +    public function it_creates_an_already_added_dto_from_array_data()
My mistake from the copy paste and not correcting  ...

2021-08-04 09:44 UTC, SeemaMenon commented on service-front/app/test/CommonTest/Service/Lpa/Response/Parse/ParseOlderLpaMatchResponseTest.php
> +    public function alreadyAddedDataProvider()
Ok

2021-08-04 11:53 UTC, SeemaMenon commented on service-front/app/src/Common/src/Service/Log/EventCodes.php
> +    public const OLDER_LPA_FOUND = 'OLDER_LPA_FOUND';
Added

2021-08-04 11:53 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Form/CreateNewActivationKey.php
> +            ],
I think for now let's leave it here unless there's a more forcing reason.  
I shall create a new improvement ticket to move this to session and change tests too [if that's OK]

2021-08-04 12:56 UTC, SeemaMenon commented on service-front/app/features/context/Integration/LpaContext.php
> +            $addOlderLpa->validate(
Aah yes, added .

2021-08-04 14:32 UTC, SeemaMenon commented on service-front/app/features/context/Integration/LpaContext.php
> -    public function iRequestForANewActivationKeyAgain()
It's clubbed with one of the existing steps.

<img width="663" alt="Screenshot 2021-08-04 at 15 31 39" src="https://user-images.githubusercontent.com/6483585/128199653-3f79584b-7c2a-4f55-8dd4-626f56a303ae.png">

2021-08-04 14:40 UTC, SeemaMenon commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +       $response = $service->validateOlderLpaRequest($this->userId, $dataToMatch);
The first one is removed :)

2021-08-06 14:46 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +        if (!isset($lpaMatchResponse['lpa-id'])) {
Removed the checks here for lpa-id and actor-id as they are not needed and will never be empty/null in the response here.  A null check is done in the lookupActorInLpa  function and an exception is thrown  at this point.

2021-08-09 06:39 UTC, SeemaMenon commented on service-api/app/test/fixtures/test_lpa.json
> +}
Had to end up end creating a new LPA test file, as  altering the example_lpa.json [by adding a second LPA] was giving errors on multiple tests.

This test files can all be consolidated and corrected as part of the new ticket raised to correct the data fixtures for the API behat tests.  [Ref: UML-1646]

2021-08-10 13:10 UTC, cooperaj commented on service-front/app/test/ActorTest/Form/CreateNewActivationKeyTest.php
> +            'force_activation_key'      => Hidden::class,
```suggestion
            'force_activation_key' => Hidden::class,
```
It's not important for this PR but going forward could we please ensure that this kind of formatting uses a single space for the longest line, all other lines are based off that.

2021-08-10 13:10 UTC, cooperaj commented on service-front/app/test/CommonTest/Service/Lpa/Response/Parse/ParseOlderLpaMatchResponseTest.php
> +        $this->expectExceptionMessage(
Don't worry about changing but it's not important to check exception message values unless we're going to be relying on them in code. They're subject to change as it's just for us normally

2021-08-10 15:37 UTC, SeemaMenon commented on .idea/remote-mappings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I thought I removed this file and file changes came down to 34. This needs removing.

2021-08-10 17:05 UTC, SeemaMenon commented on service-front/app/test/CommonTest/Service/Lpa/Response/Parse/ParseOlderLpaMatchResponseTest.php
> +        $this->expectExceptionMessage(
Ok, Thanks Adam

2021-08-10 17:05 UTC, SeemaMenon commented on service-api/app/config/routes.php
> +        '/v1/older-lpa/validate',
Just renamed the request-letter to validate , as going we will be doing a validation which checks the LPA match and fetched actor match details. And then play back the found details to the user. User on confirming will then request generation of key/letter. The latter is the new end point '/v1/older-lpa/confirm' which is a post which basically requests for the letter prior to which a validation is done once again for affirmation.

This now matches the pattern we follow for the normal Add LPA journey

2021-08-11 09:18 UTC, GemTay commented on service-api/app/config/routes.php
> +        '/v1/older-lpa/validate',
In that case, the `/v1/older-lpa/confirm` route should be a patch and `/v1/older-lpa/validate` should be a post  :)

2021-08-12 07:54 UTC, SeemaMenon commented on service-api/app/config/routes.php
> +        '/v1/older-lpa/validate',
Yes, true...... and done.

2021-08-16 11:46 UTC, SeemaMenon commented on service-api/app/features/context/Acceptance/LpaContext.php
> +            'lpaActorToken'  => $this->userLpaActorToken
Done

2021-08-17 10:13 UTC, cooperaj commented on service-front/app/src/Common/src/Service/Lpa/AddOlderLpa.php
> +        }
```suggestion
        $response = $this->apiClient->httpPatch('/v1/older-lpa/confirm', $data);
```

No need to switch on the code if the only option is default and with that gone there is no benefit to catching and throwing just one type of exception.

2021-08-17 10:21 UTC, cooperaj requested changes

2021-08-17 10:21 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/RequestActivationKey/CreateActivationKeyHandler.php
> +                filter_var($data['force_activation_key'], FILTER_VALIDATE_BOOLEAN) ?: false
This casting/value check, as well as others above, should be done as a part of the filtering on the `CreateNewActivationKey` form.

2021-08-18 18:49 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Form/CreateNewActivationKey.php
> +            ],
Ticket created : UML-1689

2021-08-19 07:33 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/RequestActivationKey/CreateActivationKeyHandler.php
> +                filter_var($data['force_activation_key'], FILTER_VALIDATE_BOOLEAN) ?: false
done

2021-08-19 07:33 UTC, SeemaMenon commented on service-front/app/src/Common/src/Service/Lpa/AddOlderLpa.php
> +        }
done

2021-08-20 05:41 UTC, SeemaMenon commented
Two new tickets created while working on this ticket.
UML-1646      -> To correct the test fixtures
 UML-1689     -> To replace using form hidden fields and use session data instead

2021-08-20 05:51 UTC, SeemaMenon commented
This PR is ready for review.

However on multiple attempts the same  flaky tests seem to fail continuously. Doesn't happen locally.
<img width="802" alt="Screenshot 2021-08-20 at 06 49 19" src="https://user-images.githubusercontent.com/6483585/130186096-7ae5bccb-062e-4b12-9c5a-e1ae7e512eb1.png">

2021-08-20 11:26 UTC, cooperaj approved these changes

2021-08-23 16:31 UTC, lukejolliffe approved these changes

2021-08-24 10:10 UTC, lukejolliffe approved these changes

2021-08-24 10:26 UTC, merged