Save LPA with TTL
ministryofjustice/opg-use-an-lpa pull request #1024
Opened 2021-08-04 07:46 UTC by lukejolliffe

# Purpose

_Briefly describe the purpose of the change, and/or link to the JIRA ticket for context_

Fixes UML-####

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-08-04 09:03 UTC, andrewpearce-digital reviewed
Terraform and DyanmoDB script changes all look good

2021-08-10 10:41 UTC, GemTay commented on service-api/app/features/context/Acceptance/LpaContext.php
> +                            'Added' => (new DateTime('2020-01-01'))->format('Y-m-d\TH:i:s.u\Z')
I dont think this could be an issue, but its always just best practice to avoid hardcoding datetime's, as we have had tests break in the past because of them. Just do a `(new DateTime('+1 week'))->format('Y-m-d\TH:i:s.u\Z')` instead

2021-08-10 10:48 UTC, GemTay commented on service-api/app/features/context/Acceptance/LpaContext.php
> +                            'Added' => (new DateTime('2020-01-01'))->format('Y-m-d\TH:i:s.u\Z')
When users are requesting a new activation key again (they already have one), we should have a test for both when we're writing the record to out DB for the first time (this test step), and also when we're just updating the TTL of the record that already exists

2021-08-11 14:00 UTC, GemTay commented on service-api/app/src/App/src/Service/ActorCodes/ActorCodeService.php
> +                    (string)$details['actor']['details']['id']
are `$actorId` and `(string)$details['actor']['details']['id']` not the same ?

2021-08-13 11:25 UTC, lukejolliffe commented on service-api/app/features/context/Acceptance/LpaContext.php
> +                            'Added' => (new DateTime('2020-01-01'))->format('Y-m-d\TH:i:s.u\Z')
There is a separate ticket for this UML-1643

2021-08-13 11:26 UTC, lukejolliffe commented on service-api/app/features/context/Acceptance/LpaContext.php
> +                            'Added' => (new DateTime('2020-01-01'))->format('Y-m-d\TH:i:s.u\Z')
```suggestion
                            'Added' => (new DateTime())->format('Y-m-d\TH:i:s.u\Z')
```

2021-08-13 11:26 UTC, lukejolliffe commented on service-api/app/features/context/Acceptance/LpaContext.php
> +                            'Added' => (new DateTime('2020-01-01'))->format('Y-m-d\TH:i:s.u\Z')
```suggestion
                            'Added' => (new DateTime())->format('Y-m-d\TH:i:s.u\Z')
```

2021-08-13 11:27 UTC, lukejolliffe commented on service-api/app/features/context/Integration/LpaContext.php
> +                                'Added' => (new DateTime('2020-01-01'))->format('Y-m-d\TH:i:s.u\Z'),
```suggestion
                                'Added' => (new DateTime())->format('Y-m-d\TH:i:s.u\Z'),
```

2021-08-13 11:38 UTC, lukejolliffe commented on service-api/app/src/App/src/Service/ActorCodes/ActorCodeService.php
> +                    (string)$details['actor']['details']['id']
the actorId here is actually the userId, not sure why but I'll clean it up!

2021-08-17 08:41 UTC, cooperaj commented on service-api/app/test/AppTest/DataAccess/DynamoDb/UserLpaActorMapTest.php
> +use function Symfony\Component\Translation\t;
Whats this used for?

2021-08-17 09:20 UTC, cooperaj commented on service-api/app/test/AppTest/Handler/LpasActionsHandlerTest.php
> +    public function test_when_sirius_is_down_remove_stored_LPA_request()
As a preference and to keep things consistent we use a @test docblock rather than a prefix.
```suggestion
    /**
     * @test
     */
    public function when_sirius_is_down_remove_stored_LPA_request()
```

2021-08-17 09:21 UTC, cooperaj commented on service-api/app/test/AppTest/Handler/LpasActionsHandlerTest.php
> +    public function test_when_sirius_is_down_remove_stored_LPA_request()
Or, the single line variant to keep it tidy
```suggestion
    /** @test */
    public function test_when_sirius_is_down_remove_stored_LPA_request()
```

2021-08-17 09:22 UTC, cooperaj commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +            Argument::exact('test-lpaId'),
Argument::exact is equal to just specifying the scalar value i.e. 'test-lpaId'

2021-08-17 09:24 UTC, cooperaj commented on service-api/seeding/dynamodb.py
> +import simplejson as json
What does this do?

2021-08-17 09:25 UTC, cooperaj commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +use PhpParser\Node\Arg;
This doesn't look used?

2021-08-17 09:27 UTC, cooperaj commented on service-api/app/test/AppTest/Handler/LpasActionsHandlerTest.php
> +        $featureEnabledProphecy->method('__invoke')->willReturn(false);
```suggestion
        $featureEnabledProphecy->__invoke()->willReturn(false);
```
Works and is used elsewhere in the codebase.

2021-08-17 09:27 UTC, cooperaj commented on service-api/app/test/AppTest/Handler/LpasActionsHandlerTest.php
> +        $olderLpaServiceProphecy->hasActivationCode('number', '123')->willReturn(null);
This shouldn't be necessary, though as you mentioned something doesn't seem right.

2021-08-17 09:42 UTC, cooperaj commented on service-api/app/src/App/src/DataAccess/DynamoDb/UserLpaActorMap.php
> +    public function create(string $uuid, string $lpaId, string $userId, string $actorId, string $expiryInterval = null)
Why rename the parameters? In PHP8 named parameters are available and this kind of change could break code quite easily. Did you change the doc referred to by @inheritDoc?

2021-08-17 09:54 UTC, cooperaj commented on service-api/app/src/App/src/Handler/LpasActionsHandler.php
> +                $this->olderLpaService->removeLpaRequest($requestId);
This fails silently if the record is not there? i.e. feature flag toggled off.

2021-08-17 09:56 UTC, cooperaj requested changes
Added a few things

2021-08-17 10:33 UTC, cooperaj commented on service-api/app/test/AppTest/Handler/LpasActionsHandlerTest.php
> +        $featureEnabledProphecy->method('__invoke')->willReturn(false);
Oh, sorry, bad suggestion. You'll need to pass in the expected parameter to 'invoke' as well. i.e. 'save-lpa-requests' or whatever it is.

2021-08-17 10:35 UTC, cooperaj commented on service-api/app/test/AppTest/Handler/LpasActionsHandlerTest.php
> +        $featureEnabledProphecy =  $this->getMockBuilder(FeatureEnabled::class)
Wait. I didn't see this, why use Mock builder and not prophesize? That would explain the need to mock all functions. Only prophesize does that magic for you.

2021-08-17 10:37 UTC, cooperaj commented on service-api/app/test/AppTest/Handler/LpasActionsHandlerTest.php
> +        $featureEnabledProphecy =  $this->getMockBuilder(FeatureEnabled::class)
This should be a prophecy. We only use mocks in some very specific circumstances (ones that prophecy is not capable of mocking, such as final or abstract classes)

2021-08-17 10:38 UTC, cooperaj commented on service-api/app/test/AppTest/Handler/LpasActionsHandlerTest.php
> +        $featureEnabledProphecy->method('__invoke')->willReturn(true);
```suggestion
        $featureEnabledProphecy->__invoke('save_older_lpa_requests')->willReturn(true);
```

2021-08-17 10:56 UTC, lukejolliffe commented on service-api/app/test/AppTest/Handler/LpasActionsHandlerTest.php
> +        $featureEnabledProphecy =  $this->getMockBuilder(FeatureEnabled::class)
I didn't think I saw anything in the prophesize documentation. I'm not even sure if I saw if it didn't work I just assumed it wouldn't maybe? I'll attempt to change this then :)

2021-08-17 14:43 UTC, lukejolliffe commented on service-api/seeding/dynamodb.py
> +import simplejson as json
simplejson can actually print Doubles that are being used by dynamoDb. Using the standard json library the print out errors

2021-08-17 14:44 UTC, cooperaj commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +        $this->featureEnabled = $this->prophesize(FeatureEnabled::class);
Generally we do a bit of a Java thing here and suffix our prophecies as "Prophecy". It looks like two sneaked in in a previous PR but it's probably better to be consistent across the project.

2021-08-17 14:48 UTC, lukejolliffe commented on service-api/app/test/AppTest/DataAccess/DynamoDb/UserLpaActorMapTest.php
> +use function Symfony\Component\Translation\t;
Who knows :D

2021-08-17 14:53 UTC, lukejolliffe commented on service-api/app/src/App/src/DataAccess/DynamoDb/UserLpaActorMap.php
> +    public function create(string $uuid, string $lpaId, string $userId, string $actorId, string $expiryInterval = null)
Yeah this change is messy and shouldn't be kept. I did something dodgy (I think I completely rewrote this line for some reason) when adding the new parameter. When I was reading the code siriusUid is a little ambiguous in this case, A siriusUid implies it could also be an actor which it couldn't

2021-08-18 10:27 UTC, cooperaj commented on service-api/app/src/App/src/DataAccess/DynamoDb/UserLpaActorMap.php
> +        $added = new \DateTime();
This is fine as is but you might want to look at the DateTimeImmutable class for instances where changing after the fact is not needed. It helps nail things down for the future.

2021-08-18 10:27 UTC, cooperaj commented on service-api/app/src/App/src/DataAccess/DynamoDb/UserLpaActorMap.php
> +        if ($expiryInterval != null) {
```suggestion
        if ($expiryInterval !== null) {
```
Always be super explicit (granted, that in the case of null there isn't much that can go wrong)

2021-08-18 10:27 UTC, cooperaj commented on service-api/app/src/App/src/DataAccess/Repository/UserLpaActorMapInterface.php
> +     * @param string $actorId
With the reversions to the parameter name changes, and given the confusion, it could be worth adding some parameter description text. i.e.

```suggestion
     * @param string $actorId The Sirius formated UID that is associated with an actor in the system
```

2021-08-18 10:27 UTC, cooperaj commented on service-api/app/src/App/src/Handler/LpasActionsHandler.php
> +    /**
A docblock like this isn't necessary unless it adds additional information not already found in the method signature i.e. description text, usages etc.

2021-08-18 10:27 UTC, cooperaj commented on service-api/app/src/App/src/Service/ActorCodes/ActorCodeService.php
>       * @return array|null
This isn't even correct. The method signature says nullable string. 

As a general rule, if you're in a file making changes, updating the docblocks to be accurate is good code scouting.

2021-08-18 10:27 UTC, cooperaj commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +    public function removeLpaRequest(string $requestId)
This method is not actually verifying that the LPA we have stored is a request v.s. an actual LPA record. That being the case it's technically identical to an other public method in the LpaService that allows deletion of LPA records. If you want to keep this here for simplicities sake then it should probably be private (or implement the additional checks to ensure only requests are covered.

2021-08-18 10:27 UTC, cooperaj commented on service-api/app/test/AppTest/Service/ActorCodes/ActorCodeServiceTest.php
> +            Argument::exact("1")
If this is a string then it should be single quoted to stop the interpolation overhead. That said this line could also be 
```suggestion
            '1'
```

2021-08-18 10:27 UTC, cooperaj commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +        )->shouldBeCalled();
We should avoid usage of inexact matching unless we're doing processing in the SUT that produces unpredictable data i.e. password hashing. Since we're in full control of the test input here (bar the guid) we should be matching on exactly that stuff.

```suggestion
        $this->userLpaActorMapProphecy->create(
            Argument::type('string'),
            $this->userId,
            $this->lpaUid,
            $this->actorId,
            'P1Y'
        )->shouldBeCalled();
```

2021-08-18 10:27 UTC, cooperaj commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +        )->shouldBeCalled();
Same applies to other instances of this in this test file

2021-08-18 10:27 UTC, cooperaj commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +        $service->storeLPARequest('test-lpaId', 'test-user', '1');
Why these strings and the not class properties as used above?

2021-08-18 16:16 UTC, cooperaj approved these changes
Nice work!

2021-08-19 07:42 UTC, merged