Uml 1630 consent and check details for cleansing
ministryofjustice/opg-use-an-lpa pull request #1042
Opened 2021-08-18 16:40 UTC by GemTay

# Purpose

As a user I would like to be able to review and change the information that is being sent when my LPA needs cleansing. I also need to be able to give my consent for my details to be collected and used to contact me.

Fixes UML-1630

## Approach

Created a new handler for the consent and check details page which displays the correct data based on a bunch of logic checks on the data set in the session. Created a new abstract handler and extended all handlers in this section of the journey (ActorRole, DonorDetails, ContactDetails) so that when users go back and change data on those pages, they are then taken back to the consent and check details page, skipping over the next pages they have already completed. Fixed the validator on the Contact Details page to display the error message when both fields are filled. Added logging with new event codes for Jude to see the split between donors/attorney requesting activation keys, as well as those providing/not providing their phone number. Created tests for all scenarios including users going back and changing data to expect the page skipping functionality. 

## Checklist

* [x] I have performed a self-review of my own code
* [x] I have added relevant logging with appropriate levels to my code
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-08-18 16:54 UTC, GemTay commented on service-front/app/src/Common/src/Validator/OptionSelectedValidator.php
> +        $valid = (!empty($value['telephone']) xor $value['no_phone'] === 'yes');
never thought id come across a scenario where I needed to use the xor operator! :D

2021-08-18 16:59 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/RequestActivationKey/CheckDetailsAndConsentHandler.php
> +                ]
Jude has requested that we capture the donor/attorney role split for requesting activation keys. She said the phone/no phone split isn't strictly needed however it would be a bonus to have

2021-08-19 08:32 UTC, cooperaj commented on service-front/app/src/Common/src/Validator/OptionSelectedValidator.php
> +        $valid = (!empty($value['telephone']) xor $value['no_phone'] === 'yes');
I've literally never used it.

2021-08-19 13:42 UTC, lukejolliffe commented on service-front/app/src/Actor/src/Handler/RequestActivationKey/ActorRoleHandler.php
> +        return !$this->session->has('opg_reference_number')
I think this should be in the abstract handler so we don't have to define all these required fields every time

2021-08-19 14:06 UTC, lukejolliffe requested changes

2021-08-19 14:15 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/request-activation-key/check-details-and-consent.html.twig
> +                                <a class="govuk-link" id="change-name" href="{{ path('lpa.add.actor-role') }}">
Ah good spot, i didn't see them!

2021-08-19 14:26 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/RequestActivationKey/ActorRoleHandler.php
> +        return !$this->session->has('opg_reference_number')
Good point, that'll be much neater

2021-08-19 14:39 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/RequestActivationKey/CheckDetailsAndConsentHandler.php
> +                    'role'  => $this->data['actor_role'] === 'donor' ?
Yeah I have considered this, however thats out of scope for this ticket. Its an issue that the person who picks that other ticket up will have to figure out - ha!

2021-09-14 15:40 UTC, SeemaMenon commented on service-api/app/features/context/Acceptance/LpaContext.php
> +                'postcode' => $this->userPostCode,
Lost some formatting here

2021-09-14 15:40 UTC, SeemaMenon commented on service-api/app/features/context/Acceptance/LpaContext.php
> +            'caseSubtype' => $this->lpa->caseSubtype,
Is the formatting removed on purpose?

2021-09-14 16:05 UTC, SeemaMenon commented on service-front/app/features/actor-add-an-older-lpa.feature
> +    When I enter both a telephone number and select that I cannot take calls
Noticed if user leaves a space by mistake or does not empty the telephone field completely is considered as a character and user is shown the error message. This could create a confusion right?
 
<img width="589" alt="Screenshot 2021-09-14 at 16 44 23" src="https://user-images.githubusercontent.com/6483585/133293342-4e8628d5-4380-4879-b7cf-187f6567e281.png">

2021-09-14 16:22 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/RequestActivationKey/CheckDetailsAndConsentHandler.php
> +                ]
I see a telephone number validation has not been requested as AC, however I think it make sense to have a basic check for telephone field after checking with Sarah? [Could be a separate ticket too]

<img width="564" alt="Screenshot 2021-09-14 at 17 10 34" src="https://user-images.githubusercontent.com/6483585/133295863-695d6513-a162-41d6-8ab7-f26cfef22d3c.png">

2021-09-14 17:48 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/RequestActivationKey/CheckDetailsAndConsentHandler.php
> +                    'role'  => $this->data['actor_role'] === 'donor' ?
This will be handled in 1570

2021-09-15 09:11 UTC, GemTay commented on service-api/app/features/context/Acceptance/LpaContext.php
> +            'caseSubtype' => $this->lpa->caseSubtype,
No, its the code formatter doing it automatically which is a bit annoying

2021-09-15 09:12 UTC, GemTay commented on service-front/app/features/actor-add-an-older-lpa.feature
> +    When I enter both a telephone number and select that I cannot take calls
I'll add in the trim filter 👍🏼

2021-09-15 10:17 UTC, lukejolliffe approved these changes

2021-09-15 10:22 UTC, merged