UML-1578 LPA already requested
ministryofjustice/opg-use-an-lpa pull request #1082
Opened 2021-09-09 12:16 UTC by GemTay

# Purpose

As a user I want to be told when I am trying to add an LPA that I have already requested a key for.

Fixes UML-1578

## Approach

LpaAlreadyAdded class now returns a `notActivated = true` in the data which results in a bad request being thrown and caught in the front to handle this scenario. Fully covered by tests

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [x] I have added tests to prove my work
* [ ] The product team have tested these changes

2021-09-13 14:22 UTC, lukejolliffe approved these changes

2021-09-13 14:28 UTC, lukejolliffe requested changes
The AlreadyAddedCheck will need to be changed in ValidateAddLpaData otherwise I think it will stop users from adding LPAs by code?

2021-09-21 08:33 UTC, cooperaj submitted a review, later dismissed

2021-09-21 10:30 UTC, lukejolliffe approved these changes

2021-09-21 10:32 UTC, merged