Create links
ministryofjustice/opg-use-an-lpa pull request #1190
Opened 2021-10-29 09:56 UTC by lukejolliffe

# Purpose

Create feedback links

Fixes UML-1766

## Checklist

* [x] I have performed a self-review of my own code
* ~~I have added relevant logging with appropriate levels to my code~~
* ~~I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant~~
* ~~I have added tests to prove my work~~
* ~~I have added welsh translation tags and updated translation files~~ will add welsh after gone live since survey is only in english
* [x] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [x] The product team have tested these changes

2021-11-03 14:49 UTC, cooperaj requested changes

2021-11-03 14:49 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/check-code-not-found.html.twig
> +                        <a class="govuk-link" href="https://eu.surveymonkey.com/r/ViewSatisfactionScore">{% trans %} Give us feedback about this service {% endtrans %}</a>
```suggestion
                        <a class="govuk-link" href="https://eu.surveymonkey.com/r/ViewSatisfactionScore">{% trans %}Give us feedback about this service{% endtrans %}</a>
```

2021-11-03 14:49 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/view-lpa.html.twig
> +            <a class="govuk-link" href="https://eu.surveymonkey.com/r/ViewSatisfactionScore">{% trans %} Give us feedback about this service {% endtrans %}</a>
```suggestion
            <a class="govuk-link" href="https://eu.surveymonkey.com/r/ViewSatisfactionScore">{% trans %}Give us feedback about this service{% endtrans %}</a>
```

2021-11-04 16:59 UTC, SeemaMenon approved these changes

2021-11-05 09:35 UTC, cooperaj approved these changes

2021-11-05 10:02 UTC, merged