UML-1596 Check access code page now shows days remaining for code to expire
ministryofjustice/opg-use-an-lpa pull request #1230
Opened 2021-11-12 10:08 UTC by SeemaMenon

# Purpose
https://opgtransform.atlassian.net/browse/UML-1596

Fixes UML-1596

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-11-16 16:35 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/partials/check-code-details.html.twig
> +                {% trans with {'%days%': days_remaining_to_expiry(code.Expires)} %}Access code expires in %days% days{% endtrans %}
```suggestion
                {% trans count days_remaining_to_expiry(code.Expires) %}Access code expires in %count% day|Access code expires in %count% days{% endtrans %}
```
This will need pluralisation. The suggested changes above are from memory so double check they work.

2021-11-23 15:50 UTC, lukejolliffe requested changes

2021-11-23 15:50 UTC, lukejolliffe commented on service-front/app/src/Actor/templates/actor/partials/check-code-details.html.twig
> +                {% trans with {'%date%': check_date(code.Expires, 'Y-m-d\TH:i:sP')} %}Access code expired %date%{% endtrans %}
Can we not just use code_date, is a new function really needed?

2021-11-23 17:09 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/partials/check-code-details.html.twig
> +                {% trans with {'%date%': check_date(code.Expires, 'Y-m-d\TH:i:sP')} %}Access code expired %date%{% endtrans %}
I thought the code_date didn't work then...but it obviously does. Good shout @lukejolliffe.
Have changed code to use code_date and removed the introduced function and test around it.

2021-11-23 17:09 UTC, SeemaMenon commented
@lukejolliffe - request a review again please.

2021-11-23 17:14 UTC, lukejolliffe approved these changes

2021-11-23 17:25 UTC, merged