Uml-1623 update instructions and preferences when unknown
ministryofjustice/opg-use-an-lpa pull request #1256
Opened 2021-11-26 15:10 UTC by lukejolliffe

# Purpose

Instructions and preferences when the donor has signed before 2016 should have more information than just "Unknown" Users are told that they cannot be found and have a link to read more on another page.

Fixes UML-1623

## Checklist

* [x] I have performed a self-review of my own code
* I have added relevant logging with appropriate levels to my code
* I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [x] I have added tests to prove my work
* [x] I have added welsh translation tags and updated translation files
* [x] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-11-30 13:25 UTC, SeemaMenon commented on service-front/app/src/Viewer/templates/viewer/instructions-preferences-signed-before-2016.html.twig
> +{% endblock %}
This template being common to  both actor and viewer, is it not ideal to have it in common/templates/partials  reducing duplication?  And in handler as below:

```
return new HtmlResponse($this->renderer->render('partials::instructions-preferences-signed-before-2016', [
            'user' => $user,
        ]));
```

2021-12-01 15:14 UTC, SeemaMenon submitted a review, later dismissed

2021-12-01 16:24 UTC, cooperaj requested changes

2021-12-01 16:24 UTC, cooperaj commented on service-front/app/features/actor-view-lpa.feature
> +    And I request to view an LPA which has a donor signature before 2016
Why the request to view the dashboard if you're immediately then going here?

The nature of these tests are that you mock what you need, go to a page and do whatever action you'd like to do. The dashboard stage above is just extra mocking and running of code that does not affect the end result.

2021-12-01 16:24 UTC, cooperaj commented on service-front/app/features/context/UI/LpaContext.php
> +            'lpa' => $this->lpa,
Needs an added field as this will break tests under PHP8 without it. (our api returns 'added' and we rely on it)

2021-12-01 16:24 UTC, cooperaj commented on service-front/app/features/context/UI/LpaContext.php
> +        $this->ui->assertPageContainsText('View LPA summary');
Could just navigate directly to the page rather than coming from the dashboard?

2021-12-01 16:24 UTC, cooperaj commented on service-front/app/features/context/UI/ViewerContext.php
> +        $this->iHaveBeenGivenAccessToAnLPAViaShareCode();
How many of these steps are strictly necessary? Is the outcome of this fixture data merely that the user is looking at the LPA summary page? That can be easily done by mocking the APIs and going straight there.

2021-12-01 16:24 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/view-lpa-summary.html.twig
> +                                {% trans %}We cannot show whether or not this <abbr title="lasting power of attorney">LPA</abbr> has preferences or instructions. {% endtrans %} <a class="govuk-link"
Would this not be a single translatable statement? Read More may have different placement under Welsh?

And maybe a content issue but I thought the usage of Read More was frowned upon.

2021-12-01 16:24 UTC, cooperaj commented on service-front/app/src/Common/src/ConfigProvider.php
> +                'common'   => [__DIR__ . '/../templates/common']
Nice. Literally looking at this earlier confused as to why these were partials.

2021-12-01 16:24 UTC, cooperaj commented on service-front/app/src/Common/templates/layout/default.html.twig
> +                {% block service_name %}
I know this change removes some duplication but i'm not sure I like it in the default layout. Do we use the service_name block anywhere else?

2021-12-02 21:49 UTC, lukejolliffe commented on service-front/app/src/Actor/templates/actor/view-lpa-summary.html.twig
> +                                {% trans %}We cannot show whether or not this <abbr title="lasting power of attorney">LPA</abbr> has preferences or instructions. {% endtrans %} <a class="govuk-link"
This was temporary if this ticket went out before uchenna was back, I'll ask her for the correct translation now :)

2021-12-02 21:55 UTC, lukejolliffe commented on service-front/app/src/Common/templates/layout/default.html.twig
> +                {% block service_name %}
It's used in all the common pages + actor layout and view layout. I would argue this should replace the way it is statically set in both the view and actor layout templates

2021-12-02 22:01 UTC, lukejolliffe commented on service-front/app/src/Common/templates/layout/default.html.twig
> +                {% block service_name %}
There are pages like 404 errors that have the title missing that this will fix as well

2021-12-03 14:26 UTC, lukejolliffe commented on service-front/app/features/context/UI/ViewerContext.php
> +        $this->iHaveBeenGivenAccessToAnLPAViaShareCode();
This one is a little more difficult because the handler requires session values to be set, is there a way we can manipulates the session values in the test easily?

2021-12-06 09:41 UTC, cooperaj commented on service-front/app/features/context/UI/ViewerContext.php
> +        $this->iHaveBeenGivenAccessToAnLPAViaShareCode();
Ha, yes, I'd forgotten about session stuff. Session stuff is literally the only thing we can't short circuit right now. Ignore this :)

2021-12-06 09:45 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                                {% trans %}We cannot show whether or not this <abbr title="lasting power of attorney">LPA</abbr> has preferences or instructions. {% endtrans %} <a class="govuk-link"
This has the same split translation/Read More issue.

2021-12-08 18:27 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/view-lpa-summary.html.twig
> +                                {% trans %}We cannot show whether or not this <abbr title="lasting power of attorney">LPA</abbr> has preferences or instructions. {% endtrans %} <a class="govuk-link"
@cooperaj  - reply from Uchenna on this

<img width="636" alt="Screenshot 2021-12-08 at 18 27 13" src="https://user-images.githubusercontent.com/6483585/145263413-4c8c4ff9-db2e-4769-965e-7dc33b257721.png">

2021-12-08 21:08 UTC, SeemaMenon commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                                {% trans %}We cannot show whether or not this <abbr title="lasting power of attorney">LPA</abbr> has preferences or instructions. {% endtrans %} <a class="govuk-link"
Made to a single translatable statement now

2021-12-17 14:30 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/view-lpa-summary.html.twig
> +                                    We cannot show whether or not this <abbr title="lasting power of attorney">LPA</abbr> has preferences or instructions.<a class="govuk-link" href="%link%">Read more
```suggestion
                                    We cannot show whether or not this <abbr title="lasting power of attorney">LPA</abbr> has preferences or instructions. <a class="govuk-link" href="%link%">Read more</a>
```
Will need a space here

2021-12-17 14:32 UTC, cooperaj approved these changes
Going to approve this so it can get merged whilst I'm away but the space issues need sorting (and then presumably the translations too)

2021-12-17 14:32 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                                    We cannot show whether or not this <abbr title="lasting power of attorney">LPA</abbr> has preferences or instructions.<a class="govuk-link" href="%link%">Read more
```suggestion
                                    We cannot show whether or not this <abbr title="lasting power of attorney">LPA</abbr> has preferences or instructions. <a class="govuk-link" href="%link%">Read more</a>
```
Space here too

2021-12-17 15:13 UTC, merged

2021-12-17 15:24 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/view-lpa-summary.html.twig
> +                                    We cannot show whether or not this <abbr title="lasting power of attorney">LPA</abbr> has preferences or instructions.<a class="govuk-link" href="%link%">Read more
Missed this ...Sorry, doing this change in another PR.