UML-1930-track-all-form-errors
ministryofjustice/opg-use-an-lpa pull request #1273
Opened 2021-12-03 16:25 UTC by lukejolliffe

# Purpose

_Briefly describe the purpose of the change, and/or link to the JIRA ticket for context_

Fixes UML-####

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-12-07 16:49 UTC, johnnolan commented
@lukejolliffe When you are back can we grab some time to look at the existing code as well as https://opgtransform.atlassian.net/browse/UML-1955 and https://opgtransform.atlassian.net/browse/UML-1908 as well as the digideps code here https://github.com/ministryofjustice/opg-digideps/blob/main/client/assets/javascripts/modules/googleAnalyticsEvents.js

Think it would be worth stepping back and looking at how we structure the code now to allow easier implementation of all the tracking needed

2022-01-05 16:56 UTC, lukejolliffe commented
Formatting of all JS files will be handled in another PR

2022-01-17 08:45 UTC, SeemaMenon submitted a review, later dismissed

2022-01-25 10:02 UTC, cooperaj requested changes

2022-01-25 10:02 UTC, cooperaj commented on service-front/web/src/javascript/googleAnalytics.js
> -        const externalLinkSelector = document.querySelectorAll('a[href^="http"]');
See how the tracking is applied to individual links. Not the whole document.

2022-01-25 10:02 UTC, cooperaj commented on service-front/web/src/javascript/googleAnalytics.js
> -    _trackLpaDownload()
Can't see this has been replaced?

2022-01-25 10:04 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/govuk_error.html.twig
> +                                    <a data-attribute="ga-load-event" data-gaCategory="Form errors" data-gaAction="Form" data-gaLabel="{{ message | trans([], null, 'error') | raw }}" href="#">{{ mess
Wait, why are we translating the gaLabel?

2022-01-25 10:05 UTC, cooperaj commented on service-front/web/src/javascript/analyticsTracking.js
> +            /^(((\+44\s?\d{4}|\(?0\d{4}\)?)\s?\d{3}\s?\d{3})|((\+44\s?\d{3}|\(?0\d{3}\)?)\s?\d{3}\s?\d{4})|((\+44\s?\d{2}|\(?0\d{2}\)?)\s?\d{4}\s?\d{4}))(\s?\#(\d{4}|\d{3}))?$/g, // Telephone
* See below

2022-01-25 11:11 UTC, cooperaj commented
https://caniuse.com/mdn-api_mutationobserver

Does this work (shimmed or otherwise) on IE<11?

2022-01-25 11:14 UTC, cooperaj commented on service-front/web/src/javascript/analyticsTracking.js
> +        observer.observe(document.body, {
Is it not better to attach this just to the bit we're interested in? Rather than the whole page and then iterating the event for a target? I imagine this adds a fair bit of overhead if every element on a page is being monitored? Batteries on mobile devices might not like this approach

2022-01-25 11:22 UTC, lukejolliffe commented on service-front/app/src/Actor/src/Handler/ChangePasswordHandler.php
> -                        $form->addErrorMessage(PasswordChange::INVALID_PASSWORD, 'current_password');
linking to the field poses issues as to how we track form errors that don't have an error_message, doing it in this way so we don't change any field names in the analytics. _I could add this as a validator instead which it probably should be?_

2022-01-25 11:25 UTC, lukejolliffe commented on service-front/app/src/Common/templates/partials/govuk_error.html.twig
> +                                    <a data-attribute="ga-load-event" data-gaCategory="Form errors" data-gaAction="Form" data-gaLabel="{{ message | trans([], null, 'error') | raw }}" href="#">{{ mess
Too many copy pastes :D hence the ticket in the backlog to think how we could template these all instead

2022-01-25 11:26 UTC, lukejolliffe commented on service-front/app/src/Common/templates/partials/govuk_error.html.twig
> +                                    <a data-attribute="ga-load-event" data-gaCategory="Form errors" data-gaAction="Form" data-gaLabel="{{ message | trans([], null, 'error') | raw }}" href="#">{{ mess
honestly no clue probably wrote this last thing on a friday :D

2022-01-25 11:28 UTC, lukejolliffe commented on service-front/app/src/Common/templates/partials/govuk_error.html.twig
> +                                    <a data-attribute="ga-load-event" data-gaCategory="Form errors" data-gaAction="Form" data-gaLabel="{{ message | trans([], null, 'error') | raw }}" href="#">{{ mess
Don't think Jude would have appreciated this

2022-01-25 12:21 UTC, lukejolliffe commented on service-front/web/src/javascript/googleAnalytics.js
> -    _trackLpaDownload()
This is handled by the more generic click event instead, using the attributes given to the element in full-lpa-display.html.twig

2022-01-25 13:47 UTC, lukejolliffe commented on service-front/app/src/Actor/templates/actor/add-lpa-triage.html.twig
> +                    <details class="govuk-details" data-module="govuk-details" data-attribute="ga-event" data-gaAction="Details" data-gaCategory="ActivationKey" data-gaLabel="Where can I find my acti
Thinking of replacing with "data-gaEventType" then making "ga-event" and "ga-load-event", "onClick" and "onLoad" respectively

2022-01-26 10:02 UTC, lukejolliffe commented on service-front/web/src/javascript/analyticsTracking.js
> +        observer.observe(document.body, {
Actually due to the event bubbling that happens in Javascript this method is more likely to be more optimised than having lot's of listeners on individual objects. https://programmingwithmosh.com/javascript/javascript-event-bubbling-and-event-delegation/

2022-01-26 10:06 UTC, lukejolliffe commented on service-front/web/src/javascript/analyticsTracking.js
> +        document.addEventListener('click', (e) => {
The click event is still raised when `preventDefault` is raised, I think it is called by the polyfill details code if I remember correctly. `preventPropogation` is the method that would stop the event from bubbling up and triggering click events but I can't think of an instance that we would want to call that apart from to stop GA tracking

2022-01-26 10:07 UTC, lukejolliffe commented on service-front/web/src/javascript/analyticsTracking.js
> +            /^(((\+44\s?\d{4}|\(?0\d{4}\)?)\s?\d{3}\s?\d{3})|((\+44\s?\d{3}|\(?0\d{3}\)?)\s?\d{3}\s?\d{4})|((\+44\s?\d{2}|\(?0\d{2}\)?)\s?\d{4}\s?\d{4}))(\s?\#(\d{4}|\d{3}))?$/g, // Telephone
I'll make a ticket for this

2022-01-26 11:50 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/ChangePasswordHandler.php
> -                        $form->addErrorMessage(PasswordChange::INVALID_PASSWORD, 'current_password');
> form errors that don't have an error_message
Unless I'm misunderstanding something that's not the case here?

2022-01-26 11:50 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/add-lpa-triage.html.twig
> +                    <details class="govuk-details" data-module="govuk-details" data-attribute="ga-event" data-gaAction="Details" data-gaCategory="ActivationKey" data-gaLabel="Where can I find my acti
I like it.

2022-01-26 11:53 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/add-lpa-triage.html.twig
> +                    <details class="govuk-details" data-module="govuk-details" data-attribute="ga-event" data-gaAction="Details" data-gaCategory="ActivationKey" data-gaLabel="Where can I find my acti
Mmm, I think the data attributes allow the progressive enhancement approach in a nicer fashion. Using javascript functions sort of blurs the lines a bit - I don't know how I feel about that personally.

2022-01-26 11:59 UTC, cooperaj commented on service-front/web/src/javascript/analyticsTracking.js
> +        observer.observe(document.body, {
Oh I get that. But I think in this case the likely hood of having many things being tracked is low. Besides, this applies to events and I'm not sure how the MutationObserver stuff functions. What counts as a mutation that would trigger this code? Is every interaction on the page running the ObserveMutations function? It's not particularly lightweight.

2022-01-26 12:02 UTC, cooperaj commented on service-front/web/src/javascript/analyticsTracking.js
> +        document.addEventListener('click', (e) => {
I think in this case it would be better to attach the event directly to `[data-attribute="ga-event"]` as the code as it stands will run on every click interaction on the page when we're only interested in what, a few at most?

2022-01-26 15:06 UTC, lukejolliffe commented on service-front/app/src/Actor/src/Handler/ChangePasswordHandler.php
> -                        $form->addErrorMessage(PasswordChange::INVALID_PASSWORD, 'current_password');
We don't have a message or display on the actual 'current_password' field, it's only a line in the summary box

2022-01-27 10:05 UTC, lukejolliffe commented
> https://caniuse.com/mdn-api_mutationobserver
> 
> Does this work (shimmed or otherwise) on IE<11?

We don't need to support under IE 11 apparently?
[ ](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices)

2022-02-02 09:56 UTC, cooperaj approved these changes

2022-02-02 12:41 UTC, SeemaMenon approved these changes

2022-02-02 13:28 UTC, merged