UML-1910 banner update live phase
ministryofjustice/opg-use-an-lpa pull request #1320
Opened 2022-01-04 10:49 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1910

Fixes UML-1910

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [X] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2022-01-17 14:58 UTC, SeemaMenon commented
This PR adds feedback links to the bottom of all pages in view and use like below. Hence affected the large number of files.
<img width="678" alt="Screenshot 2022-01-17 at 12 40 50" src="https://user-images.githubusercontent.com/6483585/149792442-48d82ed4-8725-42ea-b9bd-56a21e3c75e2.png">
<img width="604" alt="Screenshot 2022-01-17 at 12 41 01" src="https://user-images.githubusercontent.com/6483585/149792444-0a31fd3c-71b6-4397-aa55-2f5813f59d55.png">

2022-01-19 10:25 UTC, lukejolliffe requested changes

2022-01-19 10:25 UTC, lukejolliffe commented on service-front/app/src/Viewer/templates/viewer/check-code-not-found.html.twig
> +{#                    </p>#}
redundant comment?

2022-01-19 11:51 UTC, SeemaMenon commented on service-front/app/src/Viewer/templates/viewer/check-code-not-found.html.twig
> +{#                    </p>#}
MY BAD .... Sorry @lukejolliffe . Removed now

2022-01-19 12:29 UTC, lukejolliffe approved these changes

2022-01-19 12:37 UTC, merged