UML-1305: Show trust corporation in attorney list in the summary pages
ministryofjustice/opg-use-an-lpa pull request #1416
Opened 2022-03-10 06:10 UTC by SeemaMenon

# Purpose
https://opgtransform.atlassian.net/browse/UML-1305

Fixes UML-1305

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2022-03-14 15:37 UTC, lukejolliffe commented on service-front/app/languages/cy/LC_MESSAGES/messages.html
> +<!DOCTYPE html>
Whats this file?

2022-03-14 15:55 UTC, lukejolliffe requested changes
I think there should also be a BDD test for the UI showing trust corporations? 

Maybe something along the lines of : 

**Given** I have an LPA added with a TrustCorporation as an attorney
**When** I request to view the LPA 
**Then** I can see the trust corporation in the list of attorneys 

?

2022-03-14 15:55 UTC, lukejolliffe commented on service-front/app/languages/cy/LC_MESSAGES/messages.html
> +<!DOCTYPE html>
Whats this file?

2022-03-14 15:55 UTC, lukejolliffe commented on service-front/app/src/Common/src/Service/Lpa/LpaService.php
> +    public function getAttorneyDetails(array $attorneys, array $trustCorporations): ?array
Is it a needed requirement to combine the two lists? I would have just read from them both separately in the twig file instead?

2022-03-14 17:50 UTC, SeemaMenon commented on service-front/app/languages/cy/LC_MESSAGES/messages.html
> +<!DOCTYPE html>
Deleted file.

2022-03-14 17:51 UTC, SeemaMenon commented on service-front/app/src/Common/src/Service/Lpa/LpaService.php
> +    public function getAttorneyDetails(array $attorneys, array $trustCorporations): ?array
Shouldn't have...but I could not get it read in twig with the correct ordinal sequence.  Let's discuss options tomorrow.

2022-03-16 16:17 UTC, SeemaMenon commented
> I think there should also be a BDD test for the UI showing trust corporations?
> 
> Maybe something along the lines of :
> 
> **Given** I have an LPA added with a TrustCorporation as an attorney **When** I request to view the LPA **Then** I can see the trust corporation in the list of attorneys
> 
> ?

@lukejolliffe  - Done

2022-03-17 09:40 UTC, andrewpearce-digital commented
@SeemaMenon There's a missing update for the mock integrations nginx.conf file to map the new mock data you've added. This results in the mock returning a 404 for 700000151451. You've likely got it locally, or you can recreate it with the generate_example.sh script.

2022-03-17 16:30 UTC, lukejolliffe submitted a review, later dismissed

2022-03-18 09:31 UTC, lukejolliffe requested changes
The messages.html is back 😅

2022-03-23 09:39 UTC, SeemaMenon commented
> The messages.html is back 😅

Removed now.

2022-03-23 09:56 UTC, lukejolliffe approved these changes

2022-03-23 10:16 UTC, merged