Uml 1115 admin app activation keys
ministryofjustice/opg-use-an-lpa pull request #1446
Opened 2022-03-31 13:35 UTC by lukejolliffe

# Purpose

_Briefly describe the purpose of the change, and/or link to the JIRA ticket for context_

Fixes UML-####

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2022-04-27 15:00 UTC, cooperaj requested changes

2022-04-27 15:00 UTC, cooperaj commented on service-api/docker/seeding/start.sh
> +    --attribute-definitions AttributeName=Id,AttributeType=S AttributeName=UserId,AttributeType=S AttributeName=ActivationCode,AttributeType=S \
If new indexes are needed then they will need adding to the terraform for the AWS environments too.

2022-04-27 15:10 UTC, lukejolliffe commented on service-admin/internal/server/handlers/handler.go
> +		err := fmt.Errorf("%w, template \"%s\" not in available templates", ErrTemplateNotFound, name)
It doesn't like it,  pretty sure it was complaining about this. 

linter err113: do not define dynamic errors, use wrapped static errors instead

2022-04-27 15:16 UTC, lukejolliffe commented on service-api/docker/seeding/start.sh
> +    --attribute-definitions AttributeName=Id,AttributeType=S AttributeName=UserId,AttributeType=S AttributeName=ActivationCode,AttributeType=S \
Already there just noticed I missed it from the seeding data

2022-05-03 19:04 UTC, lukejolliffe commented on service-admin/internal/server/handlers/handler.go
> +		err := fmt.Errorf("%w, template \"%s\" not in available templates", ErrTemplateNotFound, name)
^^ don't know why it was appearing, I've taken it back to original functionality and now the linter isn't complaining? So I won't either!

2022-05-04 10:29 UTC, cooperaj commented on service-admin/web/templates/result_code.partial.gohtml
> +        {{ if .Used }}
This same issue is repeated through out the file :P

2022-05-04 16:34 UTC, cooperaj approved these changes

2022-05-04 17:06 UTC, merged