split add lpa in to multiple pages
ministryofjustice/opg-use-an-lpa pull request #1479
Opened 2022-04-12 12:32 UTC by lukejolliffe

# Purpose

Splits the Add LPA Journey into one per page

Fixes UML-1814

## Approach

Split pages into separate files under LpaAdd folder. Create separate workflow state for this workflow.

ActivationCode and passcode have been renamed to activation key. This fixes UML-1535 (the name "passcode" was prompting password managers to attempt to fill this field) 

## Learning

## Checklist

* [x] I have performed a self-review of my own code
* [x] I have added tests to prove my work
* [x] I have added welsh translation tags and updated translation files
* [x] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2022-04-27 14:52 UTC, cooperaj requested changes
Few bits but otherwise solid.

2022-04-27 14:52 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/AddLpa/ActivationKeyHandler.php
> +    use CsrfGuard;
No need to 'use' these if they're 'use'd by the abstract class, it's just overriding methods with identical methods.

2022-04-27 14:52 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/AddLpa/ActivationKeyHandler.php
> +            $this->state($request)->activationCode = $postData['activation_key'];
You've refactored 'code' to key most places bu not here?

2022-04-27 14:52 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/CheckLpaHandler.php
> +    private \Actor\Workflow\AddLpa $state;
import this fqdn please - probably using an alias like `ActorAddLpa`

2022-04-27 14:52 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/CheckLpaHandler.php
> +        $this->state = (object) $this->loadState($request, \Actor\Workflow\AddLpa::class);
Would prefer to see the state loaded using a state() function as we see in the abstract.

2022-04-27 14:52 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/CheckLpaHandler.php
> +        return match ($request->getMethod()) {
I do like a match

2022-04-27 14:52 UTC, cooperaj commented on service-front/app/src/Actor/src/Workflow/AddLpa.php
> +     * This does not clear the name, date of birth or postcode as it is likely a repeat journey would use
Incorrect documentation

2022-04-27 14:52 UTC, cooperaj commented on service-front/app/src/Actor/src/Workflow/AddLpa.php
> +    public function jsonSerialize(): array
Mmm. Since this is now duplicated it could be worth moving into a trait with an associated interface

2022-04-29 14:25 UTC, cooperaj reviewed
Just these two missed and good to go.

2022-04-29 14:25 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/AddLpa/DateOfBirthHandler.php
> +    use CsrfGuard;
These traits are included in AbstractAddLpaHandler already

2022-04-29 14:29 UTC, cooperaj approved these changes

2022-04-29 14:30 UTC, lukejolliffe commented on service-front/app/src/Actor/src/Handler/AddLpa/LpaReferenceNumberHandler.php
> +    use CsrfGuard;
my bad -.-
![download](https://user-images.githubusercontent.com/84718230/165965254-05077462-9425-4396-bf63-cbc1887f8b49.jpeg)

2022-04-29 14:44 UTC, merged