UML-1866: cookies page updated and banner shown on setting cookie preferences
ministryofjustice/opg-use-an-lpa pull request #1486
Opened 2022-04-14 13:10 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1886

Fixes UML-1866

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [X] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2022-04-14 17:23 UTC, SeemaMenon commented
**Changes:**
1. Cookies page content updated.
2. On changing cookie preferences, now shows a success banner in the cookies page.
3. The link in the banner, takes user back to the page they were previously on.
[Above applicable for actor service and viewer service.]

<img width="859" alt="Screenshot 2022-04-14 at 18 13 09" src="https://user-images.githubusercontent.com/6483585/163440880-775253f9-88d6-4e0b-a574-a097b4132ff2.png">
<img width="931" alt="Screenshot 2022-04-14 at 18 13 25" src="https://user-images.githubusercontent.com/6483585/163440895-504a2055-df93-47f4-a56f-12106c13b6c3.png">
<img width="1041" alt="Screenshot 2022-04-14 at 18 17 34" src="https://user-images.githubusercontent.com/6483585/163440897-baf3f133-9774-4d94-85b4-fe76ba0d3c7a.png">

2022-04-25 14:06 UTC, lukejolliffe requested changes

2022-04-25 14:06 UTC, lukejolliffe commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +#| msgid ""
This comment can be removed

2022-04-25 14:06 UTC, lukejolliffe commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +#| msgid ""
I would just quickly double check the welsh is right here as well, sometimes this is poedit trying to be clever

2022-04-25 14:28 UTC, cooperaj requested changes

2022-04-25 17:37 UTC, SeemaMenon commented on service-front/app/features/context/UI/CommonContext.php
> +        //var_dump($serviceName); die;
My bad..... removed now.

2022-04-25 17:43 UTC, SeemaMenon commented on service-front/app/features/context/UI/CommonContext.php
> +            "You’ve set your cookie preferences. Go back to the page you were looking at."
Currently it takes the user back to the previous page automatically.


How this story says user to stay on the cookie page with a banner on changing cookie preferences.

`**Acceptance criteria**

- success banner in attachment shown when user marks their options and when they click the ‘save changes’ button on the page

- Banner appears on the same cookie page

- When user clicks on ‘[Go back to the page you were looking a](https://design-system.service.gov.uk/patterns/cookies-page/cookies-updated/index.html#)t’, they need to be taken to the previous page they were on`

2022-04-26 10:08 UTC, SeemaMenon commented on service-front/app/src/Common/src/Handler/CookiesPageHandler.php
> +            "%referer%",
True...nothing, so I removed this line and passing in the referer as a parameter to flash
` $flash->flash(self::COOKIES_SET_FLASH_MSG, $form->get('referer')->getValue());`

2022-05-03 09:02 UTC, SeemaMenon commented on service-front/app/src/Common/templates/partials/flash-message.html.twig
> +                {% trans %}You’ve set your cookie preferences.{% endtrans %}
That's right.... I wasn't sure how to get the url [to take user back to the previous page] in the flash message. 

This user story is likely to get revised [a new ticket in making by Sarah], and the flash message is likely to change to the previous page used was on....like current pattern.

Can this stay until we get to that ticket?

2022-05-03 09:04 UTC, SeemaMenon commented
> Mmm. Is it not possible to automatically redirect the user to their referring page and show the appropriate flash message there?
> 
> Though I think that may need a rework of the flash messages in general.

This user story is likely to get revised [a new ticket in making by Sarah], and the flash message is likely to change to the previous page used was on....like current pattern.

2022-05-03 10:49 UTC, cooperaj commented on .idea/runConfigurations/Front_UI.xml
> -<component name="ProjectRunConfigurationManager">
Wait, why is this deleted?

2022-05-03 11:19 UTC, cooperaj approved these changes

2022-05-03 12:31 UTC, lukejolliffe approved these changes

2022-05-03 14:31 UTC, merged