Uml 1583:  Admin portal logout
ministryofjustice/opg-use-an-lpa pull request #1497
Opened 2022-04-20 12:59 UTC by SeemaMenon

# Purpose

Fixes UML-1583

Introduced new handers to redirect users to cognito log out URL and then to the log out page.

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2022-04-20 13:36 UTC, andrewpearce-digital commented on terraform/environment/admin_ecs.tf
> +          value = "${aws_cognito_user_pool_client.use_a_lasting_power_of_attorney_admin.id}"
```suggestion
          value = "${aws_cognito_user_pool_client.use_a_lasting_power_of_attorney_admin.id[0]}"
```

2022-04-20 14:12 UTC, andrewpearce-digital commented on terraform/environment/admin_ecs.tf
> +          value = "${aws_cognito_user_pool_client.use_a_lasting_power_of_attorney_admin.id[0]}"
```suggestion
          value = "${aws_cognito_user_pool_client.use_a_lasting_power_of_attorney_admin[0].id}"
```

2022-05-25 09:26 UTC, cooperaj requested changes

2022-05-25 09:26 UTC, cooperaj commented on service-admin/internal/server/handlers/logout.go
> +		http.Redirect(w, r, cognitoLogoutURL.String(), 301)
Fix as suggested by the linter. :)

2022-05-25 09:32 UTC, andrewpearce-digital requested changes
one change needed in service-admin/internal/server/handlers/logout.go as advised by the linter

2022-05-25 14:39 UTC, andrewpearce-digital approved these changes

2022-06-01 15:34 UTC, merged