Uml 2264 request additional address
ministryofjustice/opg-use-an-lpa pull request #1580
Opened 2022-05-30 11:54 UTC by lukejolliffe

# Purpose

_Briefly describe the purpose of the change, and/or link to the JIRA ticket for context_

Fixes UML-####

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2022-05-31 14:05 UTC, johnnolan commented on terraform/environment/terraform.tfvars.json
> +        "allow_older_lpas": true,
Just idling through PRs and just double checking to see if this has been committed by accident

2022-06-01 09:35 UTC, lukejolliffe commented on terraform/environment/terraform.tfvars.json
> +        "allow_older_lpas": true,
Thanks john I should have switched this back after UAT but we've decided to keep it on for dev environments now anyway :) We've all had PRs needing this change so decided to turn it back on :D

2022-06-01 09:37 UTC, SeemaMenon approved these changes

2022-06-06 09:23 UTC, cooperaj requested changes

2022-06-06 09:24 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/request-activation-key/address-on-paper.html.twig
> +                        {{ govuk_form_element(form.get('address_on_paper_area'), {
See below :)

2022-06-06 11:13 UTC, cooperaj approved these changes

2022-06-06 12:23 UTC, merged