UML-2330 additional details on check answers page
ministryofjustice/opg-use-an-lpa pull request #1604
Opened 2022-06-09 13:17 UTC by lukejolliffe

# Purpose

Adds rows for check answers page for additional information gathered. Current address, address on paper LPA, attorney details. 

Fixes UML-2330

## Approach

Had to use a \<pre\> tag to format the address on paper correctly and preserve the whitespace entered by the user

## Checklist

* [x] I have performed a self-review of my own code
* [x] I have added tests to prove my work
* [x] I have added welsh translation tags and updated translation files
* [x] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [x] The product team have tested these changes

2022-06-10 15:13 UTC, cooperaj commented on service-front/app/features/context/UI/RequestActivationKeyContext.php
> +    private const TEST_PAPER_ADDRESS = "Unit 18 \n Peacock Avenue \n Boggy Bottom \n Hertfordshire \n DE65 AAA";
Unsure as to why this is our first const.

2022-06-10 15:13 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/request-activation-key/check-details-and-consent.html.twig
> +    <div class="govuk-width-container" xmlns="http://www.w3.org/1999/html">
Whats this?

2022-06-14 09:00 UTC, cooperaj requested changes
Queries to resolve.

2022-06-20 09:25 UTC, lukejolliffe commented on service-front/app/features/context/UI/RequestActivationKeyContext.php
> +    private const TEST_PAPER_ADDRESS = "Unit 18 \n Peacock Avenue \n Boggy Bottom \n Hertfordshire \n DE65 AAA";
Not really sure either, I think it's because most things are added to the LPA object.

2022-06-20 10:36 UTC, cooperaj commented on service-front/app/features/context/UI/RequestActivationKeyContext.php
> +    private const TEST_PAPER_ADDRESS = "Unit 18 \n Peacock Avenue \n Boggy Bottom \n Hertfordshire \n DE65 AAA";
if we're only using it in the one place then we likely don't need it. There are a large number of magic strings in this file that wouldn't likely be any easier to manage as consts? Am open to arguments on it though.

2022-06-20 12:22 UTC, lukejolliffe commented on service-front/app/features/context/UI/RequestActivationKeyContext.php
> +    private const TEST_PAPER_ADDRESS = "Unit 18 \n Peacock Avenue \n Boggy Bottom \n Hertfordshire \n DE65 AAA";
Nope I'll get rid actually. Just noticed a testing faux pas with it as well!

2022-06-20 16:15 UTC, cooperaj submitted a review, later dismissed

2022-06-22 13:25 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/govuk_form.html.twig
> +            element.getValue()
Brackets not needed?

2022-06-22 13:25 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/RequestActivationKey/AbstractCleansingDetailsHandler.php
> +        if ($state->actorAddressResponse === RequestActivationKey::ACTOR_ADDRESS_SELECTION_NO) {
Would like to see this methods checks in the order that we might encounter the fields in the workflow (just for future selves sake)

2022-06-22 14:24 UTC, lukejolliffe commented on service-front/app/src/Actor/src/Handler/RequestActivationKey/CheckDetailsAndConsentHandler.php
> +
I get what you mean now :D

2022-06-22 15:06 UTC, lukejolliffe commented on service-front/app/src/Common/templates/partials/govuk_form.html.twig
> +            element.getValue()
They are still there just on the lines before and after ^^

2022-06-22 15:53 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/govuk_form.html.twig
> +            element.getValue()
Ah. Ok. There are some whitespace handling functions of twig. You put hyphens in the opening/closing tags like `{{- thing -}}` and it collapses whitespace - including new lines.

2022-06-22 15:53 UTC, cooperaj approved these changes

2022-06-23 13:39 UTC, cooperaj approved these changes

2022-06-23 14:13 UTC, merged