UML-2142 : Allow matching on add LPA to look in trust corporation field
ministryofjustice/opg-use-an-lpa pull request #1619
Opened 2022-06-28 08:51 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-2142

Fixes UML-2142

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [X] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2022-06-29 15:02 UTC, SeemaMenon commented
<img width="843" alt="Screenshot 2022-06-28 at 11 32 15" src="https://user-images.githubusercontent.com/6483585/176469958-91744191-e0ac-48b1-baac-17387d41d891.png">
<img width="854" alt="Screenshot 2022-06-28 at 11 32 26" src="https://user-images.githubusercontent.com/6483585/176469964-50c4bd07-b585-4255-8461-42426a5b10d0.png">

2022-07-01 09:27 UTC, lukejolliffe requested changes

2022-07-01 09:27 UTC, lukejolliffe commented on service-api/app/src/App/src/Service/Lpa/ResolveActor.php
> +        // Determine if the actor is a trust corporation
There is a TODO in this docblock which can now be deleted :)

2022-07-01 10:18 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/ActorCodes/Validation/CodesApiValidationStrategy.php
> +                        'expected' => $actor['details']['dob'],
I had second thoughts on this too..... you spotted and I agree :)

2022-07-01 12:25 UTC, lukejolliffe approved these changes

2022-07-01 12:46 UTC, merged