Uml 2266 server coverage
ministryofjustice/opg-use-an-lpa pull request #1664
Opened 2022-07-07 12:53 UTC by lukejolliffe

# Purpose

_Briefly describe the purpose of the change, and/or link to the JIRA ticket for context_

Fixes UML-####

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2022-07-08 09:29 UTC, andrewpearce-digital submitted a review, later dismissed

2022-07-08 09:52 UTC, cooperaj requested changes
Will need a quick chat through this I think.

2022-07-08 09:52 UTC, cooperaj commented on service-admin/internal/server/server.go
> +func NewAuthorisationHandler(token *auth.Token) func(http.Handler) http.Handler {
These arn't handlers. They're middlewares.

2022-07-08 09:52 UTC, cooperaj commented on service-admin/internal/server/server.go
> +	return func(h http.Handler) http.Handler {
Not quite what what wrapping with an additional handerfunc has achieved?

2022-07-13 13:47 UTC, lukejolliffe commented on service-admin/internal/server/server_test.go
> +
t.Errorf("expected panic")

2022-07-15 15:56 UTC, merged