Uml-2267 signing test coverage
ministryofjustice/opg-use-an-lpa pull request #1685
Opened 2022-07-18 16:40 UTC by cooperaj

# Purpose

Improving golang test coverage

Fixes UML-2267

## Checklist

* [x] I have performed a self-review of my own code
* ~I have added relevant logging with appropriate levels to my code~
* ~New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)~
* ~I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant~
* [x] I have added tests to prove my work
* ~I have added welsh translation tags and updated translation files~
* ~I have run an accessibility tool on any pages I have made changes to and fixed any issues found~
* ~I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made~
* ~The product team have tested these changes~

2022-07-19 11:31 UTC, lukejolliffe requested changes

2022-07-19 11:31 UTC, lukejolliffe commented on service-admin/internal/server/auth/signing_test.go
> +	retryCount int
I think there is a variable missing or confused here. The retryCount here is being set to 2 because we have 2 expected retries. 

This is then given to the request func so that then starts with the count of 2, it will never hit the state of 0 and 1.

2022-07-19 11:31 UTC, lukejolliffe commented on service-admin/internal/server/auth/signing_test.go
> +						Body:       io.NopCloser(bytes.NewReader([]byte(goodKeyPem))),
This isn't a failed fetch, 404 is a vaild response so the code executes correctly and doesn't retry

2022-07-19 11:31 UTC, lukejolliffe commented on service-admin/internal/server/auth/signing.go
>  	if err := retry.Do(ctx, r, func(ctx context.Context) error {
When I was testing with two retries in the test the 3 second timeout was not enough? Should the code be refactored so this isn't constant and can be configured?

2022-07-19 12:18 UTC, cooperaj commented on service-admin/internal/server/auth/signing_test.go
> +	retryCount int
See line 25 ;)

2022-07-19 12:30 UTC, cooperaj commented on service-admin/internal/server/auth/signing_test.go
> +						Body:       io.NopCloser(bytes.NewReader([]byte(goodKeyPem))),
Due to the decrementing counter this is the final success condition i.e. it has already retried twice to get here.

2022-07-20 08:14 UTC, lukejolliffe commented on service-admin/internal/server/auth/signing_test.go
> +						Body:       io.NopCloser(bytes.NewReader([]byte(goodKeyPem))),
If it starts at 2 though it should go to the default case and pass the test without failing.

2022-07-20 08:44 UTC, merged