Fixes to twig template and css tweaks to improve accessibility.
ministryofjustice/opg-use-an-lpa pull request #1697
Opened 2022-07-25 10:35 UTC by cooperaj

# Purpose

Improve screenreader accessibility of the language switcher

Fixes UML-2314

## Checklist

* [x] I have performed a self-review of my own code
* I have added relevant logging with appropriate levels to my code
* New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* I have added tests to prove my work
* I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2022-07-25 15:36 UTC, lukejolliffe requested changes

2022-07-25 15:36 UTC, lukejolliffe commented on service-front/web/src/scss/_translation-switch.scss
> +      content: " | ";
I get this being read out in voiceover, Even though it's not perfect GDS have used a border for their vertical line 

https://www.access.service.gov.uk/login/signin/creds

2022-07-25 15:53 UTC, lukejolliffe requested changes

2022-07-25 15:53 UTC, lukejolliffe commented on service-front/app/src/Common/templates/partials/welsh-switch.html.twig
> +<div class="trans-switch" role="navigation" aria-labelledby="language-switch-en language-switch-cy">
Does this div give us anything? I think one of the main criticisms of the language toggle that the screen reader user had was that there were too many levels/ things that get read out that make the whole thing confusing? 

Maybe I got the wrong end of the stick, but I would thing that it would be better if it read just simply

Change Language 
    Current Language is English
    Newid iaith i'r Gymraeg

Currently it reads :

Current Language is English | Newid iaith i'r Gymraeg
   Current Language is English
    Newid iaith i'r Gymraeg

2022-07-27 09:02 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/welsh-switch.html.twig
> +<div class="trans-switch" role="navigation" aria-labelledby="language-switch-en language-switch-cy">
The issue is that we need to read out the language in the appropriate language. The only way to inform the browser of said language is using lang="" attributes and theres no way to attach those to an aria-label so my hope is that pulling that text from appropriate elements makes it work.

2022-07-27 09:05 UTC, cooperaj commented on service-front/web/src/scss/_translation-switch.scss
> +      content: " | ";
Yeah, but it also looks worse :p

2022-08-01 11:50 UTC, cooperaj commented on service-front/web/src/scss/_translation-switch.scss
> +      content: " | ";
Ok. So the pipe that's being read out isn't even the one thats added with the CSS. I've no idea where it's getting it as it's supposed to be the concatenation of the labels (aria-labelledby). Will continue to poke.

2022-08-01 12:05 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/welsh-switch.html.twig
> +<div class="trans-switch" role="navigation" aria-labelledby="language-switch-en language-switch-cy">
Div dropped and just use english for the label. I'm not sure we can do much else.

2022-08-05 09:32 UTC, lukejolliffe approved these changes

2022-08-05 09:37 UTC, lukejolliffe requested changes
Seems like axe dev now has an issue with it, hopefully its a simple fix 

EDIT: If you remove the role="navigation" from the ul then it fixes it :)

2022-08-09 13:55 UTC, lukejolliffe approved these changes

2022-08-09 14:55 UTC, merged