Uml 2334 : Make it clearer how to ask for a new activation key if given has expired
ministryofjustice/opg-use-an-lpa pull request #1704
Opened 2022-07-27 15:57 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-2334

Fixes UML-2334

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [X] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* ~I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant~
* [X] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [X] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2022-07-28 12:19 UTC, SeemaMenon commented
<img width="819" alt="Screenshot 2022-07-28 at 13 18 53" src="https://user-images.githubusercontent.com/6483585/181503368-a5d80e40-f66f-48e3-bf4c-800908ab3d43.png">

2022-07-29 09:30 UTC, SeemaMenon commented
<img width="835" alt="Screenshot 2022-07-29 at 10 29 31" src="https://user-images.githubusercontent.com/6483585/181729923-506a59eb-8813-414f-aaa3-28baa17ffd89.png">
<img width="769" alt="Screenshot 2022-07-29 at 10 29 58" src="https://user-images.githubusercontent.com/6483585/181729929-466f6f1b-0e9f-4111-9c8c-140f746de1a4.png">

2022-07-29 13:26 UTC, lukejolliffe commented on service-front/app/src/Actor/templates/actor/add-lpa-triage.html.twig
> +                <div class="govuk-grid-column-three-quarters">
Unsure why this needs to change to three-quarters. Preferably I would want to stick to the GDS suggested two thirds as much as possible

2022-07-29 13:32 UTC, lukejolliffe requested changes

2022-07-29 13:32 UTC, lukejolliffe commented on service-front/app/src/Actor/templates/actor/add-lpa-triage.html.twig
> +                <div class="govuk-grid-column-three-quarters">
Unsure why this needs to change to three-quarters. Preferably I would want to stick to the GDS suggested two thirds as much as possible

2022-07-29 16:43 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/add-lpa-triage.html.twig
> +                <div class="govuk-grid-column-three-quarters">
Reverted

2022-08-01 09:18 UTC, lukejolliffe approved these changes

2022-08-01 13:37 UTC, merged