update to phpunit 9.5
ministryofjustice/opg-use-an-lpa pull request #1881
Opened 2022-09-12 20:56 UTC by lukejolliffe

# Purpose

_Briefly describe the purpose of the change, and/or link to the JIRA ticket for context_

Fixes UML-####

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2022-09-14 10:14 UTC, lukejolliffe commented
![Screenshot 2022-09-14 at 11 12 51](https://user-images.githubusercontent.com/84718230/190127500-f4fd8c6e-220c-4f7d-9231-0307cad9832b.png)
![Screenshot 2022-09-14 at 11 13 00](https://user-images.githubusercontent.com/84718230/190127506-3babfb54-4a86-48cc-a9c3-6c5e05f4511b.png)

2022-09-14 12:53 UTC, cooperaj requested changes

2022-09-14 12:53 UTC, cooperaj commented on service-front/app/test/CommonTest/Form/AbstractFormTest.php
> +        $this->form = new class ('testConcreteForm', $guardProphecy->reveal()) extends AbstractForm {
```suggestion
        $this->form = new class('testConcreteForm', $guardProphecy->reveal()) extends AbstractForm {
```
Did your IDE suggest this?

2022-09-14 12:53 UTC, cooperaj commented on service-front/app/test/CommonTest/Middleware/Authentication/AuthenticationMiddlewareTest.php
> +use Prophecy\PhpUnit\ProphecyTrait;
Added trait but not used?

2022-09-14 12:53 UTC, cooperaj commented on service-front/app/test/CommonTest/Service/Features/FeatureEnabledTest.php
> +use Prophecy\PhpUnit\ProphecyTrait;
Not used

2022-09-14 12:53 UTC, cooperaj commented on service-front/app/test/CommonTest/Service/Url/UrlValidityCheckServiceTest.php
>      private $locale;
```suggestion
    private ServerRequestInterface|ObjectProphecy $serverRequestFactoryProphecy;
    protected RouterInterface|ObjectProphecy $routerProphecy;
    protected ServerRequestFactoryInterface|ObjectProphecy $serverRequestInterfaceProphecy;
    private UrlHelper|ObjectProphecy $urlHelperProphecy;
    private $locale;
```

It's ok to cuddle the properties

2022-09-14 12:54 UTC, lukejolliffe commented on service-front/app/test/CommonTest/Form/AbstractFormTest.php
> +        $this->form = new class ('testConcreteForm', $guardProphecy->reveal()) extends AbstractForm {
Psalm did I think

2022-09-14 12:54 UTC, lukejolliffe commented on service-front/app/test/CommonTest/Form/AbstractFormTest.php
> +        $this->form = new class ('testConcreteForm', $guardProphecy->reveal()) extends AbstractForm {
Will double check later

2022-09-14 12:55 UTC, cooperaj commented on service-front/app/test/CommonTest/Form/AbstractFormTest.php
> +        $this->form = new class ('testConcreteForm', $guardProphecy->reveal()) extends AbstractForm {
If it's been suggested by a linter then I guess it's what we should be doing.

2022-09-14 13:43 UTC, lukejolliffe commented on service-front/app/test/CommonTest/Form/AbstractFormTest.php
> +        $this->form = new class ('testConcreteForm', $guardProphecy->reveal()) extends AbstractForm {
![Screenshot 2022-09-14 at 14 40 33](https://user-images.githubusercontent.com/84718230/190170065-dc94f6cb-e766-4cef-a173-ab25e2a5c0d9.png)
It's in my IDE but also was raised by phpcs in the github action D:

2022-09-14 13:44 UTC, lukejolliffe commented on service-front/app/test/CommonTest/Middleware/Authentication/AuthenticationMiddlewareTest.php
> +use Prophecy\PhpUnit\ProphecyTrait;
I think I've put the trait into these and then removed it when I realised it wasn't used

2022-09-15 08:54 UTC, cooperaj commented on service-front/app/test/CommonTest/Form/AbstractFormTest.php
> +        $this->form = new class ('testConcreteForm', $guardProphecy->reveal()) extends AbstractForm {
spotted. it. it is a PSR12 thing. go figure.

2022-09-15 08:54 UTC, cooperaj approved these changes

2022-09-15 08:57 UTC, merged