Uml 2009 make delete clearer
ministryofjustice/opg-use-an-lpa pull request #1936
Opened 2022-09-29 16:00 UTC by lukejolliffe

# Purpose

_Briefly describe the purpose of the change, and/or link to the JIRA ticket for context_

Fixes UML-####

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2022-09-30 11:07 UTC, cooperaj commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +msgstr "A ydych yn siŵr eich bod am ddileu’r LPA hon?"
The translated string does not contain either of the two parameters?

2022-09-30 11:10 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/confirm-remove-lpa.html.twig
> +                    <p class="govuk-body"><strong>{% trans %}LPA type:{% endtrans %}</strong> {{ lpa_type_full_name(lpa.getCaseSubtype())|trans }}</p>
This trans call will not extract anything useful anywhere. It's likely the case that 'Health and welfare' and 'Property and finance' are already extracted but this is sill going to be a missing reference. 

I'd much rather see this done as a single statement too i.e. the lpa type being a parameter of the 'LPA type:' string.

2022-09-30 11:12 UTC, cooperaj commented on service-front/app/src/Common/src/View/Twig/LpaExtension.php
> +            return 'Health and welfare';
Potentially the best thing to do here would be to use a proper translation function call, like happens with some of the flash message contents in handlers. That way the extract path is more clear.

2022-09-30 11:14 UTC, cooperaj commented on service-front/app/src/Common/src/View/Twig/LpaExtension.php
> +        if ($expiryDate) {
Would prefer to see this as a more strongly typed check.

2022-09-30 11:15 UTC, cooperaj commented on service-front/app/src/Common/src/View/Twig/LpaExtension.php
> -    private function getDateFormatter(string $locale, ?string $pattern): IntlDateFormatter
Why the change in signature?

2022-09-30 11:16 UTC, cooperaj requested changes
few things to clear up.

2022-09-30 13:12 UTC, lukejolliffe commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +msgstr "A ydych yn siŵr eich bod am ddileu’r LPA hon?"
That's deliberate since the welsh isn't ready it's getting written into another ticket.

2022-09-30 13:13 UTC, lukejolliffe commented on service-front/app/src/Common/src/View/Twig/LpaExtension.php
> +        if ($expiryDate) {
```suggestion
        if ($expiryDate !== null) {
```

2022-09-30 13:15 UTC, lukejolliffe commented on service-front/app/src/Common/src/View/Twig/LpaExtension.php
> -    private function getDateFormatter(string $locale, ?string $pattern): IntlDateFormatter
It was never bering used with the pattern. We were just calling it with a static null

2022-10-07 09:34 UTC, lukejolliffe commented on service-front/app/src/Common/src/View/Twig/LpaExtension.php
> +        if ($expiryDate) {
@cooperaj I've turned this back to a loosy goosy check because our tests expect an empty string to result in null.

2022-10-18 09:14 UTC, SeemaMenon approved these changes

2022-10-19 09:01 UTC, cooperaj approved these changes
Suggestion to use null safe assignment rather than a ternary that returns null.

2022-10-19 09:05 UTC, merged