UML-2690: Adding code created by actor id to viewer code table to be used when lpa is removed from account
ministryofjustice/opg-use-an-lpa pull request #2164
Opened 2023-01-11 15:52 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-2690

Fixes UML-2690

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2023-02-09 10:08 UTC, cooperaj requested changes
Looks like a code cleanup tool or something was run but it's not used our linting rules so it's changed a bunch of stuff it shouldn't

2023-02-09 10:08 UTC, cooperaj commented on service-api/app/test/AppTest/DataAccess/DynamoDb/ViewerCodesTest.php
> +                                       ])
```suggestion
                $this->createAWSResult(
                    [
                        'Item' => [],
                    ]
                )
```
Something like this.

2023-02-13 17:50 UTC, SeemaMenon commented on service-api/app/src/App/src/Handler/LpasResourceHandler.php
> +        private RemoveLpa $removeLpa
I am not sure, looks like something has changes my settings. Corrected manually for now.

2023-02-13 17:52 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Lpa/RemoveLpa.php
> -                if (
Business requirement changed to now NOT cancel codes when a LPA is deleted from account. The generated access code should remain active [until it expires] for users to view and the same will be shown in active code section in 'Check Access Code' page.

2023-02-14 09:35 UTC, SeemaMenon commented on service-api/app/features/context/Acceptance/LpaContext.php
> +                        $this->marshalAwsResultData($code1)
No, I shouldn't have. Added back in .

2023-02-14 16:34 UTC, cooperaj approved these changes

2023-02-15 10:46 UTC, merged