UML-2779: Adding new event codes for type of LPA
ministryofjustice/opg-use-an-lpa pull request #2183
Opened 2023-02-13 12:05 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-2779

Fixes UML-2779

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2023-02-15 15:22 UTC, SeemaMenon commented
<img width="1342" alt="Screenshot 2023-02-15 at 14 42 24" src="https://user-images.githubusercontent.com/6483585/219070747-85177c6c-9142-43ac-ac8a-46d2a53b9dd7.png">
<img width="1341" alt="Screenshot 2023-02-15 at 15 19 09" src="https://user-images.githubusercontent.com/6483585/219070760-31b2a170-9c7e-4542-a933-0bcf548c5cca.png">

2023-02-17 09:59 UTC, cooperaj requested changes
Just weird extra spaces throughout. Otherwise looks great.

2023-02-17 09:59 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/CheckLpaHandler.php
> +        $activation_key     = $this->state($request)->activationKey;
Theres a lot of this extra spacing being added. I'm not sure what settings are doing this. The general rule for consecutive assignment blocks like this is that the spacing should be the same as the longest variable name. So what this code originally was.

2023-02-17 12:02 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/CheckLpaHandler.php
> +        $activation_key     = $this->state($request)->activationKey;
Something bad and mysterious on my machine ...my bad ! Corrected manually  @cooperaj

2023-02-23 17:29 UTC, cooperaj approved these changes

2023-02-24 09:52 UTC, merged