UML-2777-2785: Show date LPA was added by code/ activated when possible in Admin portal
ministryofjustice/opg-use-an-lpa pull request #2194
Opened 2023-02-23 13:24 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-2777
https://opgtransform.atlassian.net/browse/UML-2785

Fixes [UML-2777](https://opgtransform.atlassian.net/browse/UML-2777) and [UML-2785](https://opgtransform.atlassian.net/browse/UML-2785)

## Approach

1. Added field 'Updated' to UserLpaActorMap table
2. Updated seeding script
3. Update field gets populated when LPA is activated by code [Added field remains the same and gets populated when LPA added to account and key requested]
4. In Admin portal, when searching by LPA number - it now shows 'Activated on' date along with 'Added by', 'Added on' details
5. Test additions and fixes

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X ] I have performed a self-review of my own code
~* [ ] I have added relevant logging with appropriate levels to my code~
~* [ ] New event_codes have been documented on the [wiki page]~(https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
~* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant~
* [X] I have added tests to prove my work
~* [ ] I have added welsh translation tags and updated translation files~
~* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found~
~* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made~
* [ ] The product team have tested these changes

2023-02-23 14:29 UTC, SeemaMenon commented
<img width="697" alt="Screenshot 2023-02-23 at 14 29 00" src="https://user-images.githubusercontent.com/6483585/220936160-d8c96350-104d-421a-b992-b4b73299007d.png">
<img width="711" alt="Screenshot 2023-02-23 at 14 29 25" src="https://user-images.githubusercontent.com/6483585/220936167-52b72eae-2828-408f-ac9a-ac7d51540f96.png">

2023-02-28 17:00 UTC, cooperaj commented on service-api/app/src/App/src/DataAccess/DynamoDb/UserLpaActorMap.php
> +                'UpdateExpression'          => 'set ActorId = :a, ActivationCode = :b, Updated = :c remove ActivateBy, DueBy',
Should we add an Updated column whenever we update the record? (so the other methods in this class that write changes)

2023-02-28 17:00 UTC, cooperaj submitted a review, later dismissed

2023-03-01 11:24 UTC, SeemaMenon commented on service-api/app/src/App/src/DataAccess/DynamoDb/UserLpaActorMap.php
> +                'UpdateExpression'          => 'set ActorId = :a, ActivationCode = :b, Updated = :c remove ActivateBy, DueBy',
This function 'activateRecord()' gets called only in one instance ie when an added LPA is added using activation code/or when activated. Hence added in the new field to capture the activation time to meet the requirement below

'_show date LPA was added by code/ activated_'

**I think the field name is misleading and have now updated the field name from 'Updated' to 'ActivatedOn'**

Any old records where already added LPAs don't have the ActivatedOn field populated, will show the date the LPA was Added  as the ActivationDate. Again requirement as below: 

'_We need to display the newly added ‘Updated’ date in the UserLpaActorMap table when it is present for LPA queries._ '

2023-03-02 15:01 UTC, SeemaMenon commented
Added one more test for 'not activated scenario"

2023-03-07 13:48 UTC, SeemaMenon commented on service-admin/internal/server/handlers/search.go
> +
keep the names consistent and call ActivatedOn instead of DateActivated

2023-03-09 09:30 UTC, cooperaj requested changes
I think we need to go over your IDE settings. These files haven't been go-fmt'd and for some reason indentation is a mixture of tabs and spaces.

2023-03-09 09:30 UTC, cooperaj commented on service-admin/internal/server/handlers/search.go
> +	ActivatedOn string
```suggestion
	DateAdded   string
	Email       string
	ActivateBy  int
	ActivatedOn string
```

This should have been fixed by go-fmt. Which in most IDE's runs on document saving. Please check this is setup.

2023-03-10 15:20 UTC, cooperaj approved these changes

2023-03-12 23:44 UTC, merged