Uml 3013 kick off one login process
ministryofjustice/opg-use-an-lpa pull request #2369
Opened 2023-10-16 15:52 UTC by MishNajam

# Purpose

_Briefly describe the purpose of the change, and/or link to the JIRA ticket for context_

Fixes UML-3013

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2023-10-27 13:03 UTC, cooperaj requested changes

2023-10-27 13:03 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/AuthoriseOneLoginHandler.php
> +            $this->getLogger()->info('SUBMIT PRESSED');
debug line should be removed.

2023-10-27 13:03 UTC, cooperaj commented on service-front/docker/app/Dockerfile
Don't think these edits are needed?

(spacing good)

2023-10-30 10:22 UTC, MishNajam commented on service-api/app/src/App/src/Service/Authentication/OneLoginAuthorisationRequestService.php
I've added all these PR changes and have refactored classes and methods.

2023-10-30 13:47 UTC, cooperaj approved these changes

2023-10-30 13:57 UTC, merged