Uml 1533 hashing logged email
ministryofjustice/opg-use-an-lpa pull request #2460
Opened 2023-12-14 11:16 UTC by Lbagg1

# Purpose
Currently we hash email addresses that we are logging to protect PII from being leaked. 

There are 2 places where we have missed this:

UserService.php (front) line 135 

$this->logger->notice(
    'Authentication failed for {email} with code
        [
        'code'  => $e->getCode(),
        'email' => $email
    ]
);
 

UserService.php (api) line 200

$this->logger->notice(
    'Attempt made to reset password for non-existent account',
    ['email' => $email]
);
 

AC

The email is hashed in these places where we have missed it

Search code base for other missed examples and fix

Including MLPA - LPAL-1264: Hash PII when logging password reset requests
BACKLOG
 

Fixes UML-1533

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] New event_codes have been documented on the [wiki page](https://opgtransform.atlassian.net/wiki/spaces/LSML2/pages/3277881441/Understanding+the+event+logs)
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] I have notified the Interaction Designer of any content changes so that appropriate screenshots/flow diagram changes can be made
* [ ] The product team have tested these changes

2023-12-14 17:43 UTC, mattmachell commented on service-api/app/src/App/src/Service/User/UserService.php
> +                ['email' => new Email($email)]
Not a full namespace and not appearing added as an include?

2023-12-14 17:44 UTC, cooperaj requested changes
Looks good bar the .idea folder 👍

2023-12-14 17:44 UTC, cooperaj commented on service-api/.idea/.gitignore
Please remove the commited .idea folder here. There should only be one of these at the top level of the project.

2023-12-14 17:45 UTC, cooperaj commented on service-api/app/src/App/src/Service/User/UserService.php
> +                ['email' => new Email($email)]
Good catch.

2023-12-18 10:16 UTC, cooperaj submitted a review, later dismissed

2023-12-19 14:40 UTC, cooperaj approved these changes

2023-12-19 15:23 UTC, merged