Uml 3483 sign into service content
ministryofjustice/opg-use-an-lpa pull request #2714
Opened 2024-07-17 14:25 UTC by Lbagg1

# Purpose
On new login page advise customers that by logging in with this service they are accepting the terms of use. - link to https://use-lasting-power-of-attorney.service.gov.uk/terms-of-use 

CONTENT

As a result of looking at this ticket, some other changes to this page are to be made, as per screenshot attached:

The content that signposts the user to the Make an LPA service is to appear above the page header and as part of an information banner.

New content, for the terms of use, is to appear above the ‘Continue’ button, as part of an inset component. The content is:

Terms of use reference: ‘By continuing, you are agreeing to the terms of the Use a lasting power of attorney service.’ (the link here is to go to https://use-lasting-power-of-attorney.service.gov.uk/terms-of-use )

Welsh: 'Ewch i’r Gwasanaeth gwneud atwrneiaeth arhosol  i wneud LPA ar-lein, neu i barhau gyda chais am LPA rydych eisoes wedi’i gychwyn.’ (the underlined Welsh content is the link to the terms)

Acceptance criteria

new content as displayed on attachment

behind onelogin flag

Fixes UML-3483

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] The product team have tested these changes

2024-07-23 15:10 UTC, allenannom approved these changes

2024-07-23 15:12 UTC, cooperaj commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +"<a href=https://home.account.gov.uk/contact-gov-uk-one-login?lng=cy "
missing some quotes on the url here.

2024-07-23 15:16 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/one-login.html.twig
> +                            '%link_en%': 'https://use-lasting-power-of-attorney.service.gov.uk/terms-of-use',
For relative links it's possible to use our routing code to generate this for you. Bonus is that it handles the welsh version.

https://github.com/ministryofjustice/opg-use-an-lpa/blob/26b327b0961b711560368be4b8bb2a3d5817bc8b/service-front/app/src/Actor/templates/actor/create-account.html.twig#L58

2024-07-23 15:17 UTC, cooperaj requested changes
Couple of small tweaks needed.

2024-07-23 15:29 UTC, cooperaj commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +"<a href=“https://home.account.gov.uk/contact-gov-uk-one-login?lng=cy” "
These will need to be escaped ASCII quotes 

```suggestion
"<a href=\"https://home.account.gov.uk/contact-gov-uk-one-login?lng=cy\" "
```

PoEdit definitely not doing the right thing here and it's annoying. Typically it's a manual fix in PHPStorm after using PoEdit if any of the new Welsh has HTML in it, like a link.

2024-07-23 18:15 UTC, cooperaj commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +"class=“govuk-link”>www.gov.uk/gweld-atwrneiaeth-arhosol</a> i roi’r cod "
Seems there are a number of new changes in this file. It's necessary to be quite careful with how these quotes gets introduced as they can stop the translations working entirely.
```suggestion
"class=\"govuk-link\">www.gov.uk/gweld-atwrneiaeth-arhosol</a> i roi’r cod "
```

2024-07-23 18:15 UTC, cooperaj commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +"Trwy barhau, rydych yn cytuno i <a href=%link% class=\"govuk-link\"> delerau’r "
```suggestion
"Trwy barhau, rydych yn cytuno i <a href=\"%link%\" class=\"govuk-link\"> delerau’r "
```

2024-07-23 18:15 UTC, cooperaj commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +#~ msgid ""
Looks like a fair number of changes to the viewercode side of things. Probably nothing but could you please verify the pages that have (or did have) this content on are still functioning. That goes for all the viewercode items in this diff.

2024-07-23 18:15 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/one-login.html.twig
> +                            '%link%': path('terms-of-use')
Perfect.

2024-07-23 18:15 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/one-login.html.twig
> +                                    '%link%': 'https://www.gov.uk/power-of-attorney/make-lasting-power'
I wonder if there is an equivalent welsh version of this page?

2024-07-23 18:18 UTC, cooperaj commented
I've got a series of find-and-replace operations I typically carry out on the PO file when I'm done in Poedit. I'll get them documented (or make a script) so that the double quote thing can be easily watched in the future.

The issue is that you don't just want to replace all of them (or the single quote equivalents) as they might legitimately be being used in the text. It only bites us when they end up in the html (if a translation has any)

2024-07-24 07:08 UTC, Lbagg1 commented on service-front/app/src/Actor/templates/actor/one-login.html.twig
> +                                    '%link%': 'https://www.gov.uk/power-of-attorney/make-lasting-power'
there isn't an Welsh version , I have checked with Sarah.

2024-07-24 08:46 UTC, cooperaj approved these changes

2024-07-24 10:49 UTC, merged