Fix up static links for root pages
ministryofjustice/opg-use-an-lpa pull request #475
Opened 2020-08-04 13:54 UTC by cooperaj

## Purpose
Fixes up links across the site to the static privacy policy, cookies and terms of use pages. Sets them up to properly interpret the current language on the site and set links accordingly.

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [x] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-09-01 11:16 UTC, williamfalconeruk approved these changes

2020-09-07 08:55 UTC, nickdavis2001 approved these changes
lgtm

2020-09-07 08:55 UTC, williamfalconeruk commented on service-front/app/src/Viewer/templates/viewer/enter-code.html.twig
> +                        <p class="govuk-body">{% trans with {'{link}': path('terms-of-use')} %}By continuing you agree to our <a href="{link}" class="govuk-link">terms of use</a>.{% endtrans %}</p>
is this the right format for `trans with link`?

2020-09-07 08:57 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/enter-code.html.twig
> +                        <p class="govuk-body">{% trans with {'{link}': path('terms-of-use')} %}By continuing you agree to our <a href="{link}" class="govuk-link">terms of use</a>.{% endtrans %}</p>
it works but is not the way we've been doing it. good spot

2020-09-07 08:57 UTC, williamfalconeruk commented on service-front/app/src/Viewer/templates/viewer/enter-code.html.twig
> +                        <p class="govuk-body">{% trans with {'{link}': path('terms-of-use')} %}By continuing you agree to our <a href="{link}" class="govuk-link">terms of use</a>.{% endtrans %}</p>
i think just needs a minor tweak back to using the `%` as we use this elsewhere.

2020-09-07 08:58 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/enter-code.html.twig
> +                        <p class="govuk-body">{% trans with {'{link}': path('terms-of-use')} %}By continuing you agree to our <a href="{link}" class="govuk-link">terms of use</a>.{% endtrans %}</p>
```suggestion
                        <p class="govuk-body">{% trans with {'%link%': path('terms-of-use')} %}By continuing you agree to our <a href="%link%" class="govuk-link">terms of use</a>.{% endtrans %}</p>
```

2020-09-07 08:58 UTC, williamfalconeruk requested changes
one minor tweak, then GTG.

2020-09-07 08:59 UTC, williamfalconeruk approved these changes

2020-09-07 09:01 UTC, nickdavis2001 approved these changes

2020-09-07 09:10 UTC, SeemaMenon approved these changes

2020-09-07 09:56 UTC, merged