UML: 980 - Changes to take user back to home on second attempt of session expiry
ministryofjustice/opg-use-an-lpa pull request #501
Opened 2020-08-17 08:31 UTC by SeemaMenon

## Purpose
https://opgtransform.atlassian.net/browse/UML-980

Fixes UML-980

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Refunds service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [X] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-08-19 11:20 UTC, Raffers approved these changes

2020-08-19 13:05 UTC, cooperaj requested changes

2020-08-19 13:05 UTC, cooperaj commented on service-front/app/src/Common/src/Middleware/Session/SessionExpiredRedirectMiddleware.php
> +                $uri = new Uri($this->helper->generate('/home'));
Please can these urls be generated using the route name? That way the locale will work correctly

2020-08-25 10:46 UTC, SeemaMenon commented on service-front/app/src/Common/src/Middleware/Session/SessionExpiredRedirectMiddleware.php
> +                $uri = new Uri($this->helper->generate('/home'));
done

2020-08-25 11:02 UTC, cooperaj requested changes

2020-08-25 11:02 UTC, cooperaj commented on service-front/app/src/Common/src/Middleware/Session/SessionExpiredRedirectMiddleware.php
> +        if ($session !== null) {
Please combine this 'if' with the one below

2020-08-25 11:02 UTC, cooperaj commented on service-front/app/src/Common/src/Middleware/Session/SessionExpiredRedirectMiddleware.php
> +            $expiredDate = date("Y-m-d", $sessionExpiredDatetime);
```suggestion
            $expiredDate = new Datetime($session->get(EncryptedCookiePersistence::SESSION_TIME_KEY));
```

2020-08-25 11:02 UTC, cooperaj commented on service-front/app/src/Common/src/Middleware/Session/SessionExpiredRedirectMiddleware.php
> +        if ($session !== null) {
Something like
```suggestion
        if ($session !== null && $session->has(EncryptedCookiePersistence::SESSION_EXPIRED_KEY)
```

2020-08-25 17:02 UTC, SeemaMenon commented on service-front/app/src/Common/src/Middleware/Session/SessionExpiredRedirectMiddleware.php
> +            $currentDate = date("Y-m-d", $currentDatetime);
OK, done

2020-08-25 17:45 UTC, SeemaMenon commented on service-front/app/src/Common/src/Middleware/Session/SessionExpiredRedirectMiddleware.php
> +            $expiredDate = date("Y-m-d", $sessionExpiredDatetime);
Couldn't get this working working. Instead tried this
$sessionExpiredDatetime = $session->get(EncryptedCookiePersistence::SESSION_TIME_KEY);
$expiredDate = (new DateTime("@$sessionExpiredDatetime"))->format('Y-m-d');

2020-08-25 18:51 UTC, cooperaj commented on service-front/app/src/Common/src/Middleware/Session/SessionExpiredRedirectMiddleware.php
> +            $expiredDate = date("Y-m-d", $sessionExpiredDatetime);
Mmm. It should have worked. I wonder what the formate of the session value is. Either way I'm not sure what `"@$sessionExpiredDatetime"` will do. I'm not sure that will work.

2020-08-26 08:47 UTC, SeemaMenon commented on service-front/app/src/Common/src/Middleware/Session/SessionExpiredRedirectMiddleware.php
> +            $expiredDate = date("Y-m-d", $sessionExpiredDatetime);
This works on my testing. I followed this example below:
<img width="707" alt="Screenshot 2020-08-26 at 09 47 03" src="https://user-images.githubusercontent.com/6483585/91282398-32f5fa00-e781-11ea-8859-55ad17070947.png">

2020-08-26 11:12 UTC, cooperaj approved these changes
👍 Great

2020-08-26 11:30 UTC, Raffers approved these changes

2020-08-26 11:52 UTC, merged