Seeding added lpas
ministryofjustice/opg-use-an-lpa pull request #512
Opened 2020-08-20 15:30 UTC by GemTay

# Purpose

Seeds 2 lpa's into the test user's account to save dev's and PM's from having to generate a letter in sirius to add an LPA for UAT.

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-08-20 15:38 UTC, andrewpearce-digital commented on .circleci/config.yml
> +                export DYNAMODB_TABLE_USER_LPA_ACTOR_MAP=$(cat /tmp/cluster_config.json | jq .user_lpa_actor_map | xargs)
I can't see that table being created in the cluster_config file.
You'll need to add it in the terraform here `terraform/environment/config_file.tf`

2020-08-20 15:39 UTC, andrewpearce-digital requested changes
The addition to the pipeline you've made relies on that table name being added to the config file in terraform.

2020-08-20 16:00 UTC, andrewpearce-digital approved these changes

2020-08-20 16:10 UTC, williamfalconeruk commented
think there are some issues with seeding on the build.

2020-08-26 08:52 UTC, SeemaMenon approved these changes

2020-08-26 13:55 UTC, merged