Uml 1037 : wrapped with translation tag
ministryofjustice/opg-use-an-lpa pull request #514
Opened 2020-08-21 08:05 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1037

Fixes UML-1037

## Approach

Wrapped the textswith translation tag

## Learning
 
_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-08-24 15:06 UTC, cooperaj commented
MO PO and POT files are not needed as a part of this PR. They will be created/updated when the extraction is run

2020-08-24 15:39 UTC, cooperaj requested changes
Please don't split up translation strings. As a rule `{%trans%}html is <ok> probably{%endtrans%}` and not `{%trans%}html is{%endtrans%} <ok> {%trans%}probably{%endtrans%}`. Certainly not `{%trans%}html is <a href=''>probably{%endtrans%}</a>`

2020-08-24 15:39 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/check-code-found.html.twig
> +                            <td class="govuk-table__cell">{% trans %}in{% endtrans %} {{ days_remaining_to_expiry(expires) | trans | raw }} {% trans %}days{% endtrans %}, {% trans %}on{% endtrans %}
```suggestion
                            <td class="govuk-table__cell">{% trans count days_remaining_to_expiry(expires) with {'% date %': lpa_date(expires)} %}in %count% day, on %date%|in %count% days, on %date%{% endtrans %}</td>
```

I think this should do it.

2020-08-24 15:39 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/check-code-found.html.twig
> +                            <td class="govuk-table__cell">{% trans %}in{% endtrans %} {{ days_remaining_to_expiry(expires) | trans | raw }} {% trans %}days{% endtrans %}, {% trans %}on{% endtrans %}
Though this might all still be work in progress thing. Plurals are hard. As are dates.

2020-08-24 15:39 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/check-code-found.html.twig
> +                                {% trans %}If you need to see this {% endtrans %}<abbr title='lasting power of attorney'>{% trans %} LPA {% endtrans %}</abbr> {% trans %}after{% endtrans %} {{ lpa_da
Please don't split all this up. As with the viewer enter-code template this should all be done with placeholders. The Abbr should be a part of the translation.

```suggestion
                                {% trans with {'%date%': lpa_date(expires)} %}If you need to see this <abbr title="lasting power of attorney">LPA</abbr> after %date%{% endtrans %}
```

2020-08-25 13:05 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                                {% trans %}Yes, the donor made preferences on their LPA{% endtrans %}.<br>{% trans %}To view these, ask to see the paper LPA{% endtrans %}
```suggestion
                                {% trans %}Yes, the donor made preferences on their LPA.<br>To view these, ask to see the paper LPA{% endtrans %}
```

2020-08-25 13:05 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                                {% trans %}Yes, the donor set instructions on their LPA{% endtrans %}.<br>{% trans %}To view these, ask to see the paper LPA{% endtrans %}
```suggestion
                                {% trans %}Yes, the donor set instructions on their LPA.<br>To view these, ask to see the paper LPA{% endtrans %}
```

2020-08-25 13:05 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                        <dd class="govuk-summary-list__value">{% trans with {'%date%': lpa_date(lpa.lpaDonorSignatureDate)} %}%date%{% endtrans %}</dd>
Output data

2020-08-25 13:05 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                        <dd class="govuk-summary-list__value">{% trans with {'%date%': lpa_date(lpa.registrationDate)} %}%date%{% endtrans %}</dd>
Data

2020-08-25 13:05 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                {% trans %}<a class="govuk-link" href="/home">I want to check another LPA{% endtrans %}</a>
```suggestion
                <a class="govuk-link" href="{{ path('home') }}">{% trans %}I want to check another LPA{% endtrans %}</a>
```

2020-08-25 13:05 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig
>  {% block html_title %}Terms of use - {{ parent() }} {% endblock %}
Missed title

2020-08-25 13:05 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig
> +                    <p class="govuk-body">{% trans %}The Use a lasting power of attorney (LPA) service lets donors and attorneys share a summary of an <abbr title="lasting power of attorney">LPA</abb
This is a single paragraph so should be a single translation statement?

2020-08-25 13:05 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig
> +                            <span class="govuk-warning-text__assistive">Warning</span>
Missed 'Warning'

2020-08-25 13:05 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig
> +                    <p class="govuk-body">{% trans %}The information will be stored securely and used in line with our <a class="govuk-link" href="/privacy-notice">privacy notice</a> and <a class="go
Please replace href with %link% and appropriate urlhelper usage.

2020-08-25 13:32 UTC, SeemaMenon commented on service-front/app/languages/cy.po
> +"defnyddio</a>"
ok

2020-08-25 13:36 UTC, SeemaMenon commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                            This {% if lpa.caseSubtype|lower == "pfa" %}{% trans %}property and finance{% endtrans %}{% else %}{% trans %}health and welfare{% endtrans %}{% endif %} {% trans %}LPA ha
good catch here...done.

2020-08-25 14:09 UTC, SeemaMenon commented on service-front/app/src/Viewer/templates/viewer/check-code-found.html.twig
> +                            <td class="govuk-table__cell">{{ lpa.donor.firstname | trans | raw}} {{ lpa.donor.surname | trans | raw }}</td>
That's a mistake, reverted.

2020-08-25 14:18 UTC, SeemaMenon commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                    <h3 class="govuk-heading-m">{{ lpa.attorneys | length == 1 ? '1st' : loop.index | ordinal }} {% trans %}attorney{% endtrans %}</h3>
That is right. Didn't know how to handle this now.

2020-08-25 14:26 UTC, SeemaMenon commented on service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig
> +                    <p class="govuk-body">{% trans %}The Use a lasting power of attorney (LPA) service lets donors and attorneys share a summary of an <abbr title="lasting power of attorney">LPA</abb
Converted to a single translation now. 
[Thought Lewis mentioned single sentence would be better.]

2020-08-25 15:05 UTC, SeemaMenon commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                {% trans %}<a class="govuk-link" href="/home">I want to check another LPA{% endtrans %}</a>
Done

2020-08-25 15:05 UTC, SeemaMenon commented on service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig
>  {% block html_title %}Terms of use - {{ parent() }} {% endblock %}
added in

2020-08-25 15:06 UTC, SeemaMenon commented on service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig
> +                    <p class="govuk-body">{% trans %}The Use a lasting power of attorney (LPA) service lets donors and attorneys share a summary of an <abbr title="lasting power of attorney">LPA</abb
Converted to single translation

2020-08-25 15:06 UTC, SeemaMenon commented on service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig
> +                            <span class="govuk-warning-text__assistive">Warning</span>
Done

2020-08-25 15:06 UTC, SeemaMenon commented on service-front/app/src/Viewer/templates/viewer/viewer-terms-of-use.html.twig
> +                    <p class="govuk-body">{% trans %}The information will be stored securely and used in line with our <a class="govuk-link" href="/privacy-notice">privacy notice</a> and <a class="go
Done

2020-08-25 18:55 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                                {% trans with {'%date%': lpa_date("today")} %}This LPA summary was correct on '%date%'{% endtrans %}
We've gained some quotes around %date%?

2020-08-25 18:59 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                            <dt class="govuk-summary-list__key">{% trans %}Life-sustaining{% endtrans %} <br>{% trans %}treatment{% endtrans %}</dt>
```suggestion
                            <dt class="govuk-summary-list__key">{% trans %}Life-sustaining<br>treatment{% endtrans %}</dt>
```

2020-08-25 18:59 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/check-code-found.html.twig
> +                            <td class="govuk-table__cell">{{ lpa.caseSubtype == 'pfa' ? 'Property and finance': 'Health and welfare' }}</td>
```suggestion
                            <td class="govuk-table__cell">{{ lpa.caseSubtype == 'pfa' ? 'Property and finance' | trans : 'Health and welfare' | trans }}</td>
```

2020-08-26 09:44 UTC, SeemaMenon commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                                {% trans with {'%date%': lpa_date("today")} %}This LPA summary was correct on '%date%'{% endtrans %}
Removed :(

2020-08-26 10:00 UTC, SeemaMenon commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                            <dt class="govuk-summary-list__key">{% trans %}Life-sustaining{% endtrans %} <br>{% trans %}treatment{% endtrans %}</dt>
done :(

2020-08-26 10:36 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                    <h3 class="govuk-heading-m">{{ lpa.attorneys | length == 1 ? '1st' : loop.index | ordinal }} {% trans %}attorney{% endtrans %}</h3>
```suggestion
                    <h3 class="govuk-heading-m">{% set attorneyOrdinal = lpa.attorneys | length == 1 ? '1st' : loop.index | ordinal %}{% trans count lpa.attorneys | length with {'%attorneyOrdinal%': attorneyOrdinal} %}%attorneyOrdinal% attorney|%attorneyOrdinal% attorney{% endtrans %}</h3>
```

I think this is what we need. Give it a go and if it fails give us a ring and then we can work through it.

2020-08-26 11:26 UTC, SeemaMenon commented on service-front/app/src/Common/templates/partials/full-lpa-display.html.twig
> +                    <h3 class="govuk-heading-m">{{ lpa.attorneys | length == 1 ? '1st' : loop.index | ordinal }} {% trans %}attorney{% endtrans %}</h3>
This didn't break...adding it in. :) Thanks Adam

2020-08-27 12:52 UTC, cooperaj approved these changes

2020-08-27 13:12 UTC, Raffers approved these changes

2020-08-28 08:46 UTC, Raffers approved these changes

2020-08-28 08:47 UTC, cooperaj approved these changes

2020-08-28 09:56 UTC, merged