Uml 1039 list3
ministryofjustice/opg-use-an-lpa pull request #516
Opened 2020-08-24 13:14 UTC by kate-49

# Purpose

https://opgtransform.atlassian.net/browse/UML-1039?atlOrigin=eyJpIjoiZDdhNGYxNmU2YmM5NDg4Zjg3ZmJlZmVhY2YzODc1YzYiLCJwIjoiaiJ9

Fixes UML-1039

## Approach
Adds translation tags to following pages:

- home-page.html.twig
- login.html.twig
- create-account.html.twig
- create-account-success.html.twig

I've based my wrapping on ticket 1037 as I was unsure about some of the abbr and hyperlinks. 
I've checked and all the hyperlinks work and navigate to the welsh version of the site. 
The header doesn't translate, including the beta service banner. I think this is because they are pulled from partials. 

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-08-24 14:30 UTC, cooperaj requested changes

2020-08-24 14:30 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/create-account-success.html.twig
> +                <p class="govuk-body">{% trans %}We've emailed a link to{% endtrans %} {{ emailAddress }}. {% trans %}Click on the link to activate your account. The link will work for the next 24 ho
This isn't quite how we need to do it and may give us issues down the line. The proper way as from line 41 of the viewer code entry page:

`<p class="govuk-body">{% trans with {'%link%': path('viewer-terms-of-use')} %}By continuing you agree to our <a href="%link%" class="govuk-link">terms of use</a>.{% endtrans %}</p>`

Notice that the link "text" is replaced with a placeholder which we map in the `with {}` block
Something like 

```suggestion
                <p class="govuk-body">{% trans with {'%email%': emailAddress} %}We've emailed a link to %email%. Click on the link to activate your account. The link will work for the next 24 hours.{% endtrans %}</p>
```

2020-08-24 14:30 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/create-account-success.html.twig
> +                <p class="govuk-body">{% trans %}The email should arrive in a few minutes. If it's not in your inbox, check your spam or junk folder. If you have not received the email, we can{% endt
Same here

```suggestion
                <p class="govuk-body">{% trans with {'%link%': path('create-account-success', {}, {'email': emailAddress, 'resend': 'true'})} %}The email should arrive in a few minutes. If it's not in your inbox, check your spam or junk folder. If you have not received the email, we can <a href="%link%" class="govuk-link">resend the activation email{% endtrans %}</a>.</p>
```

2020-08-24 14:30 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/login.html.twig
> +{% block html_title %}{% trans %} Sign in to your Use a lasting power of attorney account -{% endtrans %} {{ parent() }} {% endblock %}
You've mistakenly captured the hyphen '-'
```suggestion
{% block html_title %}{% trans %} Sign in to your Use a lasting power of attorney account{% endtrans %} - {{ parent() }} {% endblock %}
```

2020-08-24 14:30 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/login.html.twig
> +                        <p class="govuk-body">{% trans %}If you made an {% endtrans %}<abbr title="lasting power of attorney"> {% trans %} LPA </abbr> online, you'll still need to {% endtrans %} <a h
Aside from the link we'll need to include the abbr tags too.

```suggestion
                        <p class="govuk-body">{% trans with {'%ilnk%': path('create-account')} %}If you made an <abbr title="lasting power of attorney">LPA</abbr> online, you'll still need to <a href="'%link%" class="govuk-link">create an account</a> to use this service.{% endtrans %}</p>
```

2020-08-24 14:30 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/login.html.twig
> +                        <p class="govuk-body">{% trans %}If you made an {% endtrans %}<abbr title="lasting power of attorney"> {% trans %} LPA </abbr> online, you'll still need to {% endtrans %} <a h
As a general rule don't interleave `trans` tags and html this is good: `<title>{%trans%}Title</title>{%endtrans%}` this not so much: `<title>{%trans%}Title</title>{%endtrans%}`

2020-08-24 14:56 UTC, cooperaj commented
I think there are a couple of other places with the placeholder link issue in the PR. Should be easy to spot now.

2020-08-24 16:00 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/create-account-success.html.twig
> +                <p class="govuk-body">{% trans %}If you still do not receive the email, please contact us on 0300 456 0300.{% endtrans %}</p>
I would recommend passing this phone number in as a 'with' variable. This means the translation can be made to make contextual sense but that also we'll be able to change it in the future without invalidation of the translation files.

2020-08-24 16:29 UTC, kate-49 commented on service-front/app/src/Actor/templates/actor/create-account.html.twig
>                                  {{ govuk_form_element(form.get('terms'), { 'label': 'I agree to the <a href="/terms-of-use" class="govuk-link">terms of use</a>' }) }}
It already seems to translate 
<img width="422" alt="Screenshot 2020-08-24 at 17 28 57" src="https://user-images.githubusercontent.com/52196833/91070895-590b8500-e62f-11ea-94ee-b8e789495761.png">

2020-08-24 16:31 UTC, kate-49 commented on service-front/app/src/Actor/templates/actor/login.html.twig
> +                        <p class="govuk-body">{% trans %}If you made an {% endtrans %}<abbr title="lasting power of attorney"> {% trans %} LPA </abbr> online, you'll still need to {% endtrans %} <a h
These both look exactly the same to me @cooperaj ?

2020-08-24 16:37 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/login.html.twig
> +                        <p class="govuk-body">{% trans %}If you made an {% endtrans %}<abbr title="lasting power of attorney"> {% trans %} LPA </abbr> online, you'll still need to {% endtrans %} <a h
Oh. My bad. example is wrong. `{%trans%}<title>Title</title>{%endtrans%}`

2020-08-24 16:38 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/create-account.html.twig
>                                  {{ govuk_form_element(form.get('terms'), { 'label': 'I agree to the <a href="/terms-of-use" class="govuk-link">terms of use</a>' }) }}
Yes it will, but that capability is being removed in the near futures as it doesn't work with string extraction.

2020-08-24 16:40 UTC, kate-49 commented on service-front/app/src/Actor/templates/actor/login.html.twig
>                          {{ govuk_form_element(form.get('email'), { 'label': 'Email address', 'attr': { 'class': 'govuk-!-width-three-quarters' } }) }}
The labels seem to be translated
<img width="460" alt="Screenshot 2020-08-24 at 17 39 13" src="https://user-images.githubusercontent.com/52196833/91072001-c5d34f00-e630-11ea-8053-32b8ceb00510.png">

2020-08-24 17:46 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/login.html.twig
>                          {{ govuk_form_element(form.get('email'), { 'label': 'Email address', 'attr': { 'class': 'govuk-!-width-three-quarters' } }) }}
Yeah, that's because the translation for those currently happens in the forms extension and that's being reverted. Adding it as a filter will mean it happens in the template where we can extract it.

2020-08-25 12:52 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/create-account-success.html.twig
> +                <p class="govuk-body">{% trans with {'%link%': path('create-account-success', {}, {'email': emailAddress, 'resend': 'true'})} %}The email should arrive in a few minutes. If it's not i
```suggestion
                <p class="govuk-body">{% trans with {'%link%': path('create-account-success', {}, {'email': emailAddress, 'resend': 'true'})} %}The email should arrive in a few minutes. If it's not in your inbox, check your spam or junk folder. If you have not received the email, we can <a href="%link%" class="govuk-link">resend the activation email</a>.{% endtrans %}</p>
```

2020-08-25 12:52 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/create-account-success.html.twig
> +                <p class="govuk-body">{% trans with {'%link%': path('login') } %}If you've already activated your account, you can <a href=%link% class="govuk-link">sign in</a> now.{% endtrans %}</p>
```suggestion
                <p class="govuk-body">{% trans with {'%link%': path('login') } %}If you've already activated your account, you can <a href="%link%" class="govuk-link">sign in</a> now.{% endtrans %}</p>
```

2020-08-25 12:52 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/create-account.html.twig
> +                        <p class="govuk-body-l">{% trans with {'%link%': path('login')} %}If you already have an account, please <a href=%link% class="govuk-link">sign in</a>.{% endtrans %}</p>
```suggestion
                        <p class="govuk-body-l">{% trans with {'%link%': path('login')} %}If you already have an account, please <a href="%link%" class="govuk-link">sign in</a>.{% endtrans %}</p>
```

2020-08-25 12:52 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/create-account.html.twig
> +                                {{ govuk_form_element(form.get('terms'), { 'label': 'I agree to the <a href="/terms-of-use" class="govuk-link">terms of use</a>'| trans }) }}
This will need revisting as the /term-of-use link will lose the localisation (i.e. take you back to english). Itll need replacing with a placholder `%link%` and the value added to the trans filter (let me get back to you on the details for how that looks.

2020-08-25 12:52 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/create-account.html.twig
> +                                {{ govuk_form_element(form.get('password'), { 'label': 'Create a password', 'hint': 'Your password needs to have: <ul class="govuk-list--bullet"><li>at least 8 charact
```suggestion
                                {{ govuk_form_element(form.get('password'), { 'label': 'Create a password' | trans, 'hint': 'Your password needs to have: <ul class="govuk-list--bullet"><li>at least 8 characters</li><li>at least one lower-case and one capital letter</li><li>at least one number</li></ul>'| trans }) }}
```

2020-08-25 12:53 UTC, kate-49 commented on service-front/app/src/Actor/templates/actor/create-account-success.html.twig
> +                <p class="govuk-body">{% trans with {'%link%': path('login') } %}If you've already activated your account, you can <a href=%link% class="govuk-link">sign in</a> now.{% endtrans %}</p>
@cooperaj I didn't include the "" around the link because it changes the path to cy/"cy/whatever the path is"

2020-08-25 14:16 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/create-account.html.twig
> +                        <p class="govuk-body-l">{% trans with {'%link%': path('login')} %}If you already have an account, please <a href='%link%' class="govuk-link">sign in</a>.{% endtrans %}</p>
```suggestion
                        <p class="govuk-body-l">{% trans with {'%link%': path('login')} %}If you already have an account, please <a href="%link%" class="govuk-link">sign in</a>.{% endtrans %}</p>
```

2020-08-25 14:16 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/login.html.twig
> +                        <p class="govuk-body">{% trans with {'%link%': path('create-account')} %}If you made an <abbr title="lasting power of attorney"> LPA </abbr> online, you'll still need to <a hr
```suggestion
                        <p class="govuk-body">{% trans with {'%link%': path('create-account')} %}If you made an <abbr title="lasting power of attorney"> LPA </abbr> online, you'll still need to <a href="%link%" class="govuk-link">create an account</a> to use this service.{% endtrans %}</p>
```

2020-08-25 18:54 UTC, cooperaj commented
Looking really good now. Just need to drop out the POT file change and we'll need to work out the correct way to do that last open comment.

2020-08-26 09:33 UTC, cooperaj commented on service-front/app/languages/cy.po
> +
They're back ;)

2020-08-26 10:26 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/create-account.html.twig
> +                                {{ govuk_form_element(form.get('terms'), { 'label': 'I agree to the <a href="/terms-of-use" class="govuk-link">terms of use</a>'| trans }) }}
Have done a bit of research. I think it'll look like this

```suggestion
                                {{ govuk_form_element(form.get('terms'), { 'label': 'I agree to the <a href="%link%" class="govuk-link">terms of use</a>' | trans({ '%link%': path('actor-terms-of-use') }) }) }}
```

2020-08-27 08:56 UTC, SeemaMenon commented on service-front/app/languages/cy.po
> +#~ msgstr " ACLL "
Revert the po to what's in master

2020-08-27 09:20 UTC, SeemaMenon approved these changes

2020-08-27 10:13 UTC, cooperaj requested changes
Need to revert out the stray MO file too. As a rule, no PO, MO or POT file should be in these template PRs

2020-08-27 12:10 UTC, SeemaMenon approved these changes

2020-08-27 12:49 UTC, cooperaj approved these changes

2020-08-28 11:46 UTC, merged