UML-984 - I need access to session endpoints that allow me monitor my sessions
ministryofjustice/opg-use-an-lpa pull request #517
Opened 2020-08-24 13:27 UTC by Raffers

# Purpose

Creates endpoints to check time remaining on session & refresh the session without navigating away from page.

Fixes UML-984

## Approach

Adjusts initializeSessionFromRequest & persistSession on EncryptedCookiePersistence. It first stores any session information along with the request path. We then look at if the session is being checked & use the original session time if we are targeting the check endpoint.

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [x] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-08-24 14:57 UTC, cooperaj commented on service-front/app/src/Common/src/Handler/SessionCheckHandler.php
> +    public function __construct(ContainerInterface $container)
Please don't inject the container anywhere. If access to things from the container is needed then inject those values from a factory class that pull from the container. As a general rule the only classes with access to the container are factory classes.

2020-08-24 15:04 UTC, cooperaj requested changes

2020-08-24 15:04 UTC, cooperaj commented on service-front/app/src/Common/src/Service/Session/EncryptedCookiePersistence.php
> +        $time = isset($this->originalSessionData[self::SESSION_TIME_KEY])
Would prefer to see this check in a separate method.

I think the check of the url needs figuring out a different way as well. Is the request url not available in the ResponseInterface? Can we not store the session time instead of the entire session? Is it possible to avoid the persistSession  method call entirely when accessing this endpoint?

2020-08-25 15:44 UTC, Raffers commented on service-front/app/src/Common/src/Service/Session/EncryptedCookiePersistence.php
> +        $time = isset($this->originalSessionData[self::SESSION_TIME_KEY])
It's only available as a header, which would need additional formatting to get it to the same state. But it's already in the required state in the request object. 
I was thinking in case anything else was needed for the session, but I've changed that now. 
I did initially look at trying to bypass persistSession entirely but couldn't find a nice way to do it without going too far down into the framework.

2020-09-01 10:36 UTC, cooperaj commented on service-front/app/test/CommonTest/Handler/SessionCheckHandlerTest.php
> +<?php
Handlers we typically mark as @codecoverageignore and rely on behat to test. If you think there's benefit in having this thats also good (due to the json based nature).

2020-09-01 11:48 UTC, Raffers commented on service-front/app/src/Common/src/Service/Session/EncryptedCookiePersistence.php
> +        return isset($this->originalSessionTime)
I was getting Property access error's for some reason before, I've just removed it after doing null coalescing check & it's now passing.

2020-09-01 11:50 UTC, Raffers commented on service-front/app/test/CommonTest/Handler/SessionCheckHandlerTest.php
> +<?php
Yer, that was my thinking. As we use Behat as if it was a user performing the action, I thought it best to do Check & Refresh as unit tests due to more being an endpoint that is checked automatically.

2020-09-04 09:24 UTC, williamfalconeruk submitted a review, later dismissed

2020-09-14 08:35 UTC, GemTay approved these changes

2020-09-14 13:27 UTC, cooperaj approved these changes

2020-09-14 16:26 UTC, merged