UML-1036 Translated cookie page
ministryofjustice/opg-use-an-lpa pull request #518
Opened 2020-08-24 15:29 UTC by GemTay

# Purpose

Welsh translation for the cookie page 

Fixes UML-1036

## Approach

Added trans tags to thee cookie twig file and updated PO/POT/MO files with translations

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-08-24 16:01 UTC, cooperaj reviewed
Don't worry about the POT MO and PO files. We'll be fixing them up with the extraction tool.

2020-08-24 16:04 UTC, cooperaj requested changes

2020-08-24 16:04 UTC, cooperaj commented on service-front/app/languages/cy.po
> +"X-Generator: Poedit 2.4\n"
Best revert these MO/PO/T out

2020-08-24 16:04 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/cookies.html.twig
>                      {{ govuk_form_element(form.get('usageCookies'), {'value_options':
These labels will need to have the trans filter applied like:

`'label': 'Use cookies...' | trans,`

2020-08-25 11:09 UTC, Raffers approved these changes

2020-08-25 11:57 UTC, SeemaMenon approved these changes

2020-08-25 12:46 UTC, cooperaj approved these changes

2020-08-25 14:11 UTC, merged