Uml 1048 - Translation tag added for few more templates
ministryofjustice/opg-use-an-lpa pull request #520
Opened 2020-08-26 12:08 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1048

Fixes UML-1048

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-08-26 12:48 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig
> +                        {{ activeCodeCount }} {% trans %}active codes{% endtrans %}
Does this need changing to accommodate welsh numbering?

2020-08-26 15:18 UTC, cooperaj requested changes

2020-08-26 15:18 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/change-details.html.twig
> +        <a href="{{ path('lpa.view', {}, {'lpa': actorToken}) }}" class="govuk-back-link">{% trans %}Back{% endtrans %}</a>
I think we can make this a little more elegant

```suggestion
        {% if actorToken != 'null' %}
            {% set backLink = path('lpa.view', {}, {'lpa': actorToken}) %}
        {% else %}
            {% set backLink = path('your-details') %}
        {% endif %}
        <a href="{{ backLink }}" class="govuk-back-link">{% trans %}Back{% endtrans %}</a>
```

It *may* not work due to the context of the backLink variable so will need a try. But I think it's a cleaner approach

2020-08-26 15:18 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/change-details.html.twig
> +                            {% trans with {'%death-notification-link%': path('lpa.death-notification', {}, {'lpa': actorToken})} %}Find out more about what to do if <a class="govuk-link" href="%death
Maybe %link%? We don't have multiple links in this snippet so giving it a bigger name is unnecessary.

2020-08-26 15:18 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/death-notification.html.twig
> +            <a href="{{ path('lpa.change-details', {}, {'lpa': actorToken}) }}" class="govuk-back-link">{% trans %}Back{% endtrans %}</a>
Same as above

2020-08-26 15:18 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/death-notification.html.twig
> +                        <li>{% trans %}there are other attorneys who can act 'jointly and severally' -
This snippet has two types of single quote in it. Please can we change the second set to the standard ones?

2020-08-26 15:18 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig
> +                        {{ activeCodeCount }} {% trans %}active codes{% endtrans %}
Yes. This can be done with the pluralisation handling.

Replace lines 33 - 37
```
{% trans count activeCodeCount %}%count% active code|%count% active codes{% endtrans %}
```

2020-08-26 18:58 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/change-details.html.twig
> +        <a href="{{ path('lpa.view', {}, {'lpa': actorToken}) }}" class="govuk-back-link">{% trans %}Back{% endtrans %}</a>
That worked and I adopted :)

2020-08-26 19:02 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/death-notification.html.twig
> +            <a href="{{ path('lpa.change-details', {}, {'lpa': actorToken}) }}" class="govuk-back-link">{% trans %}Back{% endtrans %}</a>
done

2020-08-27 13:19 UTC, cooperaj requested changes

2020-08-27 13:19 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/change-details.html.twig
> +                      <a class="govuk-link" href="mailto:customerservices@publicguardian.gov.uk">{% trans %}customerservices@publicguardian.gov.uk{% endtrans %}</a><br>
Don't think the email needs translating :P

2020-08-27 13:19 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/change-details.html.twig
> +                        {% trans %}Office of the Public Guardian<br>
Probably not the address either?

2020-08-27 13:19 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/death-notification.html.twig
> +                        <a class="govuk-link" href="mailto:customerservices@publicguardian.gov.uk">{% trans %}customerservices@publicguardian.gov.uk{% endtrans %}</a>
Email?

2020-08-27 13:19 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/lpa-add.html.twig
> +                        'input_prefix': 'C - '| trans,
This is a fixed piece of data, doesn't need translating

2020-08-27 14:28 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/change-details.html.twig
> +                        {% trans %}Office of the Public Guardian<br>
removed the tag

2020-08-27 14:28 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/change-details.html.twig
> +                      <a class="govuk-link" href="mailto:customerservices@publicguardian.gov.uk">{% trans %}customerservices@publicguardian.gov.uk{% endtrans %}</a><br>
removed the tag

2020-08-27 14:29 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/death-notification.html.twig
> +                        <a class="govuk-link" href="mailto:customerservices@publicguardian.gov.uk">{% trans %}customerservices@publicguardian.gov.uk{% endtrans %}</a>
removed

2020-08-27 14:47 UTC, cooperaj approved these changes

2020-08-28 08:47 UTC, Raffers approved these changes

2020-08-28 10:25 UTC, merged