UML-760: terms page opens in new tab now
ministryofjustice/opg-use-an-lpa pull request #538
Opened 2020-09-02 09:05 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-760

Fixes UML-760

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-09-03 16:33 UTC, cooperaj commented on service-front/app/features/actor-terms-of-use.feature
> +#  @ui
Please remove

2020-09-03 16:33 UTC, cooperaj commented on service-front/app/features/viewer-terms-of-use.feature
> +#  @ui
Please remove.

2020-09-03 16:33 UTC, cooperaj commented on service-front/app/features/actor-terms-of-use.feature
> +#  @ui
Also, cleanup any steps that are no longer used (the context files are massive)

2020-09-03 21:04 UTC, SeemaMenon commented on service-front/app/features/viewer-terms-of-use.feature
> +#  @ui
My bad...thought this was all removed. Sorry

2020-09-04 08:57 UTC, williamfalconeruk submitted a review, later dismissed

2020-09-04 09:11 UTC, williamfalconeruk commented
@SeemaMenon looks like a failing test. might need to take a look..

2020-09-11 08:59 UTC, charlesmmarshall commented on service-front/app/src/Actor/templates/actor/actor-terms-of-use.html.twig
> -        {{ include('@partials/welsh-switch.html.twig') }}
hey @SeemaMenon - was this link & partial meant to be removed (apologies - dont know much context on this ticket)?

2020-09-11 09:02 UTC, johnnolan commented on service-front/app/src/Actor/templates/actor/actor-privacy-notice.html.twig
> +                    <a class="govuk-link" href="%terms-of-use%" target="_blank">terms of use</a> and <a class="govuk-link" href="%cookie%">cookie policy.{% endtrans %}</a>
When we open a link in a new window/tab we need to add some text to indicate to the user what is about to happen. An example is here https://design-system.service.gov.uk/styles/typography/#links

`<a href="#" class="govuk-link" rel="noreferrer noopener" target="_blank">govuk-link (opens in new tab)</a>`

This will need to be done on all subsequent links. Maybe an opportunity for a new reusable twig component

2020-09-11 09:37 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/actor-terms-of-use.html.twig
> -        {{ include('@partials/welsh-switch.html.twig') }}
Good catch there @charlesmmarshall . That's not meant to be removed.

2020-09-11 14:18 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/actor-privacy-notice.html.twig
> +                    <a class="govuk-link" href="%terms-of-use%" target="_blank">terms of use</a> and <a class="govuk-link" href="%cookie%">cookie policy.{% endtrans %}</a>
removed the target in this page as terms of use need not open in new tab. [privacy notice page is not a data transactional page]. Applying the design suggestion to viewer 'enter code' page and use 'account create' page.

2020-09-11 14:19 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/actor-privacy-notice.html.twig
> +                    <a class="govuk-link" href="%terms-of-use%" target="_blank">terms of use</a> and <a class="govuk-link" href="%cookie%">cookie policy.{% endtrans %}</a>
reverted changes here hence

2020-09-11 14:23 UTC, SeemaMenon commented on service-front/app/src/Viewer/templates/viewer/viewer-privacy-notice.html.twig
> +                    You can find more information about using the View a lasting power of attorney service in our <a class="govuk-link" href="{{ path('terms-of-use') }}" target="_blank">terms of use<
The trans tag wrapping was missing, added the tags and removed the target. This page is again not a data transactional page, hence 'terms of use' page can open in same tab.

2020-09-15 09:53 UTC, GemTay reviewed
Looking good! Is it possible to use $`this->ui->getSession()->getWindowNames();` in behat to assert that the page has opened in a new tab?

2020-09-15 09:59 UTC, cooperaj submitted a review, later dismissed

2020-09-15 10:10 UTC, GemTay submitted a review, later dismissed

2020-09-16 09:34 UTC, GemTay requested changes

2020-09-16 09:34 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/ActorTermsOfUseHandler.php
> +        return new HtmlResponse($this->renderer->render('actor::actor-terms-of-use'));
The route name should just be 'actor::terms-of-use' now

2020-09-16 09:34 UTC, GemTay commented on service-front/app/src/Viewer/src/Handler/ViewerTermsOfUseHandler.php
> +        return new HtmlResponse($this->renderer->render('viewer::viewer-terms-of-use'));
same here, the routes have changed and don't need to specify actor or viewer anymore

2020-09-16 09:43 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/ActorTermsOfUseHandler.php
> +        return new HtmlResponse($this->renderer->render('actor::actor-terms-of-use'));
Good spot. Should have caused a behat test failure. Best to figure out why it didnt

2020-09-16 13:03 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/ActorTermsOfUseHandler.php
> +        return new HtmlResponse($this->renderer->render('actor::actor-terms-of-use'));
OK, @cooperaj , @GemTay - Had a check here.
The 'terms of use' template and 'privacy notice' template are different for both user and view and hence we have them as separate files. So changing handler to use 'actor::terms-of-use' **would error**.

The behat tests do not fail as we use the absolute path as in the routes.


<img width="476" alt="Screenshot 2020-09-16 at 13 44 14" src="https://user-images.githubusercontent.com/6483585/93339015-020a6180-f823-11ea-8c54-d3507855f32d.png">
<img width="975" alt="Screenshot 2020-09-16 at 13 45 38" src="https://user-images.githubusercontent.com/6483585/93339017-033b8e80-f823-11ea-94bd-be5f1d3b406c.png">

2020-09-16 14:08 UTC, SeemaMenon commented on service-front/app/src/Viewer/src/Handler/ViewerTermsOfUseHandler.php
> +        return new HtmlResponse($this->renderer->render('viewer::viewer-terms-of-use'));
As above

2020-09-16 14:18 UTC, GemTay commented on service-front/app/features/context/UI/ViewerContext.php
> +    public function iAmTakenBackToTheEnterCodePage()
This test shouldn't be needed anymore since there is no back button on the terms of use pages

2020-09-16 14:40 UTC, SeemaMenon commented on service-front/app/features/context/UI/ViewerContext.php
> +    public function iAmTakenBackToTheEnterCodePage()
True the terms of use does not have back button.

This function is used in another test to check another scenario. Hence if removed will break the scenario below:
<img width="626" alt="Screenshot 2020-09-16 at 15 36 44" src="https://user-images.githubusercontent.com/6483585/93352600-ec049d00-f832-11ea-9cf8-8cf718974a22.png">
<img width="623" alt="Screenshot 2020-09-16 at 15 39 32" src="https://user-images.githubusercontent.com/6483585/93352609-ed35ca00-f832-11ea-98c7-4f6be8374a71.png">

2020-09-16 14:44 UTC, GemTay submitted a review, later dismissed

2020-09-17 15:04 UTC, GemTay approved these changes

2020-09-17 15:50 UTC, cooperaj approved these changes

2020-09-17 16:36 UTC, merged