UML-1045 banner message that only LPAs after a certain date can use the service
ministryofjustice/opg-use-an-lpa pull request #539
Opened 2020-09-02 12:24 UTC by nickdavis2001

# Purpose

_UML-1045 banner message that only LPAs after a certain date can use the service_

## Approach

_Add a new twig with the banner, include this in the triage page, behat test_

## Learning

__

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-09-02 16:39 UTC, Raffers requested changes

2020-09-02 16:39 UTC, Raffers commented on service-front/web/src/scss/_banner.scss
> +.moj-banner--success {
shouldn't thie be `__` in place of `--`

Also, have a read of John's comment on a previous PR. The structure of this can be changed - https://github.com/ministryofjustice/opg-use-an-lpa/pull/511#discussion_r475496095

2020-09-03 08:12 UTC, nickdavis2001 commented on service-front/web/src/scss/_banner.scss
> +.moj-banner--success {
Thanks for feedback. :) This was a direct copy from Make An LPA, so, while there may well be flaws in this, its tried and tested in production already elsewhere. I'm a little disinclined to fix this at this point in time, since its already passed UAT and we want to get Welsh translation out. How about if I make another story on the backlog to revisit this? (open to arguments to the contrary.  ;). )

2020-09-03 08:45 UTC, Raffers submitted a review, later dismissed

2020-09-03 08:49 UTC, johnnolan commented on service-front/web/src/scss/_banner.scss
> +.moj-banner--success {
`--` is right but as Chris said, keeping it line with the other style files would be good. Given the conversation in standup, carry on deploying and create a little ticket to tidy this up. Happy to pair to show how you can restructure it and should be a 1 pointer

2020-09-03 08:52 UTC, johnnolan submitted a review, later dismissed

2020-09-03 12:18 UTC, williamfalconeruk approved these changes

2020-09-03 12:20 UTC, merged