UML 1059: Welsh issue fix 2 added missing tags
ministryofjustice/opg-use-an-lpa pull request #545
Opened 2020-09-03 11:31 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1059

Fixes UML-UML-1059

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-09-03 11:42 UTC, Raffers submitted a review, later dismissed

2020-09-03 12:36 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/activate-account-not-found.html.twig
> +                    <p class="govuk-body">{% trans with {'%link%': "mailto:customerservices@publicguardian.gov.uk" } %}If you need more help activating your account, email <a href="%link%">customerse
The link url is being passed in but the link text isn't?

2020-09-03 12:50 UTC, cooperaj requested changes
Few things to look at.

2020-09-03 12:50 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/check-lpa.html.twig
> +                                    {% trans %}Attorney{% endtrans %}
```suggestion
                                    {% trans %}Attorney{% notes %}Users role on an LPA{% endtrans %}
```

2020-09-03 12:50 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/check-lpa.html.twig
> +                                    {% trans %}Donor{% endtrans %}
```suggestion
                                    {% trans %}Donor{% notes %}Users role on an LPA{% endtrans %}
```

2020-09-03 12:50 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/check-lpa.html.twig
> +                                    {% trans %}Donor{% endtrans %}
Both of these might help Lewis figure out a better word.

2020-09-03 12:50 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/view-lpa-summary.html.twig
> +                            <h2 class="govuk-heading-m heading-m-alt-1">{% trans %}This <abbr title="lasting power of attorney">LPA</abbr> is registered and can be used now{% endtrans %}</h2>
Is status always registered? In both cases?

2020-09-03 12:50 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/account-bar.html.twig
> +    <p class="govuk-body-s">{% trans %}Last signed in:{% endtrans %}
```suggestion
    <p class="govuk-body-s">{% trans %}Last signed in:{% endtrans %} {{ user.getDetail('LastLogin') is empty ? "Never" | trans : user.getDetail('LastLogin')|date('j F Y g:ia') }}</p>
```

Would also work

2020-09-03 12:50 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/account-bar.html.twig
>          <li><a href="/logout" class="govuk-link">{% trans %}Sign out{% endtrans %}</a></li>
Missed '/logout'

2020-09-03 12:50 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/viewer-privacy-notice.html.twig
> +                    {% trans %}
This link is done above using the placeholder value. Why different here?

2020-09-03 13:11 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/activate-account-not-found.html.twig
> +                    <p class="govuk-body">{% trans with {'%link%': "mailto:customerservices@publicguardian.gov.uk" } %}If you need more help activating your account, email <a href="%link%">customerse
removed the wrapping here....we don't need it here actually right?

2020-09-03 13:23 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig
> +                <span class="govuk-heading-m govuk-!-margin-bottom-0">{{ caseSubtype|trans }}</span>
caseSubtype is either 'Property and finance' or 'Health and welfare'. 
<img width="842" alt="Screenshot 2020-09-03 at 14 17 42" src="https://user-images.githubusercontent.com/6483585/92119971-61fb1400-edf0-11ea-8b13-02af6afe72a3.png">


Will this not work with trans?

2020-09-03 13:23 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/view-lpa-summary.html.twig
> +                            <h2 class="govuk-heading-m heading-m-alt-1">{% trans %}This <abbr title="lasting power of attorney">LPA</abbr> is registered and can be used now{% endtrans %}</h2>
Yes, checked with Jude yesterday

2020-09-03 13:32 UTC, cooperaj commented on service-front/app/src/Common/templates/partials/account-bar.html.twig
> +        {% if user.getDetail('LastLogin') is empty %}
This and the 4 lines below are now redundant

2020-09-03 13:49 UTC, SeemaMenon commented on service-front/app/src/Viewer/templates/viewer/viewer-privacy-notice.html.twig
> +                    {% trans %}
changed

2020-09-03 13:51 UTC, williamfalconeruk commented on service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig
> +                <span class="govuk-heading-m govuk-!-margin-bottom-0">{{ caseSubtype|trans }}</span>
will probably need to add this to the pot file, for lewis to translate.

2020-09-03 14:27 UTC, SeemaMenon commented on service-front/app/src/Common/templates/partials/account-bar.html.twig
> +        {% if user.getDetail('LastLogin') is empty %}
merged with master, so I assume the file is upto date now.

2020-09-03 14:29 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig
> +                <span class="govuk-heading-m govuk-!-margin-bottom-0">{{ caseSubtype|trans }}</span>
@williamfalconeruk - I can see this in the pot file already
<img width="619" alt="Screenshot 2020-09-03 at 15 28 31" src="https://user-images.githubusercontent.com/6483585/92128315-2f561900-edfa-11ea-8cbb-edc8246bf63e.png">

2020-09-03 14:38 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig
> +                <span class="govuk-heading-m govuk-!-margin-bottom-0">{{ caseSubtype|trans }}</span>
ok. I would say that the '|trans' filter needs adding to the `{% set caseSubtype ... ` line above and removing from the template line.

2020-09-03 14:40 UTC, cooperaj commented on service-front/app/src/Viewer/templates/viewer/viewer-privacy-notice.html.twig
> +                    {% trans %}Find out more about <a class="govuk-link" href="https://www.gov.uk/help/cookies">cookies</a>.{% endtrans %}
For consistency links should probably be done as placeholders

2020-09-03 14:42 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/activate-account-not-found.html.twig
> +                    <p class="govuk-body">
No {%trans%}?

2020-09-03 15:25 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/activate-account-not-found.html.twig
> +                    <p class="govuk-body">{% trans with {'%link%': "mailto:customerservices@publicguardian.gov.uk" } %}If you need more help activating your account, email <a href="%link%">customerse
changed

2020-09-03 15:29 UTC, SeemaMenon commented on service-front/app/src/Viewer/templates/viewer/viewer-privacy-notice.html.twig
> +                    {% trans %}Find out more about <a class="govuk-link" href="https://www.gov.uk/help/cookies">cookies</a>.{% endtrans %}
done

2020-09-03 15:31 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/activate-account-not-found.html.twig
> +                    <p class="govuk-body">
corrected ... sorry, my bad!

2020-09-04 08:42 UTC, Raffers approved these changes

2020-09-04 08:46 UTC, williamfalconeruk approved these changes

2020-09-04 08:55 UTC, cooperaj submitted a review, later dismissed

2020-09-04 09:08 UTC, GemTay commented on service-front/app/src/Common/templates/layout/default.html.twig
> +                <a class="govuk-footer__link govuk-footer__copyright-logo" href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-
Is the copyright  'c' symbol okay to be included in translation?

2020-09-04 09:16 UTC, GemTay commented on service-front/app/src/Viewer/templates/viewer/viewer-privacy-notice.html.twig
> +                    <li>{% trans %}share your information with other organisations for marketing, market research or commercial purposes{% endtrans %}
missing a closing </li>

2020-09-04 09:18 UTC, GemTay submitted a review, later dismissed
just a small change

2020-09-04 09:27 UTC, williamfalconeruk commented on service-front/app/src/Viewer/templates/viewer/viewer-privacy-notice.html.twig
> +                    <li>{% trans %}share your information with other organisations for marketing, market research or commercial purposes{% endtrans %}
🦅  👁️  - good spot!

2020-09-04 09:28 UTC, SeemaMenon commented on service-front/app/src/Common/templates/layout/default.html.twig
> +                <a class="govuk-footer__link govuk-footer__copyright-logo" href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-
Think it is not

2020-09-04 09:35 UTC, williamfalconeruk approved these changes

2020-09-04 09:35 UTC, cooperaj submitted a review, later dismissed

2020-09-04 09:35 UTC, Raffers approved these changes

2020-09-04 09:40 UTC, GemTay submitted a review, later dismissed

2020-09-04 09:42 UTC, williamfalconeruk approved these changes

2020-09-04 09:43 UTC, cooperaj approved these changes

2020-09-04 09:43 UTC, GemTay approved these changes

2020-09-04 09:53 UTC, merged