minor changes to welsh content from lewis
ministryofjustice/opg-use-an-lpa pull request #558
Opened 2020-09-11 14:13 UTC by GemTay

# Purpose

Lewis has made some minor changes to the welsh content

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-09-11 14:35 UTC, charlesmmarshall submitted a review, later dismissed

2020-09-11 14:42 UTC, SeemaMenon approved these changes

2020-09-11 14:59 UTC, SeemaMenon requested changes
@GemTay  - Just noticed the quotes which needs correcting

2020-09-11 15:00 UTC, SeemaMenon commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
The quotes have changed here

2020-09-11 15:00 UTC, SeemaMenon commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
Quotes changed here

2020-09-11 15:00 UTC, SeemaMenon commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +"Gallwch nawr <a href=“%link%” class=“govuk-link”>fewngofnodi i’ch cyfrif</a>"
Quotes changed

2020-09-11 15:01 UTC, SeemaMenon commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +"link”>mewngofnodwch</a>."
Quotes

2020-09-11 15:01 UTC, SeemaMenon commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
Quotes changed

2020-09-14 09:20 UTC, GemTay commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +msgstr "Rhowch y cod mynediad hwn i %organisation%"
This was the only change made

2020-09-14 13:19 UTC, cooperaj approved these changes

2020-09-14 13:19 UTC, cooperaj commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +msgstr "Rhowch y cod mynediad hwn i %organisation%"
Aye, it's somewhat frustrating that poedit keeps messing around with the line length.

2020-09-15 09:42 UTC, SeemaMenon approved these changes

2020-09-15 10:23 UTC, merged