UML-694 Passwords wrapped by HiddenString to prevent leakage
ministryofjustice/opg-use-an-lpa pull request #561
Opened 2020-09-15 16:01 UTC by SeemaMenon

# Purpose
https://opgtransform.atlassian.net/browse/UML-694
Currently we pass around string passwords from handlers to services, these should be wrapped by 
HiddenString as soon as possible to prevent leakage in log files.

Fixes UML-694

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] The product team have tested these changes

2020-09-16 14:09 UTC, johnnolan submitted a review, later dismissed
With my limited PHP skills, the code looks sensible to me

2020-09-16 14:12 UTC, nickdavis2001 approved these changes
lgtm

2020-09-18 13:07 UTC, cooperaj requested changes
As per the comment below, we shouldn't be passing passwords from the user input into service layers of the application, the handlers need to wrap passwords before passing them on.

2020-09-18 13:07 UTC, cooperaj commented on service-api/app/src/App/src/Service/User/UserService.php
> +        $user = $this->usersRepository->add($id, $data['email'], new HiddenString($data['password']), $activationToken, $activationTtl);
I would argue that the data array should contain a hiddenstring already. It should not be being made in this service class

2020-09-21 08:45 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/User/UserService.php
> +        $user = $this->usersRepository->add($id, $data['email'], new HiddenString($data['password']), $activationToken, $activationTtl);
Made the changes and it works [thought that error'd for me previously]

2020-09-24 15:18 UTC, cooperaj approved these changes
LGTM

2020-09-24 15:36 UTC, GemTay approved these changes

2020-09-25 08:30 UTC, merged