UML-1064: Removed inactive code duplication
ministryofjustice/opg-use-an-lpa pull request #566
Opened 2020-09-17 15:08 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1064

Fixes UML-1064

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] The product team have tested these changes

2020-09-21 10:37 UTC, cooperaj approved these changes

2020-09-21 11:43 UTC, williamfalconeruk commented on service-front/app/src/Actor/templates/actor/partials/check-code-details.html.twig
> +            {% if (check_if_code_has_expired(code.Expires) and check_if_code_is_cancelled(code)) %}
I wonder if you need both of these? as you have a check code is cancelled already in the `elseif` part...

2020-09-21 11:46 UTC, williamfalconeruk commented on service-front/app/src/Actor/templates/actor/partials/check-code-details.html.twig
> +            {% if (check_if_code_has_expired(code.Expires) and check_if_code_is_cancelled(code)) %}
possibly swap the logic around: so you have the cancelled check first, then do the expiry check as the last thing. that might be simpler - unless i've missed something...

2020-09-21 11:47 UTC, williamfalconeruk requested changes
think the logic needs to be simplified here.

Requirement states:
<img width="424" alt="Screenshot 2020-09-21 at 13 21 36" src="https://user-images.githubusercontent.com/6483585/93765839-6f483900-fc0d-11ea-962c-78885cc4fcc2.png">

2020-09-21 12:19 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/partials/check-code-details.html.twig
> +            {% if (check_if_code_has_expired(code.Expires) and check_if_code_is_cancelled(code)) %}
@williamfalconeruk - I had to had in this logic because the requirement says;

**For an inactive code:** 
1. if an access is both cancelled and expired, then the status in the check access code page should show the status as CANCELLED.
2. If an an access code is cancelled, show the status as CANCELLED
3. If an access code is expired, show the status as EXPIRED.

Had to keep the conditions in the else if explicitly because otherwise the active code too will show a status [which is not needed and correct]

2020-09-21 12:41 UTC, williamfalconeruk commented on service-front/app/src/Actor/templates/actor/partials/check-code-details.html.twig
> +            {% if (check_if_code_has_expired(code.Expires) and check_if_code_is_cancelled(code)) %}
to work this out i did a small bit of logic deduction on this. Looking at the rules: 

- `CANCELLED` will need to appear whether or not your code is expired, so you just could put `check_if_code_is_cancelled` as your first logic check. 
-the `elseif` part then will catch all non cancelled and then you can `check_if_code_is_expired` at that point. 

Hope this clarifies 🙂

2020-09-21 12:43 UTC, williamfalconeruk approved these changes
LGTM 👍

2020-09-22 08:56 UTC, nickdavis2001 approved these changes

2020-09-22 09:02 UTC, merged