Uml-985 frontend session check
ministryofjustice/opg-use-an-lpa pull request #571
Opened 2020-09-23 11:55 UTC by Raffers

# Purpose

Implements the front end part of session checking for users, no translation required as the displayed prompt has already been translated.

Fixes UML-985

## Approach

Adjusts the already implemented JS to make a call to the backend endpoint to confirm the current state of the session & checks if it at the warning threshold

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [x] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] The product team have tested these changes

2020-11-04 10:03 UTC, GemTay approved these changes

2020-11-04 12:01 UTC, GemTay requested changes
After manually testing, the popup displayed correctly, however when I clicked "Sign out" on the popup box, it did not sign me out

2020-11-04 13:18 UTC, GemTay commented on service-front/app/src/Common/templates/partials/session-dialog.html.twig
> +    <a class="govuk-button govuk-button--secondary govuk-!-margin-bottom-1" href="{{ path('logout') }}">
Fixed sign out issue here

2020-11-04 13:18 UTC, GemTay approved these changes

2020-11-04 13:28 UTC, johnnolan submitted a review, later dismissed

2020-11-05 11:57 UTC, johnnolan commented on service-front/web/src/index.js
> +if (document.getElementsByClassName('js-signed-in').length > 0) {
Now its only for the actor side, you probably want to do an additional check for the dialog id as well so the JS doesn't run?

`document.getElementsByClassName('js-signed-in').length > 0 && document.getElementsById('dialog').length > 0`

2020-11-06 10:10 UTC, cooperaj commented on service-front/app/src/Viewer/src/Handler/ViewerSessionCheckHandler.php
> +        if ($user !== null && $timeRemaining <= 300) {
Same here

2020-11-06 12:57 UTC, johnnolan requested changes

2020-11-06 12:57 UTC, johnnolan commented on service-front/web/src/index.js
> +import {doc} from "prettier";
Accidental import

2020-11-06 15:54 UTC, johnnolan approved these changes

2020-11-06 15:56 UTC, cooperaj approved these changes
Solid

2020-11-06 16:23 UTC, merged