UML - 1086 : Show all access codes generated by co-actors in check access code page
ministryofjustice/opg-use-an-lpa pull request #585
Opened 2020-10-01 13:31 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1086

Fixes UML-1086

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] The product team have tested these changes

2020-10-12 10:27 UTC, GemTay commented on service-api/app/src/App/src/DataAccess/DynamoDb/ViewerCodes.php
> +    public function getCodesByUserLpa(string $siriusUid): array
I would change this function name to getCodesByLpaId

2020-10-12 10:29 UTC, GemTay commented on service-api/app/test/AppTest/DataAccess/DynamoDb/ViewerCodesTest.php
> +    public function can_query_by_user_lpa(){
rename to can_query_by_lpa_id maybe?

2020-10-12 11:46 UTC, GemTay requested changes
looks good, just some small changes needed

2020-10-12 12:56 UTC, GemTay approved these changes

2020-10-14 08:36 UTC, merged

2020-10-14 08:40 UTC, cooperaj approved these changes