Uml 840 and Uml 1010: Minor dac changes applied
ministryofjustice/opg-use-an-lpa pull request #586
Opened 2020-10-02 14:48 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-840
https://opgtransform.atlassian.net/browse/UML-1010

Fixes UML-840 and UML-1010

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] The product team have tested these changes

2020-10-05 15:16 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                            <h3 class="govuk-heading-m">{% trans %}Active codes{% endtrans %}</h3>
"Active codes" an "inactive codes" should be a h2 as the ticket states, the govuk-accordion__section-heading is already a h3 (line 3 in check-code-details.html.twig) so the ticket is no longer needed

2020-10-05 15:16 UTC, GemTay requested changes
H3's just need changing back to h2's

2020-10-05 15:40 UTC, SeemaMenon reviewed
@GemTay - reverted changes. My bad !

2020-10-05 15:40 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                            <h3 class="govuk-heading-m">{% trans %}Active codes{% endtrans %}</h3>
I have no clue what my understanding was...corrected back.

2020-10-06 08:39 UTC, GemTay approved these changes

2020-10-06 20:21 UTC, merged