Uml 1079 display lpas as grouped by donor
ministryofjustice/opg-use-an-lpa pull request #588
Opened 2020-10-07 11:38 UTC by GemTay

# Purpose

Groups LPAs by donor name in alphabetical order by surname, then firstname. Each donors LPA(s) are then sorted to show HW Lpas first, followed by property and finance. Finally, if a donor has more than one LPA of the same type, they are sorted by the most recently added.

Fixes UML-1079

## Approach

Created separate functions for each stage of the ordering/grouping process. The LPAs are first sorted alphabetically by donors surname, then the ordered donors are grouped by name. The final function sorts each donor's LPAs to display HW lpas first, then sorts LPA's of the same type by most recently added. I created a unit tests to test these functions in a chain. The first unit test is rather large as lots of test data was needed to test that different scenarios were sorted correctly

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [x] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] The product team have tested these changes

2020-10-12 14:05 UTC, cooperaj commented on service-front/app/src/Common/src/View/Twig/LpaExtension.php
> +            new TwigFunction('donor_name_with_dob_removed', [$this, 'donorNameWithDobRemoved']),
I would say that it's better to create the donor name on the twig template using the data we have rather than manipulate what is essentially a sort key. I know it gives the same information at this time but this way feels... less clean.

2020-10-21 16:15 UTC, SeemaMenon submitted a review, later dismissed

2020-10-21 16:18 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/lpa-dashboard.html.twig
> +
Didn't find an alternate solution here! @cooperaj  - any suggestions?

2020-10-22 14:55 UTC, cooperaj requested changes

2020-10-22 14:55 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/lpa-dashboard.html.twig
> +
I would say that we probably need a custom function here. I've likely forgotten but why will the donor names have numbers in?

In the case of double-barrelled names what will happen with the removed hyphens?

2020-10-23 16:39 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/lpa-dashboard.html.twig
> +
@cooperaj I've added back in the custom twig function that was there before. The key is the donors name and dob (so that 2 different donors with the same name dont get grouped when DOB is not same). The twig function i've created does a regex match to remove the DOB and trims the string, so double-barrelled names wont be affected

2020-10-26 12:31 UTC, SeemaMenon approved these changes

2020-10-29 12:33 UTC, SeemaMenon approved these changes

2020-10-30 09:36 UTC, cooperaj approved these changes

2020-11-03 10:26 UTC, merged