UML-1099: Updated content and translation
ministryofjustice/opg-use-an-lpa pull request #589
Opened 2020-10-09 08:10 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1099

Fixes UML-1099

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [X] I have added welsh translation tags and updated translation files
* [ ] The product team have tested these changes

2020-10-09 13:52 UTC, GemTay commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +"\"%link%\" class=\"govuk-link\">resend the activation email</a>."
I dont think this link looks quite right...

2020-10-09 13:53 UTC, GemTay commented on service-front/app/languages/messages.pot
> +"                        If it's not in your inbox, check your spam, bulk or junk email inbox.\n"
Not sure why the translation tool has added all these spaces?

2020-10-09 13:55 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/create-account-success.html.twig
>                  <p class="govuk-body">{% trans with {'%email%': emailAddress} %}We've emailed a link to %email%. Click on the link to activate your account. The link will work for the next 24 hours.{
This text in this paragraph needs to be slightly larger looking at the content image in the ticket, perhaps a "govuk-body-l"? Also the email address needs to be in bold

2020-10-09 13:56 UTC, GemTay requested changes
few tweaks

2020-10-19 16:02 UTC, SeemaMenon commented on service-front/app/languages/messages.pot
> +"                        If it's not in your inbox, check your spam, bulk or junk email inbox.\n"
not sure...have pulled from master and tried generating translations again.

2020-10-19 16:03 UTC, SeemaMenon commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +"\"%link%\" class=\"govuk-link\">resend the activation email</a>."
fixed looks like

2020-10-20 09:15 UTC, cooperaj approved these changes

2020-10-20 09:20 UTC, GemTay approved these changes
looks good :)

2020-10-20 12:06 UTC, merged