UML-1094 Viewer add organisation
ministryofjustice/opg-use-an-lpa pull request #597
Opened 2020-10-19 14:39 UTC by GemTay

# Purpose

Organisations must now enter their organisation name on the check code page, to allow actors to see which organisations have used a code to view their LPA (actor side is a separate ticket)

Fixes UML-1094

## Approach

Created a new organisation form and added it to the check code page. I changed the lpa service functions to take in a new parameter of the organisation that defaults to null if not provided. I removed the summary/full parameter and added logic to change the route (full or summary) based off whether the organisation was provided. 

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] The product team have tested these changes

2020-10-21 13:37 UTC, cooperaj requested changes
Few tweaks

2020-10-21 13:37 UTC, cooperaj commented on service-api/app/src/App/src/Handler/ViewerCodeFullHandler.php
>              throw new RuntimeException("'code' and 'name' are required fields.");
```suggestion
            throw new RuntimeException("'code', 'name'  and 'organisation' are required fields.");
```

2020-10-21 13:37 UTC, cooperaj commented on service-api/app/src/App/src/Service/Lpa/LpaService.php
> +    public function getByViewerCode(string $viewerCode, string $donorSurname, string $organisation = null): ?array
```suggestion
    public function getByViewerCode(string $viewerCode, string $donorSurname, ?string $organisation = null): ?array
```

2020-10-21 13:37 UTC, cooperaj commented on service-api/docker/seeding/start.sh
> +    --attribute-definitions AttributeName=ViewerCode,AttributeType=S AttributeName=Viewed,AttributeType=S\
```suggestion
    --attribute-definitions AttributeName=ViewerCode,AttributeType=S AttributeName=Viewed,AttributeType=S \
```

2020-10-21 13:37 UTC, cooperaj commented on service-front/app/src/Common/src/Service/Lpa/LpaService.php
> +    public function getLpaByCode(string $shareCode, string $donorSurname, string $organisation = null): ?ArrayObject
```suggestion
    public function getLpaByCode(string $shareCode, string $donorSurname, ?string $organisation = null): ?ArrayObject
```

2020-10-21 13:37 UTC, cooperaj commented on service-front/app/src/Viewer/src/Form/Organisation.php
> +        self::NOT_SAME => "Do you want to continue?" .
Whats this message?

2020-10-21 13:54 UTC, GemTay commented on service-front/app/src/Viewer/src/Form/Organisation.php
> +        self::NOT_SAME => "Do you want to continue?" .
@cooperaj I believe its the error message for the CSRF validation. Its the same on the ShareCode.php form

2020-10-22 11:16 UTC, SeemaMenon approved these changes
lgtm

2020-10-22 14:57 UTC, cooperaj approved these changes

2020-10-23 08:44 UTC, merged