UML-396: Lists organisations who viewed lpa using access code
ministryofjustice/opg-use-an-lpa pull request #605
Opened 2020-10-23 08:37 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-396

Fixes UML-396

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [X] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] The product team have tested these changes

2020-11-02 10:30 UTC, GemTay commented on service-api/app/features/actor-check-access-codes.feature
> +  Scenario: As a user I can see the access codes I have created
The scenario could be more descriptive eg "As a user I can see which organisations have used access codes to view an LPA"

2020-11-02 10:34 UTC, GemTay commented on service-api/app/features/context/Acceptance/LpaContext.php
> +                ],
Maybe repeat the above 'Viewed' array to test that a list of orgs are returned who have viewed the LPA using the same code

2020-11-02 10:46 UTC, GemTay commented on service-api/app/test/AppTest/DataAccess/DynamoDb/ViewerCodeActivityTest.php
> +                            0 => [
Again, best to test with more than one here as a list of orgs who have viewed using the same code is the feature

2020-11-02 10:47 UTC, GemTay commented on service-front/app/features/actor-check-access-codes.feature
> +  @ui
Integration tests too

2020-11-02 10:47 UTC, GemTay commented on service-api/app/features/actor-check-access-codes.feature
> +  @acceptance
Integration tests needed too

2020-11-02 10:48 UTC, GemTay requested changes
Few changes to be made :)

2020-11-06 16:16 UTC, GemTay commented on service-api/app/test/AppTest/DataAccess/DynamoDb/ViewerCodeActivityTest.php
> +//        $this->assertNotEmpty($result[0]['Viewed'][1]['Viewed']);
Comments to be removed

2020-11-06 16:18 UTC, GemTay commented on service-api/app/features/context/Acceptance/LpaContext.php
> +                ],
Just need to repeat the array here again

2020-11-06 16:19 UTC, GemTay commented on service-api/app/features/context/Acceptance/LpaContext.php
> +        assertArrayHasKey('Viewed', $response[0]);
add some more assertions here to check the "Viewed" array contains the organisations who viewed the LPA using the code

2020-11-06 16:27 UTC, GemTay commented on service-front/app/features/context/Integration/AccountContext.php
> +    {
this behat step needs filling in. You can probably copy the existing iClickToCheckMyAccessCodes integration step and change the "Viewed" data in the api response. Then update the assertions to check the correct data was returned

2020-11-06 16:29 UTC, GemTay requested changes
a few more tweaks :)

2020-11-09 10:05 UTC, SeemaMenon commented on service-front/app/features/context/Integration/AccountContext.php
> +    {
This was a clear miss .. :(. Added in now.

2020-11-09 10:21 UTC, SeemaMenon commented on service-api/app/test/AppTest/DataAccess/DynamoDb/ViewerCodeActivityTest.php
> +//        $this->assertNotEmpty($result[0]['Viewed'][1]['Viewed']);
My mistake, sorry

2020-11-09 11:31 UTC, GemTay approved these changes
Nice job 👍

2020-11-10 11:25 UTC, GemTay commented on service-api/app/features/context/Acceptance/LpaContext.php
> +//        $code1 = [
Commented code

2020-11-10 11:26 UTC, GemTay requested changes
Comments to be removed

2020-11-10 13:32 UTC, SeemaMenon commented on service-api/app/features/context/Acceptance/LpaContext.php
> +//        $code1 = [
That's unforgivable !!!! Don't kill me Gemma... 😿 

Removed now.

2020-11-10 13:42 UTC, GemTay approved these changes

2020-11-10 16:46 UTC, merged