UML 1080: Remove Lpa API
ministryofjustice/opg-use-an-lpa pull request #620
Opened 2020-11-09 19:20 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1080

Fixes UML-1080

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] The product team have tested these changes

2020-11-13 10:42 UTC, GemTay commented on service-api/app/features/context/Acceptance/AccountContext.php
> +    public function iConfirmRemovalOfTheLPA()
All tests to do with deleting an LPA should live in the LpaContext class rather than the AccountContext

2020-11-13 10:42 UTC, GemTay commented on service-api/app/features/context/Integration/LpaContext.php
> +    public function iConfirmRremovalOfTheLpa()
small typo in the word 'Removal'

2020-11-13 11:12 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/LpaService.php
> +    public function removeLPaFromUserLpaActorMap(string $actorLpaToken): array
typo 'removeLPA...'

2020-11-13 11:27 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/LpaService.php
> +        $userActorLpa = $this->userLpaActorMapRepository->get($actorLpaToken);
Would it be worth also checking that the logged in user Id matches the UserId in the UserLpaActorMap for the LPA that they are trying to delete? This would increase the security of the feature

2020-11-13 11:31 UTC, GemTay commented on service-api/app/test/AppTest/DataAccess/DynamoDb/UserLpaActorMapTest.php
> +            //$this->assertArrayHasKey('TableName', $data);
comment to be removed

2020-11-13 11:36 UTC, GemTay commented on service-api/app/test/AppTest/Service/Lpa/LpaServiceTest.php
> +        $service = new ViewerCodeService(
Missing return statement. This can be simplified by changing $service = to "return"

2020-11-13 11:38 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                                            {% if not check_if_user_lpa_actor_set(code.UserLpaActor) %}
Does this mean that co-actors on the same LPA would not longer be able to see the codes made by the actor who has deleted the LPA? Was this the intended behaviour in the ticket?

2020-11-13 11:44 UTC, GemTay commented on service-front/app/src/Common/src/View/Twig/LpaExtension.php
> +            return true;
The logic of the return statements here is a little confusing. To match the function name, if the token is empty it should return false to read "isUserLpaActorSet" -> (no) return false. If the token is set, you should return true rather than null

2020-11-13 11:45 UTC, GemTay commented on service-front/app/test/CommonTest/View/Twig/LpaExtensionTest.php
> +        $this->assertEquals(false, $isSet);
add another test to test both scenarios, when the token is empty and when its not

2020-11-13 11:46 UTC, GemTay requested changes
Few changes to be made

2020-11-13 21:26 UTC, SeemaMenon commented on service-front/app/test/CommonTest/View/Twig/LpaExtensionTest.php
> +        $this->assertEquals(false, $isSet);
Is included  
it_checks_if_user_LPA_actor_is_not_set()
it_checks_if_user_LPA_actor_is_set()

[am unclear the suggestion here]

2020-11-15 19:11 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                                            {% if not check_if_user_lpa_actor_set(code.UserLpaActor) %}
Yes is my understanding from the kickoff conversation we had a week back [Shall get this checked Sarah again].

Removal of an LPA from account by user means removing the associated viewer codes too. But we agreed on the call the viewer code record will not be removed, but will be disassociated from the actor, so that they/or any actor do not see it on the check access code page. This area is not user tested yet! Also the chances of a user removing an LPA [where access code has been generated] is less likely is the assumption, hence requirements in this area was not explicitly mentioned and still fluid until tested I guess.

But if a viewer code [of a removed LPA] was already shared with an organisation, they would be able to view the LPA if it's not expired or cancelled.

2020-11-16 13:25 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/LpaService.php
> +            return null;
Probably more suitable to throw an exception here, since its suspicious activity if a user has manages to delete an LPA from an account which does not have that LPA added

2020-11-16 13:28 UTC, GemTay commented on service-api/app/test/AppTest/Service/Lpa/LpaServiceTest.php
> +        $viewerCodes = null;
doesn't look like this variable is used

2020-11-16 13:30 UTC, GemTay requested changes
just a few more small changes

2020-11-16 14:56 UTC, SeemaMenon commented
> service-api/app/test/AppTest/Service/Lpa/LpaServiceTest.php

removed

2020-11-16 14:57 UTC, SeemaMenon commented on service-api/app/test/AppTest/Service/Lpa/LpaServiceTest.php
> +        $viewerCodes = null;
removed

2020-11-16 15:05 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Lpa/LpaService.php
> +            return null;
Done :)

2020-11-16 15:53 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/LpaService.php
> +                ['Id' => $actorLpaToken]
This log message doesn't look the correct format as there is no {Id} wrapped in curly braces in the message. Think it should be 
`$this->logger->notice(
                'User Id passed does not match the user in userActorLpaMap for token {Id}',
                ['Id' => $actorLpaToken]
            );`

2020-11-16 15:54 UTC, GemTay requested changes
last one, sorry!

2020-11-16 16:32 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Lpa/LpaService.php
> +                ['Id' => $actorLpaToken]
:( :( :( MY BAD !

2020-11-16 16:33 UTC, SeemaMenon commented
> last one, sorry!

@GemTay - Really sorry for this! Corrected ....

2020-11-16 16:50 UTC, GemTay approved these changes
Looks good to me :)

2020-11-16 18:10 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                                            {% if check_if_user_lpa_actor_set(code.UserLpaActor) %}
3 nested if's? 

Probs a good idea to rationalise these down to 1

2020-11-16 18:10 UTC, cooperaj commented on service-front/app/src/Common/src/View/Twig/LpaExtension.php
> +        return false;
```suggestion
        return !empty($token);
```

2020-11-16 18:10 UTC, cooperaj commented on service-front/app/src/Common/src/View/Twig/LpaExtension.php
> +        return false;
But given the simplicity of this TwigFunction I question the need for it. Can this check not be done in the twig file using built-in twig tests?

2020-11-16 20:09 UTC, SeemaMenon commented on service-front/app/src/Common/src/View/Twig/LpaExtension.php
> +        return false;
Removed the function in LPAExtensions for empty check and included in twig.

2020-11-16 20:12 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                                            {% if check_if_user_lpa_actor_set(code.UserLpaActor) %}
still kept the functions to check if_code_expired and if_code_cancelled, and combined the checks in one loop in the twig.

2020-11-17 10:07 UTC, cooperaj approved these changes

2020-11-17 10:07 UTC, merged