UML-1008 Accordion non unique id attributes
ministryofjustice/opg-use-an-lpa pull request #621
Opened 2020-11-10 16:56 UTC by GemTay

# Purpose

In the accordion we have 2 attributes, id and aria-controls that have static values of accordion-default-heading-4 and accordion-default-content-4. These need to be incremented to help screen readers navigate and be able to distinguish between them

Fixes UML-1008

## Approach

I created a counter in the check-access-codes.html.twig file for both active and inactive codes. The counter is then included in the check-code-details.html.twig file and appended to the relevant id's.

## Checklist

* [x] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] The product team have tested these changes

2020-11-10 17:01 UTC, GemTay commented
Evidence of the id's incrementing correctly:
![image](https://user-images.githubusercontent.com/18176021/98706137-61de3e00-2376-11eb-997f-0ca087fb3ccd.png)

2020-11-11 13:36 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                            {% set accordion_counter = 1 %}
There is only ever going to be maximum 2 accordions, active and inactive. The active accordion should always have the id 'default-accordion-1' since it appears first, therefore the inactive accordion will be 'default-accordion-2'. In the case where by the use only has inactive codes, the only accordion on the page will be the inactive one, which will take on the default value id 'default-accordion-1' as shown on line 92. I feel as though i've just said the work 'accordion' 3 million times,...

2020-11-11 13:37 UTC, GemTay reviewed
quick explanation, any better solution ideas welcome :)

2020-11-11 13:40 UTC, GemTay commented
Evidence of unique accordion id's 
![image](https://user-images.githubusercontent.com/18176021/98818393-690f5580-2423-11eb-968b-439ef3c385ad.png)

2020-11-11 15:04 UTC, SeemaMenon submitted a review, later dismissed

2020-11-11 16:07 UTC, cooperaj requested changes
If there are only ever 2 then this entire solution can just be changed to a hardcoded -1 and -2

Even is -1 is missing we have still fullfilled the HTML requirement that id's be unique.

2020-11-11 16:10 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                            <div class="govuk-accordion" data-module="govuk-accordion" id="accordion-default-{{ accordion_counter }}" data-opentext="{% trans %}Open all{% notes %}Accordion label{% en
```suggestion
                            <div class="govuk-accordion" data-module="govuk-accordion" id="accordion-default-1" data-opentext="{% trans %}Open all{% notes %}Accordion label{% endtrans%}" data-closetext="{% trans %}Close all{% notes %}Accordion label{% endtrans %}" data-sectiontext="{% trans %}section{% notes %}Accordion label{% endtrans %}">
```

2020-11-11 16:10 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                                            {{ include('@actor/partials/check-code-details.html.twig', {'id_counter': id_counter }) }}
```suggestion
                                            {{ include('@actor/partials/check-code-details.html.twig', {'id_counter': 1 }) }}
```

2020-11-11 16:10 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                            <div class="govuk-accordion" data-module="govuk-accordion" id="accordion-default-{{ accordion_counter }}" data-opentext="{% trans %}Open all{% notes %}Accordion label{% en
```suggestion
                            <div class="govuk-accordion" data-module="govuk-accordion" id="accordion-default-2" data-opentext="{% trans %}Open all{% notes %}Accordion label{% endtrans%}" data-closetext="{% trans %}Close all{% notes %}Accordion label{% endtrans %}" data-sectiontext="{% trans %}section{% notes %}Accordion label{% endtrans %}">
```

2020-11-11 16:10 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                                        {{ include('@actor/partials/check-code-details.html.twig', {'id_counter': id_counter }) }}
```suggestion
                                        {{ include('@actor/partials/check-code-details.html.twig', {'id_counter': 2 }) }}
```

2020-11-11 16:10 UTC, cooperaj commented
Unless I'm misunderstanding.

2020-11-11 16:52 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                            <div class="govuk-accordion" data-module="govuk-accordion" id="accordion-default-{{ accordion_counter }}" data-opentext="{% trans %}Open all{% notes %}Accordion label{% en
Yeah this makes sense. I guess my only concern is for the scenario where the accordion-default-1 is missing, would this. confuse screen readers as the accordion id would start at 2? @johnnolan any thoughts?

2020-11-11 16:53 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                                            {{ include('@actor/partials/check-code-details.html.twig', {'id_counter': id_counter }) }}
I'll still need to keep this id as a counter because we don't know how many codes a user has

2020-11-12 14:58 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/check-access-codes.html.twig
> +                                            {{ include('@actor/partials/check-code-details.html.twig', {'id_counter': id_counter }) }}
ah. my bad. I missed the reasoning for that

2020-11-12 14:58 UTC, cooperaj approved these changes

2020-11-12 15:57 UTC, merged