Uml 1104 codes content change
ministryofjustice/opg-use-an-lpa pull request #633
Opened 2020-11-27 14:30 UTC by cooperaj

# Purpose
Adds additional textual context to viewer code names for accessibility reasons

Fixes UML-1104

## Approach
Uses the govuk design systems accordion subtitle field to provide additional information. In order to get the date formatted correctly I had to play around with the LpaExtension and it's date handling.

I also fixed up the database seeding which was actually breaking fresh development environments with bad data.

## Learning
There're some dark corners of our app that need some TLC. For instance, creation timestamps against records in the database use a different format to basically every other date we store.

## Checklist

* [x] I have performed a self-review of my own code
* [ ] ~I have added relevant logging with appropriate levels to my code~
* [ ] ~I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant~
* [x] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] The product team have tested these changes

2020-11-27 15:20 UTC, GemTay commented on service-front/app/src/Common/src/Service/Lpa/ViewerCodeService.php
> +                new DateTime($code['Expires']) >= (new DateTime('now'))->setTime(23, 59, 59)
How come we compare the code expiry to the end of the current day? Is it so that codes expire 30 days after they were created, regardless of the time of day? If so we'll have to do the same comparison in the checkAccessCodesHandler so that the number of active codes displayed on the dashboard matches the number on the check access codes page

2020-11-27 15:22 UTC, cooperaj commented on service-front/app/src/Common/src/Service/Lpa/ViewerCodeService.php
> +                new DateTime($code['Expires']) >= (new DateTime('now'))->setTime(23, 59, 59)
I'm guessing so, I just tidied it up though

2020-11-27 15:26 UTC, GemTay commented on service-front/web/src/scss/lpa.scss
> -$govuk-typography-use-rem: false;
This was added by john to fix the bug that users were seeing on iOS 10.3 Safari, maybe best to keep it?

2020-11-27 15:27 UTC, GemTay commented on service-front/web/src/scss/lpa.scss
> -@import "../../node_modules/govuk-frontend/govuk/core/all";
How come this was removed?

2020-11-27 15:27 UTC, GemTay requested changes
Few queries

2020-11-27 16:19 UTC, cooperaj commented on service-front/web/src/scss/lpa.scss
> -@import "../../node_modules/govuk-frontend/govuk/core/all";
Complex reasons. I guess I need to run this and the above past you and John. Monday?

Briefly, because of the build order of things, and that gds.css is included already (which contains all the above imports anyway) it was subtly breaking accordions with odd padding and margin values.

2020-11-27 16:23 UTC, cooperaj commented on service-front/web/src/scss/lpa.scss
> -$govuk-typography-use-rem: false;
See below :)

2020-11-30 12:48 UTC, GemTay commented on service-front/app/src/Common/src/Service/Lpa/ViewerCodeService.php
> +                new DateTime($code['Expires']) >= (new DateTime('now'))->setTime(23, 59, 59)
@cooperaj No problem - I just checked and replicated the issue locally, I'll raise a bug ticket, as if a code is expiring on the current day, the dashboard displays the LPA as having 1 active code, however when you then click to check access codes, the code is in the inactive section. So theres an inconsistency in the code

2020-11-30 12:49 UTC, cooperaj commented on service-front/app/src/Common/src/Service/Lpa/ViewerCodeService.php
> +                new DateTime($code['Expires']) >= (new DateTime('now'))->setTime(23, 59, 59)
Assign it straight to me. I've already started work on the fix :)

2020-11-30 12:49 UTC, GemTay commented on service-front/web/src/scss/lpa.scss
> -@import "../../node_modules/govuk-frontend/govuk/core/all";
Makes sense 👍

2020-11-30 12:50 UTC, GemTay submitted a review, later dismissed

2020-11-30 12:50 UTC, cooperaj commented on service-front/app/src/Common/src/Service/Lpa/ViewerCodeService.php
> +                new DateTime($code['Expires']) >= (new DateTime('now'))->setTime(23, 59, 59)
Spent Friday refactoring all this stuff into a ViewerCode object so we don't spread this kind of thing about.

2020-11-30 17:23 UTC, cooperaj commented on service-front/web/src/scss/lpa.scss
> -$govuk-typography-use-rem: false;
@johnnolan this need looking at?

2020-12-01 10:41 UTC, johnnolan commented on service-front/web/src/scss/lpa.scss
> -$govuk-typography-use-rem: false;
@cooperaj that needs to stay so we can support our use of the specific components and browser bugs unfortunately.

2020-12-01 15:10 UTC, johnnolan commented on service-front/web/src/scss/lpa.scss
> -$govuk-typography-use-rem: false;
After chatting with @cooperaj I am happy for this to be removed. The main place we care about this being set is here https://github.com/ministryofjustice/opg-use-an-lpa/blob/2443a622a600e9f5787714095330da462e45053a/service-front%2Fweb%2Fsrc%2Fgds.scss which removes the rems correctly for the iOS bug

2020-12-01 17:36 UTC, andrewpearce-digital approved these changes
docker-compose.yml
service-api/docker/seeding/start.sh
service-api/seeding/dynamodb.py

All these look good to me. Someone else should approve the other files.

2020-12-01 17:48 UTC, merged