Changes to add the pages for UML-1161, 1162 and 1163
ministryofjustice/opg-use-an-lpa pull request #650
Opened 2020-12-18 16:50 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1161
https://opgtransform.atlassian.net/browse/UML-1162
https://opgtransform.atlassian.net/browse/UML-1163

Fixes UML-1161, UML-1162, UML-1163

## Approach

Just UI changes to add the twigs templates and the corresponding handlers.
The whole journey will only be complete and can be tested when the API changes for the data match is done[another ticket]
Behat UI and integration tests pending on check answers scenarios

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2020-12-22 10:58 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/CannotFindLpaHandler.php
> +
These new pages dont need handlers, since the handlers aren't doing anything apart from rendering the page. You can remove the handlers and just render the twig files in the check answers handler based off the business logic of checking the data

2020-12-22 11:05 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +                return $this->handlePost($request, $this->data);
You dont need to pass $this->data into the post request, as its a public class member so it can be accessed from anywhere in the class

2020-12-22 11:06 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +        $user = $this->getUser($request);
$this->user is already defined in the class

2020-12-22 11:09 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +            if (!is_null($lpaData)) {
all of this logic should be handled by a new function in the LpaService

2021-01-07 09:31 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/cannot-find-lpa.html.twig
> +                    <p class="govuk-body">{% trans %} This could be because the information you entered does not match the information we hold about the LPA.{% endtrans %}</p>
Leading spaces should be removed. There are a few of these dotted about

2021-01-07 09:36 UTC, cooperaj requested changes

2021-01-07 09:36 UTC, cooperaj commented on service-front/app/features/actor-activation-key-sent-confirmation.feature
> +@actor @activationKeySentConfirmation
All these features need rolling into a single feature file. Which is "Adding an older lpa" There is a good one to base on in the API side

2021-01-07 09:37 UTC, cooperaj commented on service-front/app/features/actor-activation-key-sent-confirmation.feature
> +@actor @activationKeySentConfirmation
Probably as a part of the UML-1216 ticket

2021-02-01 10:41 UTC, SeemaMenon commented
Not needed anymore...as pages merged with uml-1216-feature branch

2021-02-01 10:41 UTC, closed without merging