WIP: Upgraded NPM packages
ministryofjustice/opg-use-an-lpa pull request #654
Opened 2021-01-04 10:02 UTC by johnnolan

# Purpose

Upgrade NPM dependencies that are out of date in the service-front/web container

Fixes UML-1219

## Approach

Ran `npm-upgrade` and updated as appropriate.

## Learning

None

## Checklist

* [ ] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-01-11 09:06 UTC, cooperaj requested changes
Looks good. Two tweaks

2021-01-11 09:06 UTC, cooperaj commented on service-front/web/webpack.pdf.common.js
> +              url: false,
Can't quite  decide eh?

2021-01-11 09:06 UTC, cooperaj commented on service-front/web/webpack.pdf.js
> +              url: false,
And again

2021-01-11 09:11 UTC, johnnolan commented on service-front/web/webpack.pdf.common.js
> +              url: false,
lol good spot! Sorted!

2021-01-11 09:14 UTC, cooperaj approved these changes

2021-01-11 14:25 UTC, merged

2021-01-14 11:14 UTC, cooperaj commented
oops, this is breaking local dev envs when using the dockerfile. yay