Changed healthcheck endpoint used for sirius_api and changed a key in…
ministryofjustice/opg-use-an-lpa pull request #672
Opened 2021-01-28 05:57 UTC by SeemaMenon

… the json return

# Purpose

https://opgtransform.atlassian.net/browse/UML-1243

Fixes UML-1243

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-01-28 16:53 UTC, cooperaj requested changes
Quick fix and looks good

2021-01-28 16:53 UTC, cooperaj commented on service-api/app/src/App/src/Handler/HealthcheckHandler.php
> +        } catch (GuzzleException $ge) {
This class shouldn't be aware that Guzzle is being used. There is a better exception to use in this case.
I think the possibility is that it either an ApiException or a ClientExceptionInterface would be thrown so maybe better to leave it as an Exception.

2021-01-28 17:31 UTC, cooperaj commented on service-api/app/src/App/src/Handler/HealthcheckHandler.php
> +            if ($response->getStatusCode() === 200) {
Mmm. Thinking about it we may need to check to see the output of the healthcheck. I'm fairly certain the API returns 200 for pretty much everything and only an error when a genuine error is encountered on their end (i.e. it's not fully RESTful).

Going forward either way it's best to use StatusCodeInterface::STATUS_OK instead of magic numbers.

2021-01-28 17:37 UTC, SeemaMenon commented on service-api/app/src/App/src/Handler/HealthcheckHandler.php
> +            if ($response->getStatusCode() === 200) {
Mmm...ok, changed on both checks.

2021-01-28 17:40 UTC, cooperaj reviewed
Looks good, just need to check the api healthcheck endpoint doesn't return a 200 response if they fail (like I think they do)

2021-01-28 17:43 UTC, SeemaMenon commented on service-api/app/src/App/src/Handler/HealthcheckHandler.php
> +        } catch (GuzzleException $ge) {
Changed.

2021-01-28 17:45 UTC, SeemaMenon commented
> Looks good, just need to check the api healthcheck endpoints don't return a 200 response if they fail (like I think they do)

<img width="583" alt="Screenshot 2021-01-28 at 17 42 30" src="https://user-images.githubusercontent.com/6483585/106177379-5a1d8100-6190-11eb-86c6-f4629b550372.png">

2021-01-28 17:48 UTC, cooperaj commented
I believe that this won't work. It's quite possible that the sirius_api and lpa_codes_api healthcheck endpoints will return a 200 response even if they have failed. The reason for the failure will be a part of the body of the response. I think this because that's how the rest of the endpoints work. The "not found" response for an lpa code is a reponse with 200 status code and body of "{actor: null}".

2021-02-01 10:15 UTC, SeemaMenon commented on service-api/app/src/App/src/Handler/HealthcheckHandler.php
> +            "sirius_api" => $this->checkApiEndpoint(),
@cooperaj , @GemTay  - OK with lpa_api?

2021-02-18 11:47 UTC, cooperaj approved these changes

2021-02-18 15:21 UTC, merged