Uml 1222 requesting activation key within 14 days
ministryofjustice/opg-use-an-lpa pull request #719
Opened 2021-02-23 14:44 UTC by GemTay

# Purpose

Displays a different page to users who request an activation key again within 14 days, to inform them of when their letter should arrive by.

Fixes UML-1222

## Approach

Setup date comparison on the code created date returned from lpa codes api. If the difference is within 2 weeks, it throws an exception and attaches the created date as additional data on the exception. I then added a new switch case to the AddOlderLpa and CheckYourAnswersHandler to match the new exception message, and render the new twig file.

## Checklist

* [x] I have performed a self-review of my own code
* [x] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [x] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-02-23 17:22 UTC, cooperaj commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +                'Activation key created within the last 14 days already exists for actor {actorId} on LPA {lpaId}',
```suggestion
                'Activation key recently created for actor {actorId} on LPA {lpaId}',
```

2021-02-23 17:26 UTC, cooperaj commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +        if ((int) $createdDate->diff(new DateTime(), true)->format('%a') <= 14) {
Mmm. I'm wondering if we need the distinction between 'you have a key' and 'you have a recent key' at this point. What would happen if we pass the created date back with both types of response. Would it be something we could map on the front end. The result is the same effectively (no progress) but we just change what message we show.

2021-02-23 17:29 UTC, cooperaj commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +        if ((int) $createdDate->diff(new DateTime(), true)->format('%a') <= 14) {
Specifically we'd be able to just say "is the date within 14 days" in the Handler and show one view or another. Alternatively you could shift it right and return a different response type to the handler from the service.

2021-02-23 17:33 UTC, cooperaj commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +        }
May need to return from the catch and add a forced test fail at the end of the method in case the exception isn't thrown (though you may get a 'no assertions made' error

2021-02-23 17:33 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +        if ((int) $createdDate->diff(new DateTime(), true)->format('%a') <= 14) {
Yeah thats totally doable and I agree, probably better! I was just sticking to the format of the API giving different responses for different cases but this case it seems kinda dumb. We could pass the created date back and just do the date comparison in the switch case in the CheckYourAnswersHandler

2021-02-23 17:37 UTC, cooperaj commented on service-front/app/features/context/UI/LpaContext.php
> +            if ((int) $this->codeCreatedDate->diff(new DateTime(), true)->format('%a') <= 14) {
My concert for this check is that `$this->codeCreatedDate` may not exist depending on step call order.  The preceding check specifically checks for a null which would always work.

2021-02-24 15:09 UTC, cooperaj requested changes
One change and it's ready to go 👍

2021-02-24 15:09 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +                    $createdDate = DateTime::createFromFormat('Y-m-d', $result->getData()['activation_key_created']);
Can we move the body of this case to a new private method? Will help reduce the complexity of the code.

2021-02-24 15:49 UTC, cooperaj submitted a review, later dismissed
LGTM 👍

2021-02-24 16:17 UTC, cooperaj approved these changes

2021-02-24 16:19 UTC, merged