Uml 1251 - Send email confirmation on requesting activation key
ministryofjustice/opg-use-an-lpa pull request #757
Opened 2021-03-05 08:32 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1251

Fixes UML-1251

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [X] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-03-05 09:33 UTC, cooperaj requested changes

2021-03-05 09:33 UTC, cooperaj commented on service-front/app/features/actor-add-an-older-lpa.feature
> +#  @ui @integration
Commenting this means the test isn't actually running

2021-03-05 09:33 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +                    $this->emailClient->sendActivationKeyRequestConfirmationEmail(
The sending of letters should be done in the api side. The credentials have now been added but all this should be wrapped up as a part of the code in that service now. 

At some point we'll be removing all notify stuff from the frontend.

2021-03-05 09:33 UTC, cooperaj commented on service-front/app/src/Common/src/Service/Email/EmailClient.php
> +    public function sendActivationKeyRequestConfirmationEmail(
This class needs copying into the api service and alterations made there.

2021-03-05 10:07 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +                    $this->emailClient->sendActivationKeyRequestConfirmationEmail(
Created new improvement ticket for the logic shift exercise: 
https://opgtransform.atlassian.net/browse/UML-1315

2021-03-05 10:08 UTC, SeemaMenon commented on service-front/app/src/Common/src/Service/Email/EmailClient.php
> +    public function sendActivationKeyRequestConfirmationEmail(
Created new improvement ticket for the logic shift exercise:
https://opgtransform.atlassian.net/browse/UML-1315

2021-03-05 13:50 UTC, SeemaMenon commented on service-front/app/features/actor-add-an-older-lpa.feature
> +#  @ui @integration
Oh..that's a mistake! Sorry...

2021-03-05 16:48 UTC, GemTay requested changes

2021-03-05 16:48 UTC, GemTay commented on service-front/app/src/Common/src/Service/Email/EmailClient.php
> +                'reference_number' => $referenceNumber,
in notify, the reference number attribute is written as "ref", so i dont know if this wouldnt work?

2021-03-05 17:17 UTC, SeemaMenon commented on service-front/app/src/Common/src/Service/Email/EmailClient.php
> +                'reference_number' => $referenceNumber,
The actual template is not yet created I guess. Uchenna has just created placeholders and passed me the id's for usage in code. Sarah is aware and hence UAT pending.

2021-03-05 17:19 UTC, SeemaMenon commented on service-front/app/src/Common/src/Service/Email/EmailClient.php
> +                'reference_number' => $referenceNumber,
I don't have access to notify ATM, not able to receive the text message code.

2021-03-08 15:02 UTC, GemTay commented on service-front/app/src/Common/src/Service/Email/EmailClient.php
> +                'reference_number' => $referenceNumber,
The templates are created, thats what the template ID represents, so just change the attribute name to 'ref' so it's assigned the value correctly in the templates

2021-03-09 12:22 UTC, SeemaMenon commented on service-front/app/src/Common/src/Service/Email/EmailClient.php
> +                'reference_number' => $referenceNumber,
@GemTay  -  Got you on this. Thanks for pointing this out.

@andrewpearce-digital kindly updated the reference on the templates. The functionality works now on testing.

Request a review again please.

2021-03-09 13:39 UTC, GemTay approved these changes

2021-03-10 09:24 UTC, cooperaj approved these changes

2021-03-10 09:37 UTC, merged