UML-1256 - moved the status check to api side and returns only LPA whose status meets
ministryofjustice/opg-use-an-lpa pull request #841
Opened 2021-04-08 17:38 UTC by SeemaMenon

# Purpose
https://opgtransform.atlassian.net/browse/UML-1256

Fixes UML-1256

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-04-15 09:37 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/IsValidLpa.php
> +        if (
this login can be simplified to `return strtolower($lpa['status']) === self::LPA_REGISTERED || strtolower($lpa['status']) === self::LPA_CANCELLED`

2021-04-15 09:45 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/LpaService.php
> +        return [];
how come you return an empty array instead of null?

2021-04-15 09:50 UTC, GemTay commented on service-api/app/test/AppTest/Service/Lpa/IsValidLpaTest.php
> +            $this->isValidLpaProphecy->reveal()
You only need to pass the logger into the constructor here

2021-04-15 09:52 UTC, GemTay commented on service-api/app/test/AppTest/Service/Lpa/IsValidLpaTest.php
> +        $this->assertEquals(true, $result);
using assertEquals is fine here, but you could use the assertTrue and assertFalse methods too :)

2021-04-15 09:55 UTC, GemTay commented on service-api/app/test/AppTest/Service/Lpa/LpaServiceTest.php
> +        //
empty comment to be removed

2021-04-15 10:00 UTC, GemTay commented on service-front/app/features/actor-view-lpa.feature
> +      | Revoked |This LPA has been revoked |
Since you're only passing 1 example, remove the examples and have the status in the step definition `When I request to view an LPA which status is revoked`

2021-04-15 10:03 UTC, GemTay commented on service-front/app/features/context/UI/LpaContext.php
> +    public function theRevokedLPADetailsAndMessageAreNotDisplayed($status, $message)
i cant see this step in the feature file?

2021-04-15 10:05 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/ViewLpaSummaryHandler.php
> +        if (count($lpaData) === 0) {
if you are returning an empty array in the api, this if statement should be `if (empty($lpaData))`

2021-04-15 10:16 UTC, GemTay requested changes
few small changes :)

2021-04-15 19:18 UTC, SeemaMenon reviewed
> few small changes :)

All done :)

2021-04-16 13:45 UTC, GemTay commented on service-api/app/features/actor-view-lpa.feature
> +      | Revoked   |
again, don't use examples where you are only providing 1

2021-04-16 13:49 UTC, GemTay commented on service-front/app/features/context/Integration/LpaContext.php
> +        if ($status === "Revoked") {
you're no longer passing in revoked as an example in the feature file so this isnt needed

2021-04-16 13:50 UTC, GemTay commented on service-front/app/features/context/UI/LpaContext.php
> +        if($status === 'Revoked'){
same here

2021-04-16 13:51 UTC, GemTay commented on service-front/app/features/context/Integration/AccountContext.php
> +    public function theRevokedLPADetailsAndMessageAreNotDisplayed($status, $message)
this step definition doesnt match the feature file?

2021-04-16 13:52 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/ViewLpaSummaryHandler.php
> +        if (count($lpaData) === 0) {
this still needs changing @SeemaMenon

2021-04-16 13:53 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/ViewLpaSummaryHandler.php
> +        }
tag this handler with @codeCoverageIgnore to get rid of these codecov warnings

2021-04-20 08:40 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/ViewLpaSummaryHandler.php
> +        if (count($lpaData) === 0) {
That gives me an error when tried with  empty function. Hence kept it as it is ! Would you mind having a look please

2021-04-20 13:20 UTC, SeemaMenon commented on service-front/app/features/context/Integration/AccountContext.php
> +    public function theRevokedLPADetailsAndMessageAreNotDisplayed($status, $message)
got you, corrected!

2021-04-20 13:26 UTC, SeemaMenon commented on service-front/app/features/context/Integration/LpaContext.php
> +        if ($status === "Revoked") {
That's right. But I am using same step definition for the test step below [for the revoked case]. Attached snapshot below:
<img width="780" alt="Screenshot 2021-04-20 at 14 24 39" src="https://user-images.githubusercontent.com/6483585/115403455-5116db80-a1e4-11eb-895f-4fe8cfa3182a.png">

2021-04-20 13:26 UTC, SeemaMenon commented on service-front/app/features/context/UI/LpaContext.php
> +        if($status === 'Revoked'){
same explanation as above, if that makes sense.

2021-04-20 13:29 UTC, SeemaMenon commented on service-api/app/features/actor-view-lpa.feature
> +      | Revoked   |
Amended..

2021-04-21 09:17 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/LpaService.php
> +        return [];
Theres a codecov warning here, so it looks like you need to add a test to the LpaServiceTest for the case where IsLpaValid returns an empty array

2021-04-21 10:01 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/ViewLpaSummaryHandler.php
> +        }
This redirect needs to be in place for the other pages too, eg code make and check access codes

2021-04-21 10:02 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/ViewLpaSummaryHandler.php
> +use Mezzio\Flash\FlashMessagesInterface;
these imports arent needed

2021-04-21 11:56 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/ViewLpaSummaryHandler.php
> +        }
Done now :)

2021-04-21 12:15 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Lpa/LpaService.php
> +        return [];
Ok, added in now.

2021-04-21 12:15 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/ViewLpaSummaryHandler.php
> +use Mezzio\Flash\FlashMessagesInterface;
my bad, clean up done...

2021-04-22 10:49 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/ViewLpaSummaryHandler.php
> +        if (count($lpaData) === 0) {
This is changed now

2021-04-26 09:31 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/IsValidLpa.php
> +        $this->logger = $logger;
this logger isnt currently being used, so maybe add in a log message for when the status is something other than registered or cancelled

2021-04-26 09:37 UTC, GemTay commented on service-front/app/features/context/UI/LpaContext.php
> +            $this->lpa->donor->salutation . ' ' . $this->lpa->donor->firstname . ' ' . $this->lpa->donor->middlenames . ' ' . $this->lpa->donor->surname
The donor salutation isnt displayed on the dashboard, so can be removed here

2021-04-26 09:39 UTC, GemTay requested changes
couple of things

2021-04-26 11:34 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Lpa/IsValidLpa.php
> +        $this->logger = $logger;
ok

2021-04-26 15:48 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/IsValidLpa.php
> +                ['status' => $lpa['status']]
We need to have a bit more context around which LPA this is, so maybe something like "LPA with id {lpaUid} has an invalid status of {status}" - and change the log level to notice

2021-04-26 15:54 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Lpa/IsValidLpa.php
> +                ['status' => $lpa['status']]
OK, done.

2021-04-26 16:04 UTC, GemTay approved these changes
Nice!

2021-04-26 16:24 UTC, merged