Uml 1302 : content changes on activation key sent page
ministryofjustice/opg-use-an-lpa pull request #852
Opened 2021-04-20 17:21 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1302

Fixes UML-1302

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-04-22 12:50 UTC, GemTay commented on service-front/app/features/context/UI/LpaContext.php
> +        $this->ui->assertElementContainsText('h1', 'We’re posting you an activation key');
The apostrophe needs to still be escaped with the backslash, also what character have you replaced the apostrophe with? It looks different? Probably best to change it back to the standard one

2021-04-22 13:19 UTC, GemTay commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +# Need to switch OPG & LPA in the translation
does this comment need to be kept here?

2021-04-22 13:19 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/send-activation-key-confirmation.html.twig
> +                            {% trans %}We’re posting you an activation key{% endtrans %}
strange apostrophe again

2021-04-22 13:21 UTC, GemTay requested changes
just a few queries

2021-04-22 14:02 UTC, SeemaMenon commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +# Need to switch OPG & LPA in the translation
Am not sure about this? Not introduced by me...

2021-04-22 14:03 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/send-activation-key-confirmation.html.twig
> +                            {% trans %}We’re posting you an activation key{% endtrans %}
Wonder how it keeps changing. :(

2021-04-22 16:01 UTC, SeemaMenon commented on service-front/app/features/context/UI/LpaContext.php
> +        $this->ui->assertElementContainsText('h1', 'We’re posting you an activation key');
done

2021-04-26 09:45 UTC, GemTay approved these changes

2021-04-26 09:56 UTC, merged