Uml 1200 : dashboard grey panels
ministryofjustice/opg-use-an-lpa pull request #854
Opened 2021-04-22 18:20 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1200

Fixes UML-1200

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-04-26 13:30 UTC, GemTay commented on service-api/seeding/dynamodb.py
> +        'UserId': 'bf9e7e77-f283-49c6-a79c-65d5d309ef77'
are these seeding changes intended to be merged?

2021-04-26 13:42 UTC, GemTay requested changes
Somethings still not working correctly, I've debugged and checked that the 2 "Babara Suzanne Gilson" LPAs are grouped together correctly in the sorting & grouping functions, so somewhere is breaking them apart on the UI
![image](https://user-images.githubusercontent.com/18176021/116092254-8d8f7f00-a69d-11eb-9aef-799ecae02a1a.png)

2021-04-26 15:37 UTC, SeemaMenon commented on service-api/seeding/dynamodb.py
> +        'UserId': 'bf9e7e77-f283-49c6-a79c-65d5d309ef77'
yes, to have multiple LPA's added for the user with different statuses.

2021-04-28 12:40 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig
> +        <dd class="govuk-summary-list__value govuk-!-padding-top- govuk-!-padding-bottom-4 govuk-!-margin-bottom-0">
`govuk-!-padding-top-` is missing a number

2021-04-30 09:26 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/partials/lpa-details.html.twig
> +        <dd class="govuk-summary-list__value govuk-!-padding-top- govuk-!-padding-bottom-4 govuk-!-margin-bottom-0">
added now

2021-04-30 12:13 UTC, GemTay approved these changes

2021-04-30 14:13 UTC, merged