Uml 1345:  activation key already exists page modified
ministryofjustice/opg-use-an-lpa pull request #910
Opened 2021-05-20 05:14 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1345

Fixes UML-1345

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [X] I have added tests to prove my work
* [X] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-05-20 14:41 UTC, SeemaMenon commented on service-api/app/features/actor-add-an-older-lpa.feature
> -
We don't need showing the date by when the post would be arriving any more. This scenario is redundant as per this ticket, hence removed. 

Irrespective of the request  for key was made within 14 days or months back, we would now show the user the same content.

2021-05-21 08:56 UTC, cooperaj commented on service-api/app/features/context/Integration/LpaContext.php
> +            assertEquals(['activation_key_created' => $createdDate,'donor_name' => $this->userFirstname ." " . $this->userSurname ,'lpa_type' => "hw"], $ex->getAdditionalData());
```suggestion
            assertEquals(['activation_key_created' => $createdDate, 'donor_name' => $this->userFirstname . " " . $this->userSurname , 'lpa_type' => "hw"], $ex->getAdditionalData());
```

2021-05-21 08:56 UTC, cooperaj commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +                    'lpa_type'   => $lpaMatchResponse->getData()['caseSubtype']
```suggestion
                    'activation_key_created' => $hasActivationCode->format('Y-m-d'),
                    'donor_name' => 
                        $lpaMatchResponse->getData()['donor']['firstname'] . " "
                        . $lpaMatchResponse->getData()['donor']['middlenames'] . " "
                        . $lpaMatchResponse->getData()['donor']['surname'],
                    'lpa_type'   => $lpaMatchResponse->getData()['caseSubtype']
```

2021-05-21 08:56 UTC, cooperaj commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +                    'donor_name' => $lpa->getData()['donor']['firstname'] . " " . $lpa->getData()['donor']['middlenames'] . " " . $lpa->getData()['donor']['surname'],
```suggestion
                    'donor_name' => 
                        $lpa->getData()['donor']['firstname'] . " " 
                        . $lpa->getData()['donor']['middlenames'] . " " 
                        . $lpa->getData()['donor']['surname'],
```

2021-05-21 08:56 UTC, cooperaj commented on service-front/app/features/context/UI/LpaContext.php
> +                                    'donor_name' => ($this->lpaData['lpa'])->donor->firstname . " " . ($this->lpaData['lpa'])->donor->middlenames . " " . ($this->lpaData['lpa'])->donor->surname,
```suggestion
                                    'donor_name' => 
                                        ($this->lpaData['lpa'])->donor->firstname . " ""
                                        . ($this->lpaData['lpa'])->donor->middlenames . " " 
                                        . ($this->lpaData['lpa'])->donor->surname,
```

2021-05-21 08:56 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +        if (!empty((int) $createdDate)) {
Because this function expects a string value for the $createdDate I don't know if it's worth checking at all now?

Regardless of what date gets passed in, as long as it's a valid date (which it will be as thats what we store in the DB) we show the response. It certainly doesn't make sense to cast a Datetime into an int for an empty check.

2021-05-21 13:02 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +        if (!empty((int) $createdDate)) {
Makes sense on second thought. So I am removing this additional check and function and rendering the page  in the switch loop when it matches the 'HAS_ACTIVATION_KEY'

2021-05-24 10:20 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +        if (!empty((int) $createdDate)) {
we're checking whether the created date is null on line 166 above, so this check isnt needed here

2021-05-24 10:22 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +                        . $lpaMatchResponse->getData()['donor']['middlenames'] . " "
If the donor middlenames field is blank, then wouldn't this put a double space between the first and last name?

2021-05-24 10:25 UTC, GemTay commented on service-front/app/features/context/Integration/LpaContext.php
> +                                'lpa_type' => ' '
I think it'd be better to use the lpa data here rather than blank strings: $this->lpa->donor->firstname etc to check the strings are concatenated correctly

2021-05-24 10:28 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/already-have-activation-key.html.twig
> +                    <h1 class="govuk-heading-xl">{% trans %}We've already sent you an activation key for this LPA{% endtrans %}</h1>
Make the html_title the same text as this heading so that we can keep track of it more easily in google analytics

2021-05-24 10:30 UTC, GemTay requested changes
looking good, just a few changes to be made

2021-05-24 12:05 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +                        . $lpaMatchResponse->getData()['donor']['middlenames'] . " "
Good catch...introduced a preg_replace to avoid this now.

2021-05-24 12:20 UTC, SeemaMenon commented on service-front/app/features/context/Integration/LpaContext.php
> +                                'lpa_type' => ' '
ok

2021-05-24 12:21 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/already-have-activation-key.html.twig
> +                    <h1 class="govuk-heading-xl">{% trans %}We've already sent you an activation key for this LPA{% endtrans %}</h1>
Makes sense, changed now.

2021-05-24 13:32 UTC, SeemaMenon commented
@GemTay  - could you do a review once again please?

2021-05-24 14:52 UTC, GemTay approved these changes

2021-05-24 14:54 UTC, cooperaj commented on service-api/app/features/context/Integration/LpaContext.php
> +                    'lpa_type' => "hw",
```suggestion
                    'lpa_type' => 'hw',
```

2021-05-24 14:54 UTC, cooperaj commented on service-api/app/features/context/Integration/LpaContext.php
> +                    'lpa_type' => "hw",
Single quotes unless interpolation is needed.

2021-05-24 14:54 UTC, cooperaj commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +                    'donor_name' => preg_replace(
Whats the purpose of the preg_replace?

2021-05-24 14:56 UTC, cooperaj commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +                        . $lpaMatchResponse->getData()['donor']['middlenames'] . " "
The pattern we've used elsewhere in the codebase for this is an array_filter with no conditions over an array containing the three name types. I'm not sure this method is better. Also, (at least in the above) please use single quotes.

2021-05-24 15:24 UTC, merged

2021-05-24 15:25 UTC, SeemaMenon commented on service-api/app/features/context/Integration/LpaContext.php
> +                    'lpa_type' => "hw",
Sorry @cooperaj , saw this late. Shall correct in my following ticket 1375

2021-05-24 15:28 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +                    'donor_name' => preg_replace(
<img width="809" alt="Screenshot 2021-05-24 at 16 26 34" src="https://user-images.githubusercontent.com/6483585/119370125-da6e7180-bcac-11eb-8a6b-717b4011c5c9.png">