Uml 1466 update link for surveymonkey
ministryofjustice/opg-use-an-lpa pull request #918
Opened 2021-05-27 15:27 UTC by lukejolliffe

# Purpose

Update the survey monkey links on Use and View pages

Fixes UML-1466

## Checklist

* [ x] I have performed a self-review of my own code
* [ ] I have added tests to prove my work
* [ x] I have added welsh translation tags and updated translation files
* [ ] The product team have tested these changes

2021-05-27 15:29 UTC, cooperaj submitted a review, later dismissed

2021-05-27 15:38 UTC, GemTay requested changes

2021-05-27 15:38 UTC, GemTay commented on service-front/app/languages/cy/LC_MESSAGES/messages.po
> +#~ "Use-LPA\" target=\"_blank\">adborth</a> yn ein helpu i’w wella."
Just need to fix this

2021-05-28 09:23 UTC, lukejolliffe commented
view url: https://918uml1466upd.view-lasting-power-of-attorney.service.gov.uk/home
use url: https://918uml1466upd.use-lasting-power-of-attorney.service.gov.uk/home

2021-05-28 12:14 UTC, merged