1375- Allow users to generate a new activation key even if one already exists
ministryofjustice/opg-use-an-lpa pull request #922
Opened 2021-05-31 16:48 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1375

Fixes UML-1375

## Approach

Introduced a new handler [front]
Alterations in API flow for checks

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [ ] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-06-04 08:14 UTC, SeemaMenon commented
<img width="746" alt="Screenshot 2021-06-04 at 09 14 07" src="https://user-images.githubusercontent.com/6483585/120769720-4ce51a00-c515-11eb-8b61-087641b5f524.png">

2021-06-04 08:30 UTC, SeemaMenon commented
<img width="730" alt="Screenshot 2021-06-04 at 09 30 24" src="https://user-images.githubusercontent.com/6483585/120771797-8880e380-c517-11eb-9cfe-f0cabb4533a9.png">

2021-06-08 09:41 UTC, cooperaj requested changes

2021-06-08 09:41 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +                                'donorName' => implode(' ', array_filter(array_map('trim',$result->getData()['donor_name']))),
Why do we now flatten the name?

2021-06-08 09:41 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/CreateActivationKeyHandler.php
> +                case OlderLpaApiResponse::SUCCESS:
Will we ever get any other type of response?

2021-06-08 09:41 UTC, cooperaj commented on service-front/app/src/Common/src/Service/Lpa/AddOlderLpa.php
> +        array $userData
I'm uncertain as to why the parameter list was changed like this? Service classes should have pretty explicit parameters and should not accept unknowable arrays.

If a data object is required to reduce the parameter count to a sensible number then it needs to be an explicit value object with getters.

2021-06-08 14:29 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +                                'donorName' => implode(' ', array_filter(array_map('trim',$result->getData()['donor_name']))),
Only the necessary info to be shown on the page [such as lpa type and donor name] is added to the exception thrown back. The donor name passed to the handler is an array consisting firstname,  middlename and surname. This is joined in the front for rendering.

modified to 
'donorName' => (implode(' ', array_filter($result->getData()['donor_name']))),

2021-06-08 14:45 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/CreateActivationKeyHandler.php
> +                case OlderLpaApiResponse::SUCCESS:
Fair point. Answer is NO, will always be a SUCCESS response if it's got to this handler.

I am still inclined to keep the check below _if ($result->getResponse() == OlderLpaApiResponse::SUCCESS)_

Are you suggesting I don't need to?

2021-06-10 08:05 UTC, SeemaMenon commented on service-front/app/src/Common/src/Service/Lpa/AddOlderLpa.php
> +        array $userData
Was meant to be reverted, reverted now .

2021-06-14 09:16 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +        $lpaAndActorMatchResponse['lpa_type'] = $lpaMatchResponse->getData()['caseSubtype'];
`$lpaAndActorMatchResponse` is too long, change it to something shorter like `$actorMatch`

2021-06-14 09:20 UTC, GemTay commented on service-api/app/src/App/src/Service/Log/EventCodes.php
> +    public const OLDER_LPA_NEW_ACTIVATION_KEY = 'OLDER_LPA_NEW_ACTIVATION_KEY';
whats the purpose of this event code? We already have one for OLDER_LPA_SUCCESS that gets logged in the front

2021-06-14 09:32 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +                    $form->setData($data);
You could just use $this->data instead as it contains all the data?

2021-06-14 09:45 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +                $this->data['force_activation_key']
The flag isn't needed at this point, so i'd suggest setting it as an optional parameter in the AddOlderLpa class `bool $forceActivationKey = false`, and then don't pass it in here

2021-06-14 09:52 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/CreateActivationKeyHandler.php
> +    private function localisedLetterExpectedDate(\DateTimeInterface $date): string
This function is now copied in 2 classes, so its best to strip it out into its own class

2021-06-14 09:56 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/partials/create-activation-key.html.twig
> +        <div class="govuk-grid-column-three-quarters">
this div and the grid-row div arent needed, as you've used an include statement on the other template which already wraps/styles the content

2021-06-14 09:58 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/partials/create-activation-key.html.twig
> +{% block content %}
How come you've put this in a block? I dont think its needed

2021-06-14 10:01 UTC, GemTay commented on service-front/app/src/Common/src/Service/Lpa/AddOlderLpa.php
> -            'LPA with reference number {uId} not added because "{reason}"',
Why has part of this message been removed? Even if the user requests a key when they already have one, this message doesnt make sense now

2021-06-14 10:02 UTC, GemTay commented on service-front/app/test/ActorTest/Form/CreateNewActivationKeyTest.php
> +use Laminas\Form\Element\{Radio, Hidden};
Radio element class isnt used here

2021-06-14 10:02 UTC, GemTay commented on service-api/app/features/context/Acceptance/LpaContext.php
> +                'force_activation_key' => null
it shouldn't ever be null, right?

2021-06-14 10:04 UTC, GemTay commented on service-front/app/test/CommonTest/Service/Lpa/AddOlderLpaTest.php
> +                    'force_activation_key'      => null
shouldnt be null here too

2021-06-14 10:06 UTC, GemTay commented on service-front/app/test/CommonTest/Service/Lpa/AddOlderLpaTest.php
> +    public function allow_user_continue_to_generate_new_activation_key_even_if_actor_has_active_activation_key(): void
try to shorten this test name, its too long

2021-06-14 14:57 UTC, SeemaMenon commented on service-front/app/test/CommonTest/Service/Lpa/AddOlderLpaTest.php
> +    public function allow_user_continue_to_generate_new_activation_key_even_if_actor_has_active_activation_key(): void
OK, done.

2021-06-14 14:58 UTC, SeemaMenon commented on service-api/app/features/context/Acceptance/LpaContext.php
> +                'force_activation_key' => null
Shouldn't be. Changed to false.

2021-06-14 15:03 UTC, SeemaMenon commented on service-front/app/test/ActorTest/Form/CreateNewActivationKeyTest.php
> +use Laminas\Form\Element\{Radio, Hidden};
Removed

2021-06-14 15:25 UTC, SeemaMenon commented on service-front/app/src/Common/src/Service/Lpa/AddOlderLpa.php
> -            'LPA with reference number {uId} not added because "{reason}"',
Not sure, reverted now.

2021-06-14 15:39 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/partials/create-activation-key.html.twig
> +        <div class="govuk-grid-column-three-quarters">
That's true....   removed. Thanks Gemma.

2021-06-14 16:46 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +                    $form->setData($data);
Now that 'forceActivationKey' if removed from the argument list, YES makes perfect sense to use '$this->data'.

2021-06-14 16:55 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Log/EventCodes.php
> +    public const OLDER_LPA_NEW_ACTIVATION_KEY = 'OLDER_LPA_NEW_ACTIVATION_KEY';
So OLDER_LPA_SUCCESS wouldn't help distinguish if the request for key was made the first time or a repeat request. Hence new_activation_key and force_activation_key  event codes added to capture for the respective scenarios.[Something Jude was asking to be able to see metrics/logs for first time requests and repeated requests and Andrew recommended using specific event codes].

I wasn't exactly sure if the new code need adding in the front or api, but thought it was appropriate to have it at the api and used in _OlderLpaService_ under _requestAccessByLetter_ function

2021-06-14 16:58 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +        $lpaAndActorMatchResponse['lpa_type'] = $lpaMatchResponse->getData()['caseSubtype'];
Altered :)

2021-06-15 10:04 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/CreateActivationKeyHandler.php
> +    private function localisedLetterExpectedDate(\DateTimeInterface $date): string
Done

2021-06-16 15:02 UTC, GemTay commented on service-api/app/features/actor-add-an-older-lpa.feature
> +  Scenario: The user is given an option to generate a new key even if an activation key already exists
this test isnt needed for the API side since its a UI test

2021-06-16 15:22 UTC, GemTay commented on service-api/app/features/context/Integration/LpaContext.php
> +            'dob' => $dob->format('Y-m-d'),
`$this->userDob` is already a string in the format Y-m-d ready to use

2021-06-16 15:24 UTC, GemTay commented on service-api/app/features/context/Integration/LpaContext.php
> +        $codeExists->Created = $createdDate;
these 3 lines above aren't needed or being used

2021-06-16 15:45 UTC, GemTay commented on service-api/app/src/App/src/Service/Log/EventCodes.php
> +    public const OLDER_LPA_NEW_ACTIVATION_KEY = 'OLDER_LPA_NEW_ACTIVATION_KEY';
It makes sense for Jude to be able to see how many users are asking for a new activation code when they already have one, but thats just 1 extra case, so why is there 2 new event codes? Aren't they the same thing?

2021-06-16 15:48 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +    public function hasActivationCode(array $actorLpaDetails ): ?DateTime
why have the parameters been changed to an array? Better to be explicit

2021-06-16 15:50 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +            'Activation key exits for actor {actorId} on LPA {lpaId}',
```suggestion
            'Activation key exists for actor {actorId} on LPA {lpaId}',
```

2021-06-16 15:55 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +                'Requesting new access code letter for attorney {attorney} on LPA {lpa}',
I dont think this case needs an event code. Also I find it hard to distinguish between "Requesting new" and "Requesting another", as to me, both sentences imply you already had one in the first place. So i'd change this log message to just 'Requesting an access code letter for attorney {attorney} on LPA {lpa}'

2021-06-16 16:22 UTC, GemTay commented on service-front/app/features/context/Integration/LpaContext.php
> +use function Aws\boolean_value;
Needs removing

2021-06-16 16:23 UTC, GemTay commented on service-front/app/features/actor-add-an-older-lpa.feature
> +  @ui @integration
This scenario is only relevant for the UI context

2021-06-16 16:33 UTC, GemTay commented on service-front/app/features/context/Integration/LpaContext.php
> +        }
This step is missing some sort of assertion on the response

2021-06-16 16:39 UTC, GemTay commented on service-front/app/features/context/UI/LpaContext.php
> +        $this->ui->pressButton("Continue and ask for a new key");
```suggestion
        $this->ui->pressButton('Continue and ask for a new key');
```

2021-06-16 16:46 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/CreateActivationKeyHandler.php
> +    {
this curly bracket should be on the same line as the closed bracket above with a space inbetween

2021-06-16 16:52 UTC, GemTay commented on service-front/app/src/Common/src/Service/Log/EventCodes.php
> +    public const OLDER_LPA_NEW_ACTIVATION_KEY = 'OLDER_LPA_NEW_ACTIVATION_KEY';
I'd suggest keeping this event code to be logged when a user requests another key when they already has one. I think the wording of this one is better than OLDER_LPA_FORCE_ACTIVATION_KEY

2021-06-16 16:56 UTC, GemTay requested changes
Few more changes to be made

2021-06-16 16:56 UTC, GemTay commented on service-front/app/test/CommonTest/Service/Lpa/AddOlderLpaTest.php
> +        $data = [
i'd remove all this and just add false as a final parameter for the $sut to reduce the code length

2021-06-16 16:57 UTC, GemTay commented on service-front/app/src/Actor/src/Handler/CreateActivationKeyHandler.php
> +                case OlderLpaApiResponse::SUCCESS:
@SeemaMenon Indeed, no need for a switch statement if theres only 1 type of response

2021-06-17 10:16 UTC, SeemaMenon commented on service-api/app/features/actor-add-an-older-lpa.feature
> +  Scenario: The user is given an option to generate a new key even if an activation key already exists
Didn't mind removing them, were empty steps :)

2021-06-17 11:44 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +    public function hasActivationCode(array $actorLpaDetails ): ?DateTime
Aaah old code, put back to original format now.

2021-06-17 11:46 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +                'Requesting new access code letter for attorney {attorney} on LPA {lpa}',
All that matters is the event code for the metrics purpose here. So changed content :)

2021-06-17 11:54 UTC, SeemaMenon commented on service-front/app/features/context/Integration/LpaContext.php
> +use function Aws\boolean_value;
Why did I even put this...no clue. Removed.

2021-06-17 14:33 UTC, SeemaMenon commented on service-front/app/src/Common/src/Service/Log/EventCodes.php
> +    public const OLDER_LPA_NEW_ACTIVATION_KEY = 'OLDER_LPA_NEW_ACTIVATION_KEY';
my thought was using the 
OLDER_LPA_NEW_ACTIVATION_KEY -> for a first time key generation
OLDER_LPA_FORCE_ACTIVATION_KEY -> for repeated requests.

Came up with 'forceactivationkey' flag when discussing with Adam, hence kept the same for the event codes too. Happy to rename.  
<img width="841" alt="Screenshot 2021-06-17 at 15 32 38" src="https://user-images.githubusercontent.com/6483585/122417267-475dea00-cf81-11eb-8b04-186a632016d8.png">

2021-06-17 14:42 UTC, SeemaMenon commented on service-front/app/test/CommonTest/Service/Lpa/AddOlderLpaTest.php
> +        $data = [
Got you :), perfect sense. Thanks Gemma.

2021-06-17 14:51 UTC, SeemaMenon commented on service-api/app/features/context/Integration/LpaContext.php
> +        $codeExists->Created = $createdDate;
Not sure why it was there originally, but since not being used..I am removing it.

2021-06-17 15:04 UTC, SeemaMenon commented on service-api/app/features/context/Integration/LpaContext.php
> +        $codeExists->Created = $createdDate;
Removed

2021-06-17 15:08 UTC, SeemaMenon commented on service-api/app/features/context/Integration/LpaContext.php
> +            'dob' => $dob->format('Y-m-d'),
Yes, my mistake again.

2021-06-17 15:58 UTC, SeemaMenon commented on service-api/app/features/context/Acceptance/LpaContext.php
> +        $this->apiFixtures->post('http://lpa-codes-pact-mock/v1/exists')
Oh yes, that's a good catch. Removed.

The alternative suggested would be great, needs working out how.

2021-06-18 07:22 UTC, SeemaMenon commented
@GemTay - Appreciate your attention to detail and THANKS a lot for your time reviewing this.

2021-06-18 11:28 UTC, SeemaMenon commented on service-api/app/src/App/src/Service/Log/EventCodes.php
> +    public const OLDER_LPA_NEW_ACTIVATION_KEY = 'OLDER_LPA_NEW_ACTIVATION_KEY';
So I have now removed the added event codes in api. Just introduced a new one[FORCE_ACTIVATION_KEY] in the front to  identify the repeated activation request. OLDER_LPA_SUCCESS would identify the first time request.

So we just have one new one and added to terraform too.

2021-06-21 09:16 UTC, GemTay commented on service-api/app/features/context/Acceptance/LpaContext.php
> +    public function iShouldHaveAnOptionToRegenerateAnActivationKeyForTheOldLPAIWantToAdd()
this function can be removed now that you have removed the feature step

2021-06-21 09:21 UTC, GemTay commented on service-api/app/features/context/Integration/LpaContext.php
> +    public function aLetterIsRequestedContainingAOneTimeUseCode($period=null)
not sure what this parameter is doing?

2021-06-21 09:25 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +
```suggestion
```

2021-06-21 09:28 UTC, GemTay commented on service-api/app/src/App/src/Service/Lpa/OlderLpaService.php
> +                            ];
the indentation/formatting on the lines above needs fixing

2021-06-21 09:32 UTC, SeemaMenon commented on service-api/app/features/context/Integration/LpaContext.php
> +    public function aLetterIsRequestedContainingAOneTimeUseCode($period=null)
My mistake. Was meant to be removed as part of clean up...Thanks Gemma.

2021-06-21 09:40 UTC, SeemaMenon commented
@GemTay  - The last few has been amended. Thanks and request a final one again please.

2021-06-21 10:24 UTC, GemTay requested changes
Couple more things

2021-06-21 10:24 UTC, GemTay commented on service-front/app/features/actor-add-an-older-lpa.feature
> +  @ui @integration
@SeemaMenon Remove the integration tag and steps from the integration context

2021-06-21 10:24 UTC, GemTay commented on service-front/app/test/CommonTest/Service/Lpa/AddOlderLpaTest.php
> +        $this->assertEquals(OlderLpaApiResponse::HAS_ACTIVATION_KEY, $result->getResponse());
the response event code wont be HAS_ACTIVATION_KEY, as you passed the force flag so it wont have checked if there was an activation key. You should be asserting that its equal to OlderLpaApiResponse::SUCCESS

2021-06-21 10:24 UTC, GemTay commented on service-front/app/test/CommonTest/Service/Lpa/FormatDateTest.php
> + * Class SortLpasTest
Wrong class

2021-06-21 10:24 UTC, GemTay commented on service-front/app/test/CommonTest/Service/Lpa/FormatDateTest.php
> +class FormatDateTest extends LpaFixtureTestCase
shouldnt this be `extends TestCase` ?

2021-06-21 11:02 UTC, SeemaMenon commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +        ];
Was keeping it the same format as used in handler. 
I am  OK to change if it helps reading.

2021-06-21 11:19 UTC, SeemaMenon commented on service-front/app/features/context/Integration/LpaContext.php
> +                $data['force_activation_key']
Total miss here...modified all.

2021-06-21 11:21 UTC, SeemaMenon commented on service-front/app/features/context/Integration/LpaContext.php
> +            $data['force_activation_key']
@Gemma, apologies....this file was missed. Modified all places in the file.

2021-06-21 11:23 UTC, SeemaMenon commented on service-front/app/test/CommonTest/Service/Lpa/FormatDateTest.php
> + * Class SortLpasTest
:( :( :(

2021-06-21 11:24 UTC, SeemaMenon commented on service-front/app/test/CommonTest/Service/Lpa/FormatDateTest.php
> +class FormatDateTest extends LpaFixtureTestCase
Yes, corrected.

Learning: Never Copy/Paste :(  or do it responsibly

2021-06-21 13:22 UTC, SeemaMenon commented on service-api/app/test/AppTest/Service/Lpa/OlderLpaServiceTest.php
> +            $result = $service->checkLPAMatchAndGetActorDetails($dataToMatch);
You are right.
Have now modified the checkLPAMatchAndGetActorDetails to not return exception in valid scenarios. 

The previous scenario [throws_exception_with_date_if_actor_has_active_activation_key()]
 no more being valid is changed  name and checkActorHasCode function returns a date if key exists.

2021-06-21 13:30 UTC, SeemaMenon commented on service-front/app/test/CommonTest/Service/Lpa/AddOlderLpaTest.php
> +        $this->assertEquals(OlderLpaApiResponse::HAS_ACTIVATION_KEY, $result->getResponse());
Such a shame, that's a good catch Gemma.
Modified  now. Thanks

2021-06-21 14:47 UTC, GemTay approved these changes
Nice one, all looks good now! Sorry for so many comments!

2021-06-22 11:54 UTC, cooperaj commented on service-front/app/features/actor-add-an-older-lpa.feature
> +  Scenario: The user is given an option to  generate a new key even if an activation key already exists
```suggestion
  Scenario: The user is given an option to generate a new key even if an activation key already exists
```

2021-06-22 11:54 UTC, cooperaj commented on service-front/app/features/actor-add-an-older-lpa.feature
> +  Scenario: The user is given an option to  generate a new key even if an activation key already exists
And fix to the test definiton (obviously :))

2021-06-22 11:54 UTC, cooperaj commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +                                'donorName' => (implode(' ', array_filter($result->getData()['donor_name']))),
Create ticket and make this a TODO to move the name "creation" to a Twig function as a part of the template.

2021-06-22 11:54 UTC, cooperaj commented on service-front/app/src/Common/src/Service/Lpa/AddOlderLpa.php
> +            'force_activation_key' => $forceActivationKey
```suggestion
            'reference_number'     => $lpaUid,
            'first_names'          => $firstnames,
            'last_name'            => $lastname,
            'dob'                  => $dob->format('Y-m-d'),
            'postcode'             => $postcode,
            'force_activation_key' => $forceActivationKey
```

2021-06-22 11:54 UTC, cooperaj commented on service-front/app/src/Common/src/Service/Lpa/AddOlderLpa.php
> +            'force_activation_key' => $forceActivationKey
Ensure indentation is consistant. We don't use this style in many places but should continue to do so if it's already in place

2021-06-22 11:54 UTC, cooperaj commented on service-front/app/src/Common/src/Service/Lpa/FormatDate.php
> +     * Violation of DRY so TODO: https://opgtransform.atlassian.net/browse/UML-1370
Is this TODO still applicable?

2021-06-22 11:54 UTC, cooperaj commented on service-front/app/src/Common/src/Service/Lpa/FormatDate.php
> +class FormatDate
May be better named as `LocalisedDate`?

2021-06-22 11:54 UTC, cooperaj commented on service-front/app/test/CommonTest/Service/Lpa/AddOlderLpaTest.php
> +                    'force_activation_key'      => false
```suggestion
                    'reference_number'     => (string) $this->olderLpa['reference_number'],
                    'first_names'          => $this->olderLpa['first_names'],
                    'last_name'            => $this->olderLpa['last_name'],
                    'dob'                  => ($this->olderLpa['dob'])->format('Y-m-d'),
                    'postcode'             => $this->olderLpa['postcode'],
                    'force_activation_key' => false
```

2021-06-22 11:54 UTC, cooperaj commented on service-front/app/test/CommonTest/Service/Lpa/AddOlderLpaTest.php
> +                    'force_activation_key'      => false
As above. Try to keep this style of indentation consistant across the code base. The number of spaces is always dictated by the longest key.

2021-06-22 14:41 UTC, SeemaMenon commented on service-front/app/src/Actor/src/Handler/CheckYourAnswersHandler.php
> +                                'donorName' => (implode(' ', array_filter($result->getData()['donor_name']))),
Done - https://opgtransform.atlassian.net/browse/UML-1523

2021-06-22 15:16 UTC, SeemaMenon commented on service-front/app/src/Common/src/Service/Lpa/FormatDate.php
> +     * Violation of DRY so TODO: https://opgtransform.atlassian.net/browse/UML-1370
Aah, this new class is handling date localisation in the front, currently used in CreateActivationKeyHandler and CheckYourAnswersHandler. And placed under common->service->lpa.

Shall remove this comment now.

2021-06-22 15:16 UTC, SeemaMenon commented on service-front/app/src/Common/src/Service/Lpa/FormatDate.php
> +class FormatDate
Yes, done.

2021-06-22 15:25 UTC, SeemaMenon commented on service-front/app/test/CommonTest/Service/Lpa/AddOlderLpaTest.php
> +                    'force_activation_key'      => false
OK,  correcting it for all test scenarios where applicable in this file.

2021-06-24 10:25 UTC, GemTay commented on service-front/app/src/Actor/src/Form/CreateNewActivationKey.php
> +    const FORM_NAME = 'create_new_activation_key';
```suggestion
    public const FORM_NAME = 'create_new_activation_key';
```
This will fix the linting error below

2021-06-24 10:34 UTC, GemTay reviewed
All looks good to me, just one last thing that was causing a linting error

2021-06-24 15:51 UTC, GemTay approved these changes
👍🏼

2021-06-24 16:43 UTC, SeemaMenon commented
@cooperaj  - Request your review/approval too please on this one. Been hanging here for toooo long  :) Thanks.

2021-06-29 08:27 UTC, merged