Uml 1568
ministryofjustice/opg-use-an-lpa pull request #998
Opened 2021-07-21 10:41 UTC by SeemaMenon

# Purpose

https://opgtransform.atlassian.net/browse/UML-1568

Fixes UML-1568

## Approach

_Explain how your code addresses the purpose of the change_

## Learning

_Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Use a Lasting Power of Attorney service_

## Checklist

* [X] I have performed a self-review of my own code
* [ ] I have added relevant logging with appropriate levels to my code
* [ ] I have updated documentation (Confluence/GitHub wiki/tech debt doc) where relevant
* [X] I have added tests to prove my work
* [ ] I have added welsh translation tags and updated translation files
* [ ] I have run an accessibility tool on any pages I have made changes to and fixed any issues found
* [ ] The product team have tested these changes

2021-07-22 15:33 UTC, GemTay commented on service-api/app/features/context/Acceptance/LpaContext.php
> +                'request_activation_key'    => false
Im confused as to what this new `request_activation_key` attribute is for, the purpose of this journey is to request an activation key?

2021-07-22 15:42 UTC, GemTay commented on service-api/app/src/App/src/Handler/LpasActionsHandler.php
> +        if ($requestData['request_activation_key']) {
Instead of this, it would be better to split this second part of the journey (user clicking to confirm the lpa is correct) into a new API handler and route. Much like how we have the `AddLpaValidationHandler` and `AddLpaConfirmationHandler` for the add an LPA journey

2021-07-22 15:57 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/check-right-lpa.html.twig
> +                                {{ user.first_names ~ ' ' ~  user.last_name }}
Mm, i feel like this is kind of cheating, we have identified the actor on the LPA, and returned that data back from the API so we can use it here to display. Just displaying what they typed in (even though it must have matched) feels wrong. Its also worth noting that we don't compare the middle name they entered, so if they entered a middlename that didnt match the LPA, then they could see the confirm page with either a different middlename to the one they entered, or no middlename as they didnt include it on the LPA in the first place. These could be some questions for Sarah

2021-07-22 15:59 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/check-right-lpa.html.twig
> +                                {{ user.first_names ~ ' ' ~  user.last_name }}
Also, theres an existing function called `actor_name` that you can use for formatting

2021-07-22 16:06 UTC, GemTay commented on service-front/app/src/Actor/templates/actor/partials/check-right-lpa-button-options.html.twig
> +<div class="govuk-grid-row">
This doesn't need to have been separated from the other template as it is not a reusable component, it will only be used in that one template, so best to just copy it into back in

2021-07-22 16:11 UTC, GemTay commented on service-front/app/src/Common/src/Service/Lpa/OlderLpaApiResponse.php
> +            self::ADD_LPA_FOUND
This event code is for the add an LPA journey, so it shouldn't be used here. You'll need to create a new one such as `OLDER_LPA_FOUND` ?

2021-07-22 16:15 UTC, GemTay commented on service-front/app/src/Common/src/Service/Lpa/AddOlderLpa.php
> +            return new OlderLpaApiResponse(OlderLpaApiResponse::ADD_LPA_FOUND, $lpaData);
i'd like to see a new DTO created for the response we expect back instead of just passing back an array

2021-07-22 16:20 UTC, GemTay requested changes
My apologies but I don't think this is the best approach, i've got an idea in my head of how I would implement it so i'm happy to pair with you whenever you're free and we could go through it :)

2021-07-23 08:25 UTC, SeemaMenon commented on service-api/app/src/App/src/Handler/LpasActionsHandler.php
> +        if ($requestData['request_activation_key']) {
@GemTay  - Makes sense the code design for the add lpa's and add older lpa's remain identical. I shall go through the former pattern.

2021-07-23 08:34 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/check-right-lpa.html.twig
> +                                {{ user.first_names ~ ' ' ~  user.last_name }}
Here I was assuming, 'your name' needs to what the user provided.... I didn't think about it too much for the same reason you mentioned, that we don't check for an LPA match based on the user name provided.

May be you are right. I Shall check this with Sarah and extract the full name if asked to. Even so how do compare the names still remains a question given that we only ask first name and last name.

2021-07-23 08:35 UTC, SeemaMenon commented on service-front/app/src/Actor/templates/actor/partials/check-right-lpa-button-options.html.twig
> +<div class="govuk-grid-row">
:) OK

2021-07-23 08:37 UTC, SeemaMenon commented on service-front/app/src/Common/src/Service/Lpa/OlderLpaApiResponse.php
> +            self::ADD_LPA_FOUND
Aah I was meant to rename this. Yes rightly spotted.

2021-07-23 08:39 UTC, SeemaMenon commented
> My apologies but I don't think this is the best approach, i've got an idea in my head of how it could be improved it so i'm happy to pair with you whenever you're free and we could go through it :)

@Gemma - Happy to speak anytime today :)

2021-07-23 09:16 UTC, cooperaj commented on service-api/app/features/actor-add-an-older-lpa.feature
> +    Then a letter is requested containing activation key
```suggestion
    Then I am shown the details of an LPA
    And I confirm that those details are correct
    Then a letter is requested containing a one time use code
```

2021-07-23 09:16 UTC, cooperaj commented on service-api/app/features/actor-add-an-older-lpa.feature
> +    Then a letter is requested containing activation key
Why this change?

2021-07-23 09:16 UTC, cooperaj commented on service-front/app/features/actor-add-an-older-lpa.feature
> +    Then I am shown details of the found LPA
```suggestion
    Then I am shown the details of an LPA
```

2021-07-23 09:16 UTC, cooperaj commented on service-front/app/features/actor-add-an-older-lpa.feature
> +    Then I am shown details of the found LPA
I think this step is used a bunch so won't comment again.

2021-07-23 09:16 UTC, cooperaj commented on service-front/app/features/actor-add-an-older-lpa.feature
> +    Then I am taken back to the start of requesting an activation key again
```suggestion
    Then I am taken back to the start of the "request an activation key" process
```

2021-07-23 09:16 UTC, cooperaj commented on service-front/app/features/context/UI/LpaContext.php
> +            $this->lpa->donor->firstname . '' .
```suggestion
            $this->lpa->donor->firstname . ' ' .
```

2021-07-23 09:16 UTC, cooperaj commented on service-front/app/src/Actor/templates/actor/check-right-lpa.html.twig
> +                                {{ user.first_names ~ ' ' ~  user.last_name }}
This page is the "check we've found the right LPA" page so should show details from the LPA.

2021-07-30 07:47 UTC, SeemaMenon commented
Gemma has pushed a new PR for this ticket after refactoring.

2021-07-30 07:47 UTC, closed without merging